### ISSUE TITLE
cache folder not created when updating 1.x to 2.0

### ISSUE THREAD

**Issue by ajaybhargav** [e107inc/e107#1013]
During 1.x to 2.0 update process e107_system folder is not updated. hence I am not able to enable cache. I get this error in cache menu in admin panel.

![screenshot2](https://cloud.githubusercontent.com/assets/927133/7720871/c51e4098-feef-11e4-82f4-2ac776609dea.png)

And because of this thumbs are not showing in the media manager.

Following directories and files should be created.. but none of them are there...
backup  cache  cookies.txt  filetypes.xml  import  logs  temp

**Comment by ajaybhargav** [comment]
Update: I think there is a missing check in the update process where e107_system should also be writable? I just made e107_system as writable and all folders are now created.

**Comment by LaocheXe** [comment]
As the picture is shown, The error message says that - that directory is not writable and to fix it change it to CHMOD 0777 (777)

I would put the blame on the server it self because some times it does not make directories writable (From my experiance - had a bunch of direcroties that needed to be 777 but where all 644 due to the hosting settings).

**Comment by tgtje** [comment]
As LaocheXe already answered about host settings; and some host do not accept 777; nice to know that 755 is just as affective.

**Comment by Moc** [comment]
I strongly recommend using 755 over 777 as the latter is highly risky when the server is incorrectly configured (which happens a lot I'm afraid).

**Comment by CaMer0n** [comment]
:+1:

**Comment by CaMer0n** [comment]
Closing, as this is not actually a bug.
