### ISSUE TITLE
language packs - questions

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1131]
Is there possibility to create uncomplete lang pack? For examle if you are in developer mode? 

What are differencies between controls in verify and generate packs? I mean this: (error's numbers are different)

![image](https://cloud.githubusercontent.com/assets/5429548/8633931/109bf91c-27e4-11e5-9002-29519d6ef164.png)

![image](https://cloud.githubusercontent.com/assets/5429548/8633933/250f4688-27e4-11e5-933b-45a774f4a73e.png)

Thanks

**Comment by tgtje** [comment]
also @CaMer0n 

Yes it is possible (for me) (by accident or intentional ?). 
BUT : system error > Folder is missing or not writable, you need to CHMOD 777 the following folder before uploading: ../e107_files/public (is NOT a part of v2) (not implemented yet?)
Create this folders and see below.....

You can not save a lang pack when your in let's call it window 2 AFTER you did run a verify test.
Go back to main menu (left) click Language-packs link
On that window (first) do not verify, but just click create lang pack (zip).
If it functions you will find the file in media/files folder..

**Comment by Jimmi08** [comment]
Thank you, but there is no file in media/files folder... 

By the way, you should change Welcome message, there are very old links... Funny, I didn't notice it before... 

![image](https://cloud.githubusercontent.com/assets/5429548/8634894/5b954acc-280c-11e5-9004-d60966e44e30.png)

**Comment by tgtje** [comment]
As posted : for me (the e107 files folder with inside public folder must exist else a no go (they have no other use)

**Comment by CaMer0n** [comment]
@tgtje e107_files should no longer be checked if you updated from Github recently.

**Comment by CaMer0n** [comment]
@Jimmi08 If you're not using the multilan plugin, then you are literally wasting your time with translating files. With this plugin you should never have an incomplete language pack.

**Comment by tgtje** [comment]
@CaMer0n  i know but it occured using the above mentioned method. The files are from 09-07.

**Comment by Jimmi08** [comment]
There is really path to e107_files/public folder
![image](https://cloud.githubusercontent.com/assets/5429548/8636981/3db0ec5c-287d-11e5-9424-f45c77f2d88e.png)

@tgtje sorry, I didn't check e107_files, but files in media folder

Then I got this message and I really hope that no mail was sent. Good to know that first checkbox is sending email. 

![image](https://cloud.githubusercontent.com/assets/5429548/8636969/ad3abae0-287c-11e5-8bb5-2c57adedba90.png)

**Comment by CaMer0n** [comment]
Line 576 of lancheck.php  (which is currently commented out)

    if(!is_writable(e_FILE."public"))

**Comment by tgtje** [comment]
Correct, but it was triggered (and do not know if it is supposed to) Hence mentioning it.

**Comment by Jimmi08** [comment]
Closing - I need to use multilang plugin, thanks for info.
