### ISSUE TITLE
[Problem] When "Update" a news

### ISSUE THREAD

**Issue by zekss** [e107inc/e107#1168]
Hi, Today I upgraded all old files that I have with the new files here and I have a problem. First (less important) I've installed on localhost the last versión of e107 and has a different theme on my computer than in my host web, but as I said, this is not the most important point.

Step to tell the real problem. I tried to edit a news using the option: "Tools --> <> Source Code". When I finished the edit and click on Update, appears me:

"<strong>notify Template detected

e107MailManager :: e107MailManager::sendEmails - Line 1836</strong>"

And below that title all arrays that shows the change, but when I check the news, did not change anything.

I leave an image with the situation immediately after that I clicked on "Update".

<img src="http://i.imgur.com/VO0hQul.jpg" />

Well, 
From already thank you very much.

**Comment by tgtje** [comment]
Just tested using latest files, can not reproduce the error.
With or without wysiwig, with or with email notification etc..
Editing by standard and by direct use of Source button/link.

since mailer seems involved : did the news item have (advanced) notify selected (configured?)? and by that > is your mailing also in order?

(using php 5.5.9 MySql 5.5.44 MariaDB)

**Comment by CaMer0n** [comment]
Is e_DEBUG set to true in your e107_config.php file?

**Comment by zekss** [comment]
Sorry for my late answer. I forgot the e_DEBUG config and yes, is set in true. I'll set in false and check again. Thanks

**Comment by Moc** [comment]
@zekss is this still an issue?

**Comment by zekss** [comment]
No, the problem has solved. The problem was that I had not changed e_DEBUG. Thanks for the help!
