### ISSUE TITLE
Issue: Forum Upgrade Step 6

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1236]
Step 6: Thread and post data
This step will copy all of your existing forum threads and posts into the new `forum_thread` and `forum_post` tables.
Depending on your forum size and speed of server, this could take some time.

Doing from e107 version 1.0.4 upgrade for the forums - on step 6 and hit a wall - wont do anything just stays there like if I broke something.

**Comment by Moc** [comment]
Could you provide a list of plugins that are installed?

**Comment by LaocheXe** [comment]
Wish I could, so many - had a few AACGC or was it AAGCG cant remember - either way I finally got it to work after removing all but the e107_images, e107_plugins, and e107_files folders and uploading the new code from GitHub here - got past that issue - however due to the plugins, one had an issue which for some reason it was pointing to a path called roster (e107_plugins/roster) was showing no image on the plugin manager and the name/title that was shown in plugin manager was Static Logging. had to go into the site prefs in the database and remove anything that had 'roster' in it (must have been a broken plugin that was installed once but removed and didn't really remove itself at all in the database.

The site is now up and running with the new code and only error I get in admin area is this:
Index	Query / Error
354  	SELECT COUNT(*) FROM gzm_forum_t
Table 'xxxxxx_dataBaseName.gzm_forum_t' doesn't exist

**Comment by Moc** [comment]
The way you are upgrading makes no sense at all, sorry to say it like that. 

Please follow the recommended steps as outlined here: https://github.com/e107inc/e107/issues/1242#issuecomment-158746100

Get rid of plugins and themes that you don't use beforehand, then overwrite the files with the new ones from Github and perform the database updates in the admin area. 

That should solve a lot of issues. 

The error you are getting is caused by the forum upgrade not completing successfully. In fact, it is still referencing the old forum tables which means that there either there is an outdated plugin, or not all the v1 files are correctly overwritten.
