### ISSUE TITLE
Issue: Upgrade

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1242]
Last week I took a backup of the database and made a new file "directory" separate from the default e107 v1.0.4 and upload e107 v2 to the new directory and uploaded a modified e107_config.php file (to point at a new database that has the backup database file on it).

Did the process of updating the database via e107 v2 admin area and all was good but the old plugins that I did not copy over where being displayed as plugins that I couldn't removed - so cleaned the database, uploaded the backup database to it, (copy the missiong plugins and folders) then try doing to steps again but end up getting an http error 500 - now on the main website that has v1.0.4 installed - can't access the admin area. using the basics for the e107 debug tool for firefox I get this: 

PHP Errors
Warning: fopen(../e107_themes/bootstrap3/theme.php) [function.fopen]: failed to open stream: No such file or directory, Line 717 of /home/clancoy1/public_html/main/class2.php
Warning: require_once(../e107_themes/4xA_047/languages/German.php) [function.require-once]: failed to open stream: No such file or directory, Line 16 of /home/clancoy1/public_html/main/e107_themes/4xA_0479/theme.php

The German language file I can understand, but the bootstrap 3 theme? Got no bootstrap 3 theme in v1.0.4

**Comment by Moc** [comment]
It looks like you made an error somewhere that updated the v1.0.4 database to v2, probably because you pointed to the main database and not the newly created database. That's the only explanation for the original v1.0.4 database to be updated. 

You should revert back to the previous situation using a backup. 

Please note that the way you upgrade the installation is not the recommended way, this may lead to all sorts of issues. Instead, you should:
- Backup both your files and database
- Overwrite the current files with the v2 package from e107.org OR the latest file from Github
- Go to your admin area and perform all the database updates (if some cannot be completed, STOP and report an issue to Github)

Only once the update is completed, go ahead and delete the plugins that you no longer use. 
I personally recommend to clean your v1.0.4 installation BEFORE updating to v2, by removing all plugins and themes that you do not use.

**Comment by CaMer0n** [comment]
@Moc :+1:
