### ISSUE TITLE
Error uploading user photograph

### ISSUE THREAD

**Issue by pricey1981** [e107inc/e107#1274]
Getting the following error when uploading a photograph on the usersettings page

Fatal error: Call to undefined function exif_imagetype() in /home/uknetrun/public_html/e107_handlers/upload_handler.php on line 565

**Comment by Moc** [comment]
This is because the upload handler has been rewritten to fix bugs, add more functionalities and increase performance (commit https://github.com/e107inc/e107/commit/af5ca367e80412a0860ff5a263d985df1a09be08). As a result, your webhosting provider needs to have the EXIF extension enabled. 

This is part of the regular server configurations on most hosting platforms but apparently not on yours. You'll therefore need to enable this extension on your server to fix the error.

**Comment by pricey1981** [comment]
thanks for this, investing with my host now
