### ISSUE TITLE
Database update message shown after upgrade

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1336]
Hello,

I have managed to upgrade my e107 to v2.0, but in keep getting this message in the admin saying :
"System Information
There is a database update available, please click button to install ..."

What could be the cause ?

**Comment by CaMer0n** [comment]
If you enable 'debug' (using the Firefox addon for example) it should display the reason for the notification.

**Comment by pierre0042** [comment]
System Debug
Plugin Update(s) Required - different version

**Comment by pierre0042** [comment]
Ok so I see that in the plugins list, e107 says that "Forum" must be upgraded :

forums_32.png 	Forum 	1.2 	2012-08-01 	content 	e107 Inc. 	Made for v2 	This plugin is a fully featured forum system. 


but the problem is that I have already upgraded this plugin...

**Comment by Moc** [comment]
If you go into Tools > Database > Check for updates. You should still see some updates you can perform.

**Comment by pierre0042** [comment]
It shows me

Update from 1.x to 2.0	OK
Add additional/missing core settings	OK
Forum 	UPDATE

Same issue : I have already done that.
If I try it fails on the tables creation.

**Comment by Moc** [comment]
This shows the the forum update has not been completed properly. I suggest going back to the backup and trying again. You can enable debug to have it display extra information which may be useful in case you run into issues. 

- Restore to backup 
- Download files from Github 
- Overwrite existing files with files from Github
- Go to the admin area and follow the database updates
- Remember to perform all database updates before doing anything else. 
- If you get stuck on any part during the update, STOP and ask in this issue report. Especially regarding the forum. All steps must be completed during the forum update. If you click on the update button next to 'forum', you get a new page with a dozen steps (or so) which you have to go through in order to update the forum properly.

**Comment by pierre0042** [comment]
Ok I will try this but I am sure I have already done this forum update.

**Comment by pierre0042** [comment]
The problems I encounter are that the tables creation at step2 fails, because the tables already exist.

Adding a check for this case would be nice.

**Comment by CaMer0n** [comment]
@pierre0042 I'll work on something.

**Comment by CaMer0n** [comment]
Please update from github and try again. Thanks

**Comment by pierre0042** [comment]
Thanks. I have less errors but it still fails :
http://imgur.com/j6W4JB0

Some tables exist and are not empty...

**Comment by CaMer0n** [comment]
@pierre0042 Please restore your v1.x forum tables, remove the new ones, and start again.

**Comment by pierre0042** [comment]
Ok I will try that, just to be sure, the v1 tables are : 
e107_forum
e107_forum_t
e107_forum_thanks (from a plugin I think)

**Comment by CaMer0n** [comment]
Yes!  (I have no idea about e107_forum_thanks)

**Comment by pierre0042** [comment]
Success
Congratulations, the forum upgrade is now completed!

Forum Version updated to version: 2.0 


Ok so I run through the 12 steps without error.
I have chosen to keep the v1 tables as backup.
I hope it will be ok now.

**Comment by pierre0042** [comment]
It's not working... In the plugin manager, it says that Forum must be upgraded to v2.0 :(
Is it maybe because I kept the old tables ?

**Comment by pierre0042** [comment]
I tried to rename the old tables but it's the same problem :
http://imgur.com/WxhYnVW

**Comment by CaMer0n** [comment]
@pierre0042 If you need to talk in real-time, please join us: https://gitter.im/e107inc/e107

**Comment by pierre0042** [comment]
Thanks to CaMer0n the upgrade is now fully done and no more message is displayed.
