### ISSUE TITLE
problem with demo content for gallery plugin

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1372]
Default (with installation) value for gallery category is gallery_image.  New gallery (manually inserted) has category gallery_image_2.
If somebody tries to use slideshow gallery menu for default category/from install, it doesn't work, because slideshow menu looks for image category gallery_image_

Thanks

**Comment by tgtje** [comment]
Just adding : maybe intentional use ???, i do not know, i was in understanding that when adding new pictures and added them to a new cat was the way..as cat 1 already is a kind of demo ???
But as Jimmi mentioned : the behaviour is there.. (out of the box with just adding menu = empty black box ( with message below; which when having 3 ??  images disappears)

**Comment by Jimmi08** [comment]
There should be at least warning, not use demo category for slideshow menu. I know it, but other people don't and they got black box with something like:  jumper has to be loaded before...

**Comment by tgtje** [comment]
Agree on that , i had to figure the use out for myself too....... maybe something for the admin field, or help docs??.

**Comment by Jimmi08** [comment]
Ha, maybe is problem somewhere else. After changing category for slideshow menu, I can't select default gallery back...  If this preferencie would be empty, people will know that they need to create new category.
