### ISSUE TITLE
Feature Request: Override core shortcodes from theme_shortcodes.php

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1484]
Which would be the best way to create a shortcode for a news template for a theme? can it be done in theme_shortcodes.php or do I need to create a theme_shortcode.php?

**Comment by Moc** [comment]
Reference: http://e107help.org/2295/where-can-custom-theme-news_template-shortcodes-be-defined

**Comment by CaMer0n** [comment]
At the moment the only way to register a 'global' shortcode is via a custom plugin using e_shortcode.php. Currently the theme shortcodes are limited to use by the theme template only. The option to allow theme shortcodes to function like e_shortcode.php and be used globally (including in a news template) is currently experimental. 

You can enable this feature to experiment with it by adding the following to e107_config.php 

    define('e_DEVELOPER', true); 

Please keep in mind that this may trigger other experimental features and unpredictable behavior.

**Comment by rica-carv** [comment]
Well, somehow, i've managed to use custom shortcodes on the news_template.php inside my theme, with this "hack":
theme_shortcodes.php
`	function __construct()
	{

		require(e_THEME."selospt v2/templates/news/news_shortcodes.php"); // don't use 'require_once'.
		
	}
`

and news_shortcodes.php, inside the theme, as called in previous code, has to be FULL CORE NEWS_SHORTCODES.PHP, edited to change code or add custom shortcodes....

For me, it works.....
The only drawback is that it has to be a copy of the core file, or if you delete the any core shortcodes on the theme file, they simply won't render, since they'll be missing....

**Comment by CaMer0n** [comment]
@LaocheXe @rica-carv I have removed the e_DEVELOPER check. You should now be able to override any core shortcode from within theme_shortcodes.php. 
```

class theme_shortcodes extends e_shortcode
{
      $override = true; 

      function sc_existing_shortcode($parm=null)
      {

      }

}
```

**Comment by Moc** [comment]
Keeping this open as a documentation reminder

**Comment by rica-carv** [comment]
@CaMer0n It's not working with news shortcodes.
It just renders as if there is no shortcode definition in theme_shortcodes, and still uses core shortcodes....

**Comment by Jimmi08** [comment]
Try use:  var $override = true; 

Tested with login shortcodes and it worked.

**Comment by rica-carv** [comment]
@Jimmi08 The issue is not the override. My
`function sc_newssummary($parm=null)
	{ ..... }`
simply returns blank.....

**Comment by Jimmi08** [comment]
@rica-carv  It was more info that it works with some shortcodes. I can't help you, I am not on news yet.

**Comment by rica-carv** [comment]
@Jimmi08 Maybe the issue is because news_shortcodes is in the e107_core, and maybe is handled diferently of other shortcodes....

**Comment by Moc** [comment]
@rica-carv Find @CaMer0n on gitter so you can debug this issue: https://gitter.im/e107inc/e107

**Comment by Jimmi08** [comment]
@CaMer0n  confirm problem with news shortcodes. Override works, no-error, just returns nothing, because there is no value for f.e 
`$this->news_item['news_title']  `
Of course, I know that there should be something different than $this, but I don't know what.

**Comment by CaMer0n** [comment]
@Jimmi08 Thanks. I'll look into it.

**Comment by rica-carv** [comment]
@CaMer0n If i can add a suggestion: one way to allow THEME shortcode overriding is to add some code for reading shortcodes from specific folders inside the theme (as is currently donne for specific templates inside a theme...) around line 375, 376 of shortcode_handler.php....
Maybe like this:
`$path = THEME.'override/shortcodes/batch/'.$pluginName.'_'.$_class_fname.'.php';`
`$className = 'override_'.$className;`
But that's just my personal opinion....

**Comment by CaMer0n** [comment]
@rica-carv You want to rewrite an entire batch of shortcodes? That's a lot of work. Isn't it easier to just override the few that you need modified?

I don't need to allow theme shortcode overriding, it is already functional. 

@Jimmi08 perhaps you were using the wrong code to override news. Here's my code that I test edusing the bootstrap3 theme and slightly modifying its theme_shortcodes.php file. 


    class theme_shortcodes extends e_shortcode
    {
	public $override = true; //added

	function __construct()
	{
		
	}
       
	function sc_news_summary()  // add override of news_summary shortcode
	{
		$sc = e107::getScBatch('news');  
		$data = $sc->getScVar('news_item');

		return "<span class='label label-danger'>".e107::getParser()->toHTML($data['news_summary'],'BODY')."</span>";
	}


	function sc_bootstrap_branding()
	{

Apart from the obvious change to what is displayed in the news item, I can also confirm the override is working using the Firefox e107 debugger in "BBCode and Shortcodes" mode. Here's a small portion of the results. 

![news_override](https://cloud.githubusercontent.com/assets/2825679/14931385/e59b6e8c-0e1f-11e6-9c03-ac16172cf097.png)

News is a little bit different in the way it grabs the shortcodes, since it uses 'news_item' rather than just the standard 'var'.  So, the NORMAL way to do it, would be like this: 

     function sc_attachments($parm=null)
     {
           $sc = e107::getScBatch('view', 'forum');
           $data = $sc->getVars();  // array of table data. 
           
           return $data['post_attachments'];
      }  

You can override any shortcode which uses a class (batch) in this way. As you found out, you cannot override the core single codes like GLYPH. Please tell me what you're trying to achieve as maybe the core function can be improved with some enhanced features.

**Comment by Jimmi08** [comment]
@CaMer0n Confirm it works. I just didn't know correct way how to replace $this->news_item.   I let you know if this stop with some shortcode.

This is final code, so I can left core shortcodes without new params and close that pull request.

```
function sc_newstags($parm='')
	{
    $sc = e107::getScBatch('news');  
    $data = $sc->getScVar('news_item');
		
		$tmp = explode(",",$data['news_meta_keywords']);
		$words = array();
		
		foreach($tmp as $val)
		{
			if(trim($val))
			{
				$url = e107::getUrl()->create('news/list/tag',array('tag'=>$val)); 
				$words[] = "<li><a href='".$url."'>".$val."</a></li> ";	
			}
		}
		
		if(count($words))
		{
			return implode($sep,$words);
		}
		else 
		{
			return '';
		}			
	}
```

**Comment by rica-carv** [comment]
@CaMer0n I don't want to replace ALL the shortcodes, that was my first approach on my theme, and i found it it would lead to conflicts if anyone changed the core shortcodes and if i have a old shortcode still on my theme.
I want only to replace certain shortcodes, as it is now on my theme (and wich reply i already give you there...).

I aknowledge you already setup the allowance to override core shortcodes inside theme_shortcodes.php, but just a small question: will not that be a little bit crumbersome and confusing if, for instance, i want to override news shortcodes, banner shortcodes, and so on???
Won't theme_shortcodes.php be a mix up and a little bit confusing with all the mixed up shortcodes??

By the way, regarding the news summary shortcode, what should it be used???
NEWS_SUMMARY (as is in [news_template.php](https://github.com/e107inc/e107/blob/master/e107_plugins/news/templates/news_template.php), line 99) or NEWSSUMMARY (as is in  [news_template.php](https://github.com/e107inc/e107/blob/master/e107_plugins/news/templates/news_template.php), line 140)???
It's that my previous attempt was to override the NEWSSUMMARY, not the NEWS_SUMMARY...

Anyway, i've tried to use your override news_summary code on my theme, and it still renders no text...
Even changing the core bootstrap3 theme_shortcodes.php file, it simply returns the regular shortcode....

**Comment by CaMer0n** [comment]
@rica-carv If an excessively large number of shortcodes need to be overridden then this signals to me that the core shortcodes need to be improved. Ideally, overriding should be done in exceptional cases when doing something really unique (reading/writing data from another table or manipulating the data. ) , not just when something needs to be styled differently using different html or css.   

I don't know why news-summary is not working for you. As you can see, it's working for @Jimmi08 and myself.

**Comment by rica-carv** [comment]
@CaMer0n I'm currently doing shortcode overriding because of html output, as [i've stated previously](https://github.com/e107inc/e107/pull/1557#issuecomment-211122239)....

I've pulled now the newest files from github, and updated both my clean e107 install and my development site (future live site), and in e107 install, the news_summary shortcode as you have, does render, but in my development site it doesn't!

Firefox E107 debug returns this really weird double news_summary shortcodes register:
![untitled 1](https://cloud.githubusercontent.com/assets/17130530/14937900/8c44f342-0f0c-11e6-893f-8e8208ce679d.jpg)

**Comment by rica-carv** [comment]
@CaMer0n Grrrr, i'm really stupid.....
Got it solved, it was my fault.....
I was using `$this->news_item["xxxx"]` call inside the override shortcode, and it simply blow it up.....
Had simply to adapt it to your code....
Sorry for all the trouble....
Now it's working like a charm.....
