### ISSUE TITLE
New post icons missing in 1.x theme

### ISSUE THREAD

**Issue by Brooniee** [e107inc/e107#1488]
Hi there,

The forum appears to be missing new/old post icons in 1.x theme

I've used inspect element to check if it references an image URL, but it does not appear too.

See:

https://www.crazy-fools.co.uk/e107_plugins/forum/forum.php

Thanks

**Comment by tgtje** [comment]
Hard to tell; they are present in install (partially the icons are called (right side poster) For BS and for legacy. Do you use own forum template? Testrun with BS theme to see if it works.

**Comment by Brooniee** [comment]
Yeah icons appear with bootstrap.

The icons appeared in the 1.x installed too, it's since the upgrade they have disappeared.

I had to copy some files before to enable a 'template', but haven't custom-coded anything

**Comment by tgtje** [comment]
Normally ( if i am correct) the forum folder in v1 state had no images/icon folder.
Now (_out of my head_) going back to forum adjusted themes, they had to copy the images too. Since i do not know how you have done it, check if the method is same and copy the icon folder also in there... I can be wrong, but as mentioned : out of memory...

**Comment by Brooniee** [comment]
Thanks for your help last night @CaMer0n - I've downloaded latest git but I'm still missing post icons though :(

is there any additional fixes/adjustments i need to do? (forum templates..?)
