### ISSUE TITLE
Display menu only on frontpage, how?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1496]
How can i define a menu display only on frontpage?
I've tried with `index`, doesn't work
`FRONTPAGE `also doesn't work
I can only make it work with `\!`, but i wonder if that's the only way to make a menu visible only on the frontpage....

**Comment by Jimmi08** [comment]
You can have layout for frontpage and menus are added to layout.

**Comment by tgtje** [comment]
e107help question.
Example : Index php is in BS3 > jumbotron home.  (theme php)
Find {WMESSAGE=force} add menu area below (new number not in use...!!); inside menu area post menu to use; change visibilty to index php only for menu. This is when standard; else use Jimako's reply.

**Comment by rica-carv** [comment]
Humm, i though i could do that directly on the menu manager admin area, since it's not a theme problem, but a general site setup...
I would like to keep that special setup even if i switch themes, got my point? :wink:

**Comment by tgtje** [comment]
Yes, but no. All menu's are put in meu AREAS. Areas are set in each theme. e107 is not an editor to instantly change website structures.
What you do say is correct however (example) bs3 uses 4 kinds of layout, where some parts are equal and others not. My prev example creates an area on a certain layout at a certain position. That area will nromally only exist in THAT layout.. Might be not but you need/want, but is very flexible.

**Comment by rica-carv** [comment]
@tgtje If that's so, for what purpose exists the menu visibility, on menus management???
I understand you, but isolated menus visibility shouldn't be defined by a theme, but from inside the admin, as is right now.
A theme designer never knows if a specific menu will be activated on menu area 1, 2, 3 or 10, right?

**Comment by Moc** [comment]
FRONTPAGE in the visibility settings should work in the menu manager. It it doesn't, it's probably a bug.

**Comment by rica-carv** [comment]
@Moc I've already tried that, as i've stated on my first message on this issue. Retried again right now, still doesn't work

**Comment by Moc** [comment]
Labelled as Bug.

**Comment by tgtje** [comment]
@rica-carv 
Specifying for understanding : menu areas vs menus.
Areas are 'positions/placeholders"  where menus are 'content'.

Purpose : visibilty to show the menu on only those pages (supposing layout is the same ( 2 - 3column)) the menu should appear. This is totally independant from menu area  in theme.
Language use also has an influence on them, but thats not for github purpose explain.

Isolated menus> no..  because the area defines the position, menu is still being placed there_ through admin and also visibility is to be adjusted through admin.
_As for where it will be activated > correct, but imagine if you create areas in (over the top) 100 areas throughout the theme layout.(top, left,right bottom,middle).. your good to go...

**Comment by CaMer0n** [comment]
@rica-carv Please try again using FRONTPAGE

**Comment by rica-carv** [comment]
@CaMer0n Confirmed, it's working! Thanks!

**Comment by PH5HP** [comment]
Hi,

I have the same issue. It works just one time and If I go back from another page to the main page my menu with the filter to be displayed only on the frontpage does not showon the frontpage any more.

I tried FRONTPAGE and even /!. Both gives me the same result. I can see it on the frontpage the first time after I set the visibility. After that I go to another page and when I go back to the frontpge it does not show anymore.

Anyone? I am using BS GAMING 01 as my theme (just for info).

Kind regards,
Henk - ph5hp.nl
