### ISSUE TITLE
Enhancement : Filetype file

### ISSUE THREAD

**Issue by tgtje** [e107inc/e107#1627]
Possibility to change filetypes xml through/within system ( assume ftp and/or filemanager from cPanel admin are not directly avaliable to  \* admin)), and changes are needed . ( idea sprouted from issue #1445 )

**Comment by Moc** [comment]
Summarising from the discussion on e107help.org:

- In some particular server configurations, the filetypes.xml file is not editable through FTP. 
- In this case, there is no way to change the allowed file extensions 

My argument remains that it is relatively simple for an admin login to be compromised rather than an FTP/MySQL login. Having an option in the admin area to change the allowed filetypes is thus relatively  dangerous and in my opinion should remain the way it is.

**Comment by Moc** [comment]
Closing. Not likely to change due to security risk.
