### ISSUE TITLE
e107 wiki access is forbidden

### ISSUE THREAD

**Issue by Sbaszz** [e107inc/e107#1640]
http://wiki.e107.org => forbidden.
Could you please fix this? Tx

**Comment by nesjett** [comment]
I saw this some days ago too, but I was waiting to see if it was an error or just some kind of maintenance

**Comment by Jimmi08** [comment]
It's some time now. I didn't copy some articles because somebody told that the same thing as with forum would not happen to wiki. But I think it's related to wiki itself.

**Comment by Moc** [comment]
This is related to a security issue with the wiki system. It is currently down until a solution is found and that may take a while as you noticed. 

We are looking into alternatives of converting the wiki content to some other system/website/display to provide access again, because we know that people are using and require the information that it contains.

**Comment by Moc** [comment]
Forgot to reply to this but the contents of the v1 wiki is available here: https://github.com/e107inc/e107v1/wiki
