### ISSUE TITLE
Question: Can SETIMAGE scale up a image?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1710]
Is it possible that the SETIMAGE shortcode could scale up a image?
Let's say i have a image size 600 x 400, and i would like to have it scaled up to 700 x 500, can it be possible?

**Comment by CaMer0n** [comment]
Line 304 of thumb.php 

	$sizeUp = ($this->_request['w'] > 110 || $this->_request['aw'] > 110) ? true : false; // don't resizeUp the icon images.

**Comment by rica-carv** [comment]
And how can use that with the SETIMAGE shortcode???

**Comment by CaMer0n** [comment]
It should be automatic. If the width of the image is greater than 110px then up-sizing is enabled.

**Comment by rica-carv** [comment]
@CaMer0n Well, with the SETIMAGE shortcode before the FEATUREBOX shortcode, that doesn't work, because i have some several 640x480 images, that i want scaled up to 1024x700 (for featurebox), and it simply are displayed in theyr normal 640x480 size.
I ended up solving this with a simple css mock...... :(

**Comment by Moc** [comment]
@rica-carv This is not my area of expertise so forgive me if this is a strange question, but when you scale up a 640x480 image to 1024x700, the aspect ratio changes, meaning the image will be shaped differently (e.g. stretched or made taller, whatever). 

The reason I'm saying this is because I think that the `{SETIMAGE: w=X}` should do what you want (replace X with the desired width, the height will be automatically determined by keeping the aspect ratio the same.

**Comment by rica-carv** [comment]
@Moc Indeed, if you "scale" a image from 640x480 to 1024x700, it will change the aspect ration, leading to strange images. Althought if i only set width or height, image should keep its apect ratio, since the other setting is missing, and therefore, the code should keep its aspect ratio. But that's not the point here, the fact is that if i have a 400x300 image mixed in a feturebox with more images of let's say, 1024x700, the lower image(s) is not scaled up, it keeps it's own original size. A bug? Maybe...

**Comment by Moc** [comment]
Is this issue still relevant?
