### ISSUE TITLE
Request: multiple admin links, plugin requirement and custom download dir.

### ISSUE THREAD

**Issue by dobem** [e107inc/e107#1744]
If it's not done yet, I would like to request:
1. Option to create more than one admin link for the same plugin (i.e, admin/navbar/myplugin).
2. Option to require another plugin before plugin's installation.
3. Option to customize download folders (i.e, not by date).

**Comment by rica-carv** [comment]
Regarding point 2, isn't there already a `<dependecies>` section in the [plugin.xml](http://e107.org/developer-manual/plugin-basics/setup-and-installation) of every plugin that can deal with that???

**Comment by Moc** [comment]
> Regarding point 2, isn't there already a <dependecies> section in the plugin.xml of every plugin that can deal with that???

Correct. This functionality was not completely working, but will be fixed once this pull-request is merged in: https://github.com/e107inc/e107/pull/1735

**Comment by dobem** [comment]
The #1735 fix will not work. I posted the reason there.

What about item 1 and 3?

**Comment by Moc** [comment]
Thanks for commenting on item 2, it will be discussed. 
The other two feature requests are noted down as requests but may take a while for them to be considered. If you're familiar with PHP, you could consider submitting pull-requests in order to achieve what you want. This will speed up the implementation process. 

Also, the next time, please keep each Github issue limited to one issue only rather than submitting three feature requests all at once. This way we can keep things organized more clearly. Thanks :)

**Comment by rica-carv** [comment]
@dobem I can't quite get the point of item 1.
Can you develop it a little bit more?
Why do you need more admin links for a plugin?
Can't you anchieve what you want by using the left side admin menu on the plugin admin area?

**Comment by dobem** [comment]
@moc I know it will take some time but I need to know if the requests are viable, otherwise I would have to  change the structure of my plugin.
Also, I will keep on issue at time.

About item 1:
Plugins can have a link to configure it, using <adminLinks> @plugin.xml.
Since my plugin has a lot of tables to manage, it would be nice if could create more than on link on the admin navigation menu.

For example, one for handling categories, other items.

`<adminLinks>
    <link url="category_config.php" ... </link>
    <link url="item_config.php" ... </link>
</adminLinks>`

**Comment by Moc** [comment]
Personally I think having more than one admin link is not viable since we want to keep the admin interface as simple as possible for e107 users. Having more links there will make it more confusing. 

A direct link the main plugin page, which then offers unlimited links in the side menu and tabs, suffices in my opinion. 

As for number 3, I don't really understand this. Are we talking about the download plugin?

**Comment by dobem** [comment]
Not sure if it's a problem of MediaManager os Download plugin.
If you upload a file, you have the option to change the path to the file, but even if you change it, the download will be saved as `{e_MEDIA_FILE}2016-06/example.txt`.

**Comment by Moc** [comment]
> If you upload a file, you have the option to change the path to the file, but even if you change it, the download will be saved as {e_MEDIA_FILE}2016-06/example.txt.

@CaMer0n Is this intended?

**Comment by dobem** [comment]
Sorry. I explained it wrong.

If you edit the path of your file to `{e_MEDIA_FILE}somedir/example.txt` after you upload it, the download_url at e107_download table will be save as `{e_MEDIA_FILE}somedir/example.txt` but the file will be moved to `{e_MEDIA_FILE}2016-06/example.txt`.

**Comment by Moc** [comment]
Sounds like a bug. We'll wait for Cameron to take a peek at this :)

**Comment by dobem** [comment]
We wait. I'm at work anyway.

**Comment by rica-carv** [comment]
@dobem Regarding item 1, you can do like you proposed, take a look at the [plugin.xml file from download plugin](https://github.com/e107inc/e107/blob/master/e107_plugins/download/plugin.xml#L6): 
`<adminLinks>
		<link url='admin_download.php' description='LAN_CONFIGURE' icon='images/downloads_32.png' iconSmall='images/downloads_16.png' primary='true' >DOWLAN_CAPTION</link>		
		<link url='admin_download.php' description='' icon='manage' iconSmall=''>DOWLAN_29</link>
		<link url='admin_download.php?create' description='' icon='add' iconSmall=''>DOWLAN_30</link>
		<link url='admin_download.php?cat' description='' icon='images/downloads_32.png' iconSmall=''>DOWLAN_31</link>
		<link url='admin_download.php?opt' description='' icon='settings' iconSmall=''>DOWLAN_32</link>	
		<link url='admin_download.php?limits' description='' icon='images/downloads_32.png' iconSmall=''>DOWLAN_112</link>
		<link url='admin_download.php?mirror' description='' icon='images/downloads_32.png' iconSmall=''>DOWLAN_128</link>		
	</adminLinks>`

These links are rendered in the left side admin menu for the donwload plugin....

**Comment by dobem** [comment]
@rica-carv
I've tried these options and it doesn't work.
I think the extra admin links on download/plugin.xml don't do anything at all. It's all commented inside `admin_download.php`.
Also, the option I need is to add more items on the navbar at admin area for my plugin.
The reason is to have a better/clean way to arrange your links in case you create a plugin with too many links/configuration.
Now that I know about `<dependencies>` I can separate my plugin into small ones. But I still think it would be a nice feature to implement.
It would be even better if we could add more links/sublinks to admin navbar using something like `e_sitelinks.php`

**Comment by rica-carv** [comment]
@dobem I've just given the download plugin plugin.xml file as example, as far i know, all v2 plugins must have the plugin.xml file...
For instance, you can also try with the [featurebox plugin.xml file](https://github.com/e107inc/e107/blob/master/e107_plugins/featurebox/plugin.xml)....

**Comment by CaMer0n** [comment]
@domem, regarding the media-manager, this is how it organizes it's files. All the paths are stored in it's database. Please share what you are trying to achieve and perhaps I can make suggestions.

**Comment by dobem** [comment]
@rica-carv I know how to create admin links on this menu. I've trying to say that the menu I want is the navbar. Lets ignore my request 1 because I've failed to explain exactly what I need.

@CaMer0n you said yourself, media-manager is organizing the files by itself. The way it organizes it, is very good for a blog for example but I want to organize my files on my own. All I'm asking is an way to do so.

I'm afraid I can't explain better than I've already did as I have two language barrier (english and programming).

Here is a step-by-step of my problem.
1. Admin Area -> Content -> Downloads
2. Create -> Choose a file -> (Media Manager opens)
3. Upload a File -> Add Files
4. Select the folder where the file will be place
5. Start Upload
6. Choose from Library -> Select
7. Close
8. Create the download

Step 4 is the one I need.

**Comment by rica-carv** [comment]
@CaMer0n Also, regarding item 3 (Media-manager folders), there's also anb annoyng issue. IF you grab your entire site files, and put it in another server (or even in the same server, but in a different folder...), all the media files are gonne, because the folder where they are located is not referenced anymore, since it will be created another folder. I've had that issue today, just by simply moving the site from one folder to another!
With "fixed" folder names, the images from media manager would be always on the same path, under the site address....
I don't understand why media manager creates those diferent paths for diferent installs....
If i do a site move, all the paths should remain exact as the original...
Imagine you have 1000 images under media manager. Reload them all again would be a real.....
So, here i kind of agree with @dobem proposal....

**Comment by CaMer0n** [comment]
@rica-carv If you use the same database name and prefix, the folder will be the same.

**Comment by Moc** [comment]
I am assuming this issue has been resolved or answered adequately. If there are still remaining questions, please let us know and I'll re-open.
