### ISSUE TITLE
Feature Request: Extended User Rich Text

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1775]
So there is a Textarea, but no Rich Text selection, trying to create a user bio but Textarea lacks the TnyMic and BB Code

**Comment by CaMer0n** [comment]
`$frm->bbarea() `?

**Comment by LaocheXe** [comment]
![capture1](https://cloud.githubusercontent.com/assets/5818022/16903141/fa3636b6-4c3a-11e6-966f-61066cd5989c.PNG)

![capture2](https://cloud.githubusercontent.com/assets/5818022/16903142/ffc9a05e-4c3a-11e6-8f96-c5c0aeb5788f.PNG)

![untitled-1](https://cloud.githubusercontent.com/assets/5818022/16903143/04bdf132-4c3b-11e6-9287-e23ec5c5cfaf.png)

**Comment by Moc** [comment]
@CaMer0n This needs updating: https://github.com/e107inc/e107/blob/644a10c370308f09e99c13f84a258230186fa433/e107_handlers/user_extended_class.php#L952

I'm afraid to change it because of backwards compatibility with fields already using the textarea now. Especially with the 'Field include text' (advanced tab when creating a new UEF). 

Another option is to just add add a new type "bbarea" which can be selected when creating a new UEF. That would avoid any BC issues. What do you think? If that's ok with you, I'll add it in.

**Comment by CaMer0n** [comment]
@CaMer0n This should be working now.

**Comment by Moc** [comment]
Done some testing with @CaMer0n and it is now working like it should. 

@LaocheXe Three years later, but it is implemented haha :)
