### ISSUE TITLE
how to replace missing admin images

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1822]
Hi,
I updated e_version plugin and it uses this admin images:
![image](https://cloud.githubusercontent.com/assets/5429548/18035736/ac016a0a-6d5b-11e6-9fd0-3106350fc361.png)
they are missing in version 2, what is correct way to replace them?
Thanks

**Comment by tgtje** [comment]
Change internal path + images (admin_getall) to own (e_vers) image folder ? An update can handle more than code of course..

**Comment by Jimmi08** [comment]
I solved it this way, I just dislike it, because now every plugin uses e_version has to have these images inside it. I don't understand why were admin images so much cleared when a lot of old plugins use them and they are still in core_image.php file as core images..

**Comment by tgtje** [comment]
Maybe pull and adding them (path changes of coursein plug) to e107_images/generic system folder?

**Comment by Jimmi08** [comment]
I could do it, but I don't know if it is purpose or not. I noticed some old images replaced by fa icons, maybe this is correct way. But it looks very bad when you install old plugin and you haven't them there. There are not just these ones. 
Using favicon has negative - if you have frontend editing too, and your theme doesn't use it.

**Comment by Moc** [comment]
The plugin needs to be updated. Either with new images or with the old ones. These images should be included in the plugin folder itself, as they are no longer present in the core. The plugin code should be updated to reflect the changes to the new images path.

**Comment by rica-carv** [comment]
E_version isn't a Father Barry plugin?

**Comment by Moc** [comment]
I thought we were talking about a plugin here right?

**Comment by rica-carv** [comment]
If it's a plugin, and since it needs to backward compatible (does it?), maybe just placing and linking the images to the plugin images folder itself should solve the issue....

**Comment by Moc** [comment]
Backwards compatibility only refers to core functionality (such as functions or methods - in php code -which are used by plugins and themes. Not so much to all core files. 

The admin images you are referring to have been removed and are simply not used in the core anymore. The core_image.php should list them as 'old', if it doesn't then this needs to be updated. 

Moreover, it's a really quick and easy job for the plugin author to update his or her plugin and simply include the images in the plugin itself. 

>  plugins should be upgraded to match the newer e107 version...

Yes, there are so many outdated e107 plugins out there. It is time for that plugin authors step up their game and upgrade their plugins or new plugins should be created. There are so many great new features in v2 that everyone can take advantage of. It's such a waste to be falling back onto old and deprecated methods which cause a lot of headaches and are very time-consuming for the developers. 

Concluding: Backwards compatibility does not apply in this case, since its a an image reference not a function/method reference (php code). Seeing how easy it is for the plugin author to address this issue, the old images will not return into core. 

Keeping the issue closed...

**Comment by Jimmi08** [comment]
Just explanation. These images are still in core_image.php but they don't exist anymore.   So I was curious why.

e_version plugin is special one. If you want your own plugin (f.e. links_page) to work with e_version, you need these images under your plugin too and yes, I made their own folder.  

I've already updated this plugin, because how to say it...  you try to ask for help one, twice...  and with no answers you do your own version.

**Comment by rica-carv** [comment]
>  you try to ask for help one, twice... and with no answers you do your own version. 

Indeed....

**Comment by Moc** [comment]
> Just explanation. These images are still in core_image.php but they don't exist anymore. So I was curious why.

If they are still in the core_image.php, they can (and should) be marked as 'old'. This way users can recognize that they are dealing with old files which can be deleted as they are no longer used by core. 
As per the above discussion, this issue is easily resolved by the plugin author. Either by including them in the plugin files or by changing from images to glyphs. I am not familiar with the code of this plugin but if needed I could take a look and help out. 

> you try to ask for help one, twice... and with no answers you do your own version.
Indeed....

Yes, that's the unfortunate thing about not having enough volunteers here with enough knowledge to help others out. Simply too many questions/issues and not enough time/resources to deal with them all in a timely manner. Every outstanding issue on Github will get its attention, but it may literally take weeks (or in some exceptional cases months).

**Comment by Jimmi08** [comment]
@Moc  I didn't have on mind this team.  Only the name you mentioned.  But let stop here.
