### ISSUE TITLE
None vs none, Capitalised LANS ... LAN_NONE should we use strtolower(LAN_NONE)

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1827]
OK, so we have LAN_NONE defined as None. But we need to use "none" not "None". 
Is it OK to use strtolower(LAN_NONE)? 
Particularly interested to hear from translators.

**Comment by MikeyGMT** [comment]
Works ok 
![image](https://cloud.githubusercontent.com/assets/2847651/18150136/80c0ebb2-6fdc-11e6-87eb-b2d1c2ddd819.png)

But is it going to be correct for translation?

**Comment by MikeyGMT** [comment]
Oh but ... something is not happy?
![image](https://cloud.githubusercontent.com/assets/2847651/18150277/83d8d7dc-6fdd-11e6-9233-22fc93459776.png)

**Comment by tgtje** [comment]
I personally would advice NO on strtol... reason if it gets a common practise, it will eventually give errors.
 example suppose it is believed...Ah i may use strtolower and used f.e in formfield (suppose user name) ...troubles...
Not happy? > a thing to be changed from FR_LAN_21 to LAN_NONE.
Since it is only in use in fileinspector i do not know if it also is 'hidden' in the 'check against file' (call name ???)
As for the word none why not ? each own locale does it in THEIR way (if they use capital, they will); BUT if the N (capital) also carries the function to emphasize (visual impression) the importance.... ??? small will take it away...

**Comment by MikeyGMT** [comment]
Agreed, it actually looks ok with capital N. Equally one could use 0.  

![image](https://cloud.githubusercontent.com/assets/2847651/18179823/1f58d236-707c-11e6-8f00-e5d479387e3f.png)
