### ISSUE TITLE
Constant logging out

### ISSUE THREAD

**Issue by Khade76** [e107inc/e107#1836]
Whenever changing any page it will log out the user no matter who they are. I have downloaded 1.04 to see if this happened with my current config, but it works perfectly no login issues at all.

**Comment by Moc** [comment]
Is this also the case in the admin area? 

If not, can you try accessing the preferences >  Security & Protection section? Please tell us the `User Tracking method` that is currently set and try switching it to the other option. 

Can you also provide your PHP version please? You can find it in the admin area in About > PHP Info

**Comment by LaocheXe** [comment]
I have this issue on my smart phone, idk if it's Google Chrome browser or something else.

**Comment by Moc** [comment]
@LaocheXe Same question for you as in my previous reply.

**Comment by LaocheXe** [comment]
@Moc sorry for the delay, the session is being tracked via cookies, and last time I used Sessions was a few years back (old e107) when a guy had issues with cookies, and again this happens on my smart phone. 

PHP version is 5.6.27

**Comment by Deltik** [comment]
This bug was caused by 220d258915313c9b895379e6be9db750a01ba3ed (specifically [this line](https://github.com/e107inc/e107/commit/220d258915313c9b895379e6be9db750a01ba3ed#diff-a5745596eb9bb46dabf26d7e53f651f4R434)).

If you are on revision c03945cd6377999e32ddbaf0a0ec89f3a9b52bc8, follow along in this stack trace:

1. e107 is shut down, with all singletons destroyed (including `e_core_session`):
   ```
   e107_class.php:5194, e107->destruct()
   footer.php:400, require_once()
   admin.php:875, {main}()
   ```
2. The problematic line creates a new `e_core_singleton`, but the validation preferences do not get set because of the guard at the top of `e_session->setDefaultSystemConfig()`.  This essentially causes `e_session::SECURITY_LEVEL_HIGH` to be used, which may be higher than what is actually configured.  As a result, this validation now fails:
   ```
   session_handler.php:653, e_core_session->validate()
   session_handler.php:466, e_core_session->init()
   session_handler.php:865, e_core_session->__construct()
   e107_class.php:1011, e107::getObject()
   e107_class.php:1416, e107::getSession()
   e107_class.php:4721, e107::canCache()
   class2.php:2895, e_http_header->send()
   footer.php:413, require_once()
   admin.php:875, {main}()
   ```
3. The session is destroyed:
   ```
   session_handler.php:835, e_core_session->destroy()
   session_handler.php:677, e_core_session->validate()
   session_handler.php:466, e_core_session->init()
   session_handler.php:865, e_core_session->__construct()
   e107_class.php:1011, e107::getObject()
   e107_class.php:1416, e107::getSession()
   e107_class.php:4721, e107::canCache()
   class2.php:2895, e_http_header->send()
   footer.php:413, require_once()
   admin.php:875, {main}()
   ```
