### ISSUE TITLE
Character problem of the date

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#1866]
If the date on the other language page, the accented characters​ not appears right (example: appears mÃ¡rc.​instead of márc.) - I have latest v2 from GitHub.

**Comment by tgtje** [comment]
I can confirm; datetimepicker can not handle diacritics for Hungarian nicely. Although language files do carry correct translation (afaik) they will either display (see above) or �

**Comment by Jimmi08** [comment]
I can confirm problem with coding of date in latest updates.. But I have opposite problem - my calender is ok, but displayed dates are wrong displayed. Maybe it would help to be able set this date somewhere to see problem:  because Friday on December has no national characters in my language.
![image](https://cloud.githubusercontent.com/assets/5429548/18615913/87656950-7db2-11e6-9f5d-1b8d345ddcde.png)

My issue:
![image](https://cloud.githubusercontent.com/assets/5429548/18615954/643b566e-7db3-11e6-8ec3-32db8324ad8c.png)
after saving:
![image](https://cloud.githubusercontent.com/assets/5429548/18615956/781f3eac-7db3-11e6-87f1-f97bf9e1c34e.png)
It's on news, so there shouldn't be problem with database coding.

I didn't notice this before because on localhost I have date coding problems from the beginning, but live site always worked correctly.

**Comment by fizi** [comment]
I see the problem on the news and userprofile.

**Comment by lonalore** [comment]
It happens because of utf8_encode() in date_handler.php (line ~200). If you apply utf8_encode() to an already UTF-8 string it will return a garbled UTF-8 output. I added a method to check if string is valid UTF-8, so it only uses utf8_encode() if string is not encoded in UTF-8.

@CaMer0n if it suits you, I could create a pull-request.

**Comment by CaMer0n** [comment]
@lonalore Yes please, thank you! :+1:

**Comment by fizi** [comment]
It seems the date is right. Thanks!

**Comment by CaMer0n** [comment]
Thank you @fizi for the confirmation.
