### ISSUE TITLE
Inserting images/emoticons is replaced by a thumbnail generator

### ISSUE THREAD

**Issue by jornmo** [e107inc/e107#1880]
For example, a shark emoticon turns into this:

`<img src="/thumb.php?src=&amp;w=100&amp;h=0"  title="shark" />`

Resulting in a big gray box

**Comment by rica-carv** [comment]
Maybe because it's a unfound image path....
Can it be something related to issue #1700?

**Comment by Moc** [comment]
I suggest you contact @CaMer0n (main developer of e107) directly through Gitter: https://gitter.im/e107inc/e107  for this specific issue. 

This is a chatroom based on Github accounts. He'll be able to assist you in real-time to debug the issue.

**Comment by CaMer0n** [comment]
I believe this was recently fixed. Are you using the latest files @jornmo ?

**Comment by Moc** [comment]
It may very well be that this issue is resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in Preferences > Advanced features
- Go to Tools > Database > Sync with Github 

Alternatively you can download the ZIP file with all the latest files included by hitting the 'Download ZIP' button at the top of this page: https://github.com/e107inc/e107
