### ISSUE TITLE
Documentation Project

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#1916]
Hi All, 

I've seen the documentation project, can I ask how we intend to implement system documentation? I ask because a lot of work went into the old wiki and it seems to have disappeared. 

Thanks 

Mikey

**Comment by Moc** [comment]
Hi :-) 

- Anyone with a Github account can contribute to the developer reference manual on e107.org. There is a 'contribute' button at the right bottom corner of each documentation section. Once you login you can make changes and submit these for review. 

- The Github project named 'documentation' which I initiated is meant to track the progress of moving documentation posted in the Github issues to the e107.org website. This is something that I have assigned myself to but until January next year I won't have too much time to work on this unfortunately. 

- It is my personal wish to complement the developer reference manual with documentation targeted at end-users more in the form of guides (which includes screenshots and possibly videos). I initiated this project through e107help.org but unfortunately we had to cancel due to the lack of resources (time mostly) http://e107help.org/update

**Comment by nesjett** [comment]
As a suggestion, the page I usually accessed from the old wiki was the e107 constants reference, would be nice to have a v2 reference, atleast of the most common/important ones.

Grts,
- Nes

**Comment by Moc** [comment]
@nesjett Noted, I thought these were already present in the developer reference manual on e107.org but I just checked and I cannot find them. Will get a list of the constants published asap.
