### ISSUE TITLE
Plugin from older e107 versions not installed.

### ISSUE THREAD

**Issue by g4you** [e107inc/e107#1943]
When I tried to install the plugins, always comes the message Bad link or Root directory not found. This happens with version e107 2.0. I have tried installing the e107 wiki? Is there generally problems with the plugins to install? E107 has no plugin directory

**Comment by rica-carv** [comment]
@g4you The e107 plugin directory is e107_plugins, under the root of your website. If it isn't there, then you have a uncompleted e107 install. Try to transfer all the files via FTP....

**Comment by g4you** [comment]
@rica-carv 
No I mean when I use in the new e107 when I use the search, he can not download it. Then comes the error message "bad link". This happens when you try to install old plugins.

**Comment by rica-carv** [comment]
@g4you Once more, workaround would be to transfer those old plugins via FTP to e107_plugins folder, and once donne, they're available to install in the admin area.

**Comment by tgtje** [comment]
Maybe some explanation needed : replicate the download of e107wiki (by) Ener (Alcides? https://github.com/alcides/e107wiki )  will fail because of no root folder.
Most likely in this case is the presented file on server (e107 org ??) where the zip file only contains the files NOT being inside a basic folder but just plain (structure norm is usually zip pack and inside the actual folder + content. Date of files available is of no influence as older ones are being processed fine.

**Comment by Moc** [comment]
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download' button at the top of this page: https://github.com/e107inc/e107
