### ISSUE TITLE
[bug] e107::getComment()->render() not ready to display mutiple times on same page

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1944]
As the tittle says, It seems that if you call reder() multiple times on the same page, It´s default behaviour will be broken.

It adds the comment as espected, and renders them, but the javascript is not done in the right way and it shows the resulting new comment on the wrong element.

Explanation:
The problem is that you handle a lot of things with ID in order of using Classes and find them trought parent (or somthing dynamic)

Scenario:
We would need a lot of comment forms on a social news feed, for example like facebook one.

I´ve already solved that, but I´m still working on making prev next buttons work, and edit one

Ill make a pull request when finished, hope it helps.

**Comment by nesjett** [comment]
Update: Im driving crazy with next prev buttons, can someone confirm that they are working as expected? (in my case they just doesnt do nothing)

**Comment by Moc** [comment]
@nesjett Have you been able to solve this?

**Comment by CaMer0n** [comment]
@Moc @nesjett @Jimmi08 @SimSync  This commit above is a partial fix that hopefully won't break the comments. If you guys can test my changes thoroughly over the next 48 hours, that would be very helpful. I have tested locally, and haven't found any issue so far.

**Comment by Moc** [comment]
So far, adding comments still seem to work. Haven't tested with multiple comment forms yet.

**Comment by Evgura** [comment]
@CaMer0n The whole structure of the comments was broken. Maybe because of CSS or Javascript.
Rolled back the update.

**Comment by Jimmi08** [comment]
Hi all, 
I don't know what to test because I hadn't any problem with comments (except the position of new reply comment with nested comments)

_before update:_
So I added nested comments to news, no problems, I changed setting to set nested off, I got paginated comments, button prev and next works.

_I updated_
Everything looks normal, both nested and not nested. 
I only noticed a bit slow reaction on next,prev buttons but it can my installation itself. 

_I added comment menu to news sidebar..._
everything works

It surprised me that Moderate comments took me to admin area...

Ok, I maybe have the problem:

-  single news
- click on reply -  works, the position of reply is fixed now
- click on reply on another comment - no reaction
after refresh, I can reply, but it takes visible time to display textarea (again it could be my problem) 

- I can open more reply textarea at once after refresh... just note, maybe it's ok. 

-  I have set Comment sorting - newest at first, but if I am on next page (not first), and a new comment is posted (not reply, first level comment), it's not visible, you need to manually click on pagination...

**Comment by CaMer0n** [comment]
@Evgura Did you try clearing the browser cache after updating?

**Comment by Evgura** [comment]
@CaMer0n Yeah, I cleared my browser cache. It doesn't help.

**Comment by CaMer0n** [comment]
Thank you @Evgura . Would you be okay to send me your theme (via Private message on Github) so I can test with it?

**Comment by Evgura** [comment]
@CaMer0n , As open source on github to send a personal message, theme BS_Magazine_02, I have the theme without any changes.

**Comment by CaMer0n** [comment]
okay, thank you @Evgura . I'll just download it then.

**Comment by Jimmi08** [comment]
@Evgura  theme from e107.org or from Fizi site?

**Comment by Evgura** [comment]
@Jimmi08 The website fizi I can not open the theme site e107.org

**Comment by Jimmi08** [comment]
@Evgura just posted you fix by mail you have on my site.  Test and you can close this.  This is the theme update problem, so the theme author needs to do it.

**Comment by Evgura** [comment]
Rename it "style" ?

**Comment by CaMer0n** [comment]
@fizi @Evgura All references (eg. in style.css) to `#comments-container` need to be changed to `.comments-container`

**Comment by Jimmi08** [comment]
> @Jimmi08 Rename it "style" ?

no, just upload. it's the way how to customize a theme without losing of the update feature

**Comment by Evgura** [comment]
I tried to change #comments-container to .comments-container and nothing has changed.
Uploaded file Jimako, all became well.

**Comment by Moc** [comment]
I am assuming this is fixed (when themes apply the right styling)

> All references (eg. in style.css) to #comments-container need to be changed to .comments-container
