### ISSUE TITLE
New private message admin form working with server time

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1951]
The new private message, on the admin area has the server time stamp, not taking in consideration the time offset setup on preferences....

![untitled 1](https://cloud.githubusercontent.com/assets/17130530/19578504/de660be0-9713-11e6-99c3-8edff99611a9.jpg)
![untitled 2](https://cloud.githubusercontent.com/assets/17130530/19578505/de6a5dd0-9713-11e6-8efe-34e27be46fe6.jpg)
![untitled 3](https://cloud.githubusercontent.com/assets/17130530/19578550/1610f42e-9714-11e6-9662-c7700fcd8fda.jpg)

**Comment by lonalore** [comment]
@rica-carv "Time offset" setting is not in used, and it should be removed. Time offset is set in [class2.php](https://github.com/e107inc/e107/blob/master/class2.php#L1145) using "Timezone" setting. In your case, Server-time and PM-sent time are "equals" because these values calculated using the same timezone due to [date_default_timezone_set()](https://github.com/e107inc/e107/blob/master/class2.php#L1145) (it sets the timezone globally).

**Comment by CaMer0n** [comment]
Closing.
