### ISSUE TITLE
Language=>Create

### ISSUE THREAD

**Issue by yesszus** [e107inc/e107#1955]
Language create not work.
This bug?

![language](https://cloud.githubusercontent.com/assets/17430115/19634137/b1d87c50-99b8-11e6-8696-a2b3cd70c4cb.png)

**Comment by tgtje** [comment]
Just took a look at it. I can confirm. However it always was Tables (dblan_97) before ? and that is missing now.. (did a fresh sync (just now) in comparison with site synced some weeks ago) At present can not pinpoint source (yet)
![oldnew](https://cloud.githubusercontent.com/assets/1811857/19635586/c0bbe9e0-99c3-11e6-9171-16405270827e.jpg)

**Comment by tgtje** [comment]
Need to update my post as i discovered i was a step ahead : 
explanation 
: when Multi-Language Database Tables option (prefs) is _disabled_ the Create page appears _blank_. When enabling this mode Create is changed into Tables..(with content if multi langs present).

**Comment by Moc** [comment]
This either needs a message or the menu item should be hidden then if the pref is set to disabled.

**Comment by tgtje** [comment]
Working !  however for me it is not notible that menu (left) refreshes when changing. Have to refresh page to see the outcome of switch.
So thinking over that one : instead of hiding Create a textual message that one has to enable a setting first as@moc already mentioned. (ala ..... working with tables and what to do )
