### ISSUE TITLE
[question]  what are differences in calling some class

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#1968]
I noticed in vstore plugin this:
in menu there is:
`require_once(e_PLUGIN.'vstore/vstore.class.php');
$vst = new vstore;`

but in page there is this code:

```
$vstore = e107::getSingleton('vstore',e_PLUGIN.'vstore/vstore.class.php');
$vstore->init();
```

Is there some diffs between menu and page or this are just two ways how to do the same ?
Thanks

**Comment by CaMer0n** [comment]
The Singleton is one of the simplest Patterns to understand. It's common usage is to ensure that only one instance of a class is ever instantiated. The reason for wanting such behaviour varies but typically it is because only one object instantiated from the source class is required and you want the resulting object to be available throughout an application, i.e. globally available. 

Source: http://www.patternsforphp.com/wiki/Singleton

**Comment by Jimmi08** [comment]
@CaMer0n 
Thank you. Question was why one time is used calling class file and second time is Singleton used.

**Comment by CaMer0n** [comment]
@Jimmi08 I forgot to change the one in the menu.
