### ISSUE TITLE
Forum.php Fatal error when upgrading 2.1.1 to 2.1.2

### ISSUE THREAD

**Issue by Aaronsss** [e107inc/e107#2006]
After upgrading from 2.1.1 to 2.1.2 I get the following error from the forum.php file:

Fatal error: Call to a member function parse_scbatch() on a non-object in website/p/forum/forum_shortcodes.php on line 4

The error is 'fixed' by restoring the old forum.php file from 2.1.1 but presumably the new one shouldn't be doing this. 

There is no file in the location its trying to access.

**Comment by rica-carv** [comment]
There's something wrong there.
The `website/p/forum/forum_shortcodes.php` is not a valid e107 path, therefore must be something else giving this error...

**Comment by Aaronsss** [comment]
I replaced the file path with website as it contains username and file location of my site which is irrelevant to the issue. I have renamed the plugin folder to p to keep the urls shorter in the e107_config.php folder. The rest of the the forum runs fine from that location and replacing the new forum.php file with the old makes it work again.

**Comment by tgtje** [comment]
as @rica-carv mentioned and you replied with path info.. it still bothers me where your reporting error on line 4 comes from.
Since about 4 to 5 motns there are nu real changes to be seen. Forum php did have a change (a lot is gone into own shortcodes). Now assuming this could be the shortcode handler having affect.. still line 4  is not showing of influence (line 4 is always commented aka 'header'info).
Now going back in time i can find something that relates to ssuch issu but that is in a much older file..
here's a line 4 (forum_shortcodes) `$forum_shortcodes = $tp -> e_sc -> parse_scbatch(__FILE__);
This file (forum_shortcodes)`resides in a file from around 27/12/2011 (v1.0.4) and supports the above paths mentioned on error line.. Please check and if so : your files are not up to date (or were not removed or earlier update was already not ok).

**Comment by Aaronsss** [comment]
Ok thanks for the comments. I compared the clean instal of 2.1.2 with what I had in the directory and there were a lot of old files (most of which were LAN files) but one of which was forum_post_shortcodes.php. After cleaning the directory of all no longer used files it works a treat.

Come to think of it I should probably do a similar thing on the whole site, I have been running e107 on it for 8 years :)

Thanks for the help

**Comment by tgtje** [comment]
Yw, and if it is alright, please close the issue.

**Comment by CaMer0n** [comment]
Closing.
