### ISSUE TITLE
Usersettings.php some information isnt displayed

### ISSUE THREAD

**Issue by Aaronsss** [e107inc/e107#2017]
After upgrading to bootstrap (2.1.2) I am finding on my site that the usersettings page is missing the following:

- The signature box doesn't show up despite it being set to display in the site preferences - signatures that were set up on the previous version still show up in the forum.
- Required field asterisk do not show up on required extended user fields on this page, they do however appear on the signup page. 

I did try the default theme and also copying the core templates files into the theme templates folder as a suggestion to an issues on a previous version to no avail.

**Comment by MikeyGMT** [comment]
backup (take a copy) of
e107_themes/templates
next 
copy e107_core/templates 
to 
e107_themes/templates

Re-implement any customisations of e107_themes/templates you did earlier

**Comment by Jimmi08** [comment]
I can confirm this.

**real name**  - don't display asterix if it's set as required on profile edit (usersettings.php) (I suppose it's general for each fields)
**custom title** - it's not displayed on signup page (it's not in template, it's not in shortcodes), but it's not displayed on profile page (user.php), but it's on edit profile (usersettings.php) . 
**email confirmation** - it's displayed on signup page, but not on profile edit page (probably not reason)

Otherwise I didn't notice differencies.

**Comment by Aaronsss** [comment]
Yes I beleive the astrix issue applies to a number of diffrent fields. Some additional potentially useful information:

The forum signature box does appear on the signup page.
When navigating to the users settings through the admin area the fields there do not show the required field astreix either. Maybe for this one its intentional.

**Comment by Moc** [comment]
Related #1767

**Comment by Moc** [comment]
As discussed, missing CSS class for .required

**Comment by CaMer0n** [comment]
I believe this is already fixed. Closing.
