### ISSUE TITLE
Forum shortcode { NEWTHREADBUTTONX }

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2126]
If I logged in, the button appear normally, if I not logged appear button with text (I think this is not good).
I logged: 
![logged](https://cloud.githubusercontent.com/assets/86780/21012749/d96b253e-bd57-11e6-966f-79795dac1ff9.jpg)
I not logged:
![notlogged](https://cloud.githubusercontent.com/assets/86780/21012762/e5923e06-bd57-11e6-8758-a1fdbb37fc22.jpg)

**Comment by rica-carv** [comment]
Somehow already discussed in #2052

**Comment by fizi** [comment]
I think It is so very ugly. My suggestion: non need the buttom, if anybody nor logged or not registered need the text: "Sign In or Register to comment." - in this way the system say what need make.  - Do not jump anywhere :)

**Comment by rica-carv** [comment]
So, as you're proposing, should it replace the "forum options" text with "sign in or register to create new topic", right?
Currently, the system with the text "forum options" is not jumping anywhere.
Anyway, currently if a user is not logged in, there's more option on the dropdown, and i personmally find very ugly just to leave there a dropdown arrow with no further indications.

Personally i guess it would be very much straight forward approach when a user is not logged in to leave the "new topic" button there, but disable it, and your text in a tooltip, so that when a user hovers it, can see why it is disabled...
What do you think of it?

**Comment by fizi** [comment]
Would be good too, if the "new topic" stay and disabled.
This problem on the viewtopic (Reply) and viewforum (New topic).

**Comment by CaMer0n** [comment]
Yes a disabled "New Topic" would be ideal. Is this what is in the patch @rica-carv  ?

**Comment by rica-carv** [comment]
Yes, @CaMer0n that's what in the patch.
It has to have some custom css and # href, since natively bootstrap doesn't allow that disbled items do have tooltips. Therefore the custom css inside the tag.
Further more, if i'm allowed to create newm LAN, i could do the tootlip LAN a different of what it is on the patch, where i tried to no create new LAN's...

P.S.: Commented on the tooltip there's a variant, without the "New Topic" text on the dropdown...
I thought of creating a parm for it, but i wanted everybody opinion...
No parm, default with disabled buton & tooltip
Parm "Nobutton", with only text on the dropdown...
