### ISSUE TITLE
News pagination

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2164]
The pagination on the news page don't work.

**Comment by Moc** [comment]
Cameron just committed a fix for this. Please test :)

It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the 'Download ZIP' button at the top of this page: https://github.com/e107inc/e107

**Comment by fizi** [comment]
Thanks! Work!
