### ISSUE TITLE
Pview Gallery Display

### ISSUE THREAD

**Issue by oui3kings** [e107inc/e107#2241]
May be similar issue as Random Avatar Menu in terms of how it does/does not display.

**Comment by Moc** [comment]
This concerns a third party plugin right?

**Comment by Moc** [comment]
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download' button at the top of this page: https://github.com/e107inc/e107

**Comment by Moc** [comment]
Closing this due to lack of feedback. Let us know if the issue persists.
