### ISSUE TITLE
Menu areas in theme template

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2254]
If I make MENU=300, I don't activate the menu on this menuarea.

**Comment by Moc** [comment]
Sorry I don't understand this completely. Could you explain it more?

**Comment by Jimmi08** [comment]
I can confirm. Test with new menu manager. If you have menuares 1,2,11,12,13... it works, but with 111, 112.

**Comment by Moc** [comment]
Ok, I understand. Question: would you really need XXX amount of menu areas?

**Comment by Jimmi08** [comment]
For me not. I used this if I had for example menus 41, 42 , 43 (because footer is section No.4) and then I needed to divide 41 and I didn't  want to rewrite others. So I did 411 412 42 43.  No problem to do it other way.  But it worked before and there is no information that you can't use it anymore.

**Comment by Moc** [comment]
@CaMer0n Was this intentional? What's your take on this?

**Comment by fizi** [comment]
I wanted to group the menus (example: in area 4 wanted 401,402,403)

**Comment by CaMer0n** [comment]
@Moc I couldn't reproduce it when I tested.

**Comment by Moc** [comment]
I assume this issue has been resolved. If not, please let us know and I'll reopen.
