### ISSUE TITLE
newforumposts_main plugin not shown, bug?

### ISSUE THREAD

**Issue by Killer0561** [e107inc/e107#2354]
Hello,

i try to activate the plugin newforumposts_main (at the top of the page), but it is not displayed, is the problem allready known?

I use a premium theme/template (dragonhead) from e107 v1.4. No custom template in my theme dir exits, its allready the default template. Same problem with custom extended user fields, but is allready fixed.

- Killer0561

**Comment by Moc** [comment]
It's showing up for me in the Boostrap 3 theme
Maybe an odd question, but you do have the forum plugin installed and there are actual posts right?

**Comment by Killer0561** [comment]
The newforumpost_menu works without problems, but nothing is shown to me in detail. The newforumposts_main plugin had the thread name + subforum, thread creator + date, views, replies, last answer + date.

**Comment by Moc** [comment]
Just for anyone reading along: 

- The newforumposts_MAIN plugin is not updated for v2 (yet?), and is still referring to the old forum database structure. Therefore the menu is not displayed (SQL errors) 
- The newforumposts_MENU within the forum plugin IS updated for the new forum database structure and is therefore working. 
- The issue here is that the newforumposts_MENU is lacking information compared to the newforumposts_MAIN plugin.

**Comment by Moc** [comment]
Should be resolved in the latest update. 

In your theme.php file you may need to check that you have `{NEWFORUMPOSTS}`
