### ISSUE TITLE
Theme Creation Tool

### ISSUE THREAD

**Issue by kreativmind** [e107inc/e107#2392]
When using the tool, the following sections are not created in the XML file upon completion:

- screenshots
- layouts
- stylesheets
- plugins
- theme preferences

Also, the date isn't in the format 2017-02-07 it's displayed as such date="253150142"

**Comment by LaocheXe** [comment]
Theme creation tool? never knew this was a thing.

**Comment by Jimmi08** [comment]
@LaocheXe Either me. Maybe it's too new. In Theme Manager Tools > Create New. It creates copy of theme with new name.

**Comment by Moc** [comment]
It's been added only very recently and will premiere in the 2.1.5 release.

**Comment by kreativmind** [comment]
It is new. Only a few days old in fact @LaocheXe and @Jimmi08 It's a great tool so that you can have the same thing as your favorite without messing up the original. Unless you paste the xml data from the original theme, it won't look and work properly as of right now until the code is fixed by @CaMer0n

**Comment by LaocheXe** [comment]
Lets think on how this can be executed - so where should the custom code be stored, in a database table - I'm thinking in e107_core as theme_code???

Next, gotta have the main e107 code to detect if you want to override the default theme files - or maybe add a check box in theme manager for that theme to enable override or don't.

Another thing to think about, for a new theme, have the site pull the current files and display them inside the text editor....

So the default files for any e107 theme would be style.css - theme.php, theme_shortcodes.php, - might be missing a few. however, some theme's may include other files such as js, css, etc... even random.php (to allow random image backgrounds or other...

Did I miss anything?

**Comment by Jimmi08** [comment]
@LaocheXe I admit I have no idea you are talking about. What is overriding default theme?
This tool just saves you time if you are customizing already existing theme, nothing more. In e107 there will be no system parent/child theme as wordpress have.   

I use parent/child theme system only because licence limits. I have one parent theme with all licenced assets and child theme for custom templates (theme.php use assets from parent theme). But all others files are copied and customized files.
