### ISSUE TITLE
[Question] Use menu parms outside menus, how?

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2397]
Somehow, this issue is related with #2369 , but it addresses the use of the menu parms outside a menu, if it can be possible.
For instance, i've got a menu with shortcodes, whose output relies on menu parms setup by admin on the menu manager area.
The shortcodes work as intended in the menu, no problem here.
The issue pops when i want to use the same shortcodes in a regular page, outside it's own menu.
Do i have to go the hard way and fetch the menu parms via MySQL, or there's a way i can get those parms via the e_menu class, somehow?
Or am i thinking things wrong here?

**Comment by Moc** [comment]
I don't know the answer to this question, but what I notice in your questions is that you go very detailed for specific methods, without explaining the end goal. 

To help developers understand more what you want, it sometimes helps to explain more of what you want to achieve rather than the 'step in between' of which you think is the solution. There may be an other way of doing things, usually easier, to achieve what you want. In this case you won't need the specific method you are asking for. 

I am not saying that this is the case in this specific question, but it's a general comment that may help for your future questions :) 

(not meant as criticism, it's positive advice 😄 )

**Comment by rica-carv** [comment]
@Moc No criticism taken, LOL

Regarding this issue, my aim is the following (by the way, this will happen all inside a plugin):
- I got a menu with it's own parms, either defined by admin ui, menu defaults file or parms via hardcoded menu.
Menu works fine and is displayed  via shortcodes that rely on those parms.
- On the same plugin, i'll design a page that will use the same menu shortcodes (ie: double use shortcodes or reusable shortcodes), to render almost the same menu info, but in a page format.
Since those reused shortcodes rely on those menu parms by default, they can't render properly if i can't have the menu parms available at page render time...

I don't know if i explain it right, but it's the best i can do right now...

Also, i might be thinking the wrong way, but to reduce workflow and file fetching, this is the best approach i have until now...

**Comment by CaMer0n** [comment]
I would use the menu.php file for both pages, but change the template used. 
ie. inside your 'page' set a constant or whatever that the menu would check. Include the menu php file and have that load a different template and render it.

**Comment by Moc** [comment]
I am assuming this question has been answered sufficiently, if not, please let me know and I'll re-open.

**Comment by rica-carv** [comment]
@Moc Not quite, but it's kind of irrelevant right now.
If this issue arises again, i'll let you know...
