### ISSUE TITLE
Wrong margin button on Verify Language-Packs

### ISSUE THREAD

**Issue by eduardocp** [e107inc/e107#2452]
The second button has a wrong margin-top

![image](https://cloud.githubusercontent.com/assets/1816859/23148527/19a44728-f7c5-11e6-8804-83ed2c61c030.png)

**Comment by rica-carv** [comment]
They might have different top margins because firts button is a `<input>`, rendered under bootstrap btn class, and the second is a `<a>` tag also rendered as bootstrap btn class.
This is a bootstrap old related bug:
[Buttons and anchors with the btn class have different heights #1794](https://github.com/twbs/bootstrap/issues/1794)
[.btn on input vs button vs href elements result in different heights in FF #2985](https://github.com/twbs/bootstrap/issues/2985)
