### ISSUE TITLE
How can i use template shortcode inside plugin template?

### ISSUE THREAD

**Issue by eduardocp** [e107inc/e107#2495]
The title is self explanatory...

**Comment by rica-carv** [comment]
If the template shortcode is changed or deleted, how would the plugin deal with it?
What are you trying to anchieve, can you explain in more detail?

**Comment by eduardocp** [comment]
@rica-carv I did it, but I do not know if it was the best way.

**What I need is this:** inside my theme, I have the templates folder and inside it I override the plugins template. But within these files I need to use specific shortcodes that will only exist for my theme.

**Example:** `my_theme/templates/forum/forum_template.php` I want to use a shortcode that will only exist in my theme.

**What I did:** within my theme_shortcodes.php file, in the constructor method I made the shortcode call of the plugin that I need (`require (e_PLUGIN. "plugin/shortcodes/batch/shortcode.php")`)

Is it the best way to do this?

**Comment by rica-carv** [comment]
@eduardocp Err, i think you might be a little confused....
Every plugin shortcodes is available inside the theme, when creating a custom plugin template (in your case, the forum plugin, and the forum_template.php)
You're doing it right, in the template part.
Now you don't need to include the forum shortcodes file. If you're making a shortcode only available in your theme, make it on the theme_shortcodes.php file. But if you need any variables from forum, that's another story...
If you can, please let me know what you're trying to anchieve, so i can develop further, if possible...

**Comment by eduardocp** [comment]
I'm not developing a plugin, just a theme. What I need is in the forum plugin template, to use a shortcode of my theme, but when I tried to do this directly (creating the shortcode in the `theme_shortcodes.php` file of my theme and using it in the forum template, it simply was not recognized the new shortcode...

**Comment by rica-carv** [comment]
@eduardocp You still got things mixed, or i simply can't explain me right. So this time, i'll do it in both languages...
**Português:** Eu percebi que você está criando um tema, e que quer colocar os seus shortcodes criados no tema no template do forum. No entanto, você não pode colocar o shortcode DIRECTAMENTE no template dentro do plugin fórum, se é isso que tem tentado fazer. Pura e simplesmente não vai funcionar, porque os shortcodes definidos no tema são para usar no tema, e os do plugin, no próprio plugin, ou em templates do plugin customizados DEFINIDOS NO TEMA! Expliquei-me ou continua tudo confuso? Dá uma olhada [neste tema, dentro da pasta templates](https://github.com/e107inc/e107/tree/master/e107_themes/landingzero/templates)... Em último caso, [podes-me contactar através do gitter](https://gitter.im/rica-carv), apesar de estarmos em fusos horários diferentes...
**English:** I understand you're making a theme, and wnat your theme custom shortcodes inside the forum plugin template, but you can't go and put your shortcode inside the forum templte INSIDE teh plugin itself, if that's what you're trying to do! Plain and simple it won't work, since the theme shortcodes are to be used inside the theme, and the plugin shortcodes can be used inside the plugin or in the customized plugin template INSIDE THE THEME! Did i explain correct or did i make it more confuse? Take a look on [this theme , inside the templates folder](https://github.com/e107inc/e107/tree/master/e107_themes/landingzero/templates)... In last case, [you can contact me directly through gitter](https://gitter.im/rica-carv), even if we're in different time zones...
