### ISSUE TITLE
Enhancement - possibility to load css file in theme after style.css

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2517]
I hope I explain this correctly.

style.css is always loaded and it's loaded as latest css files.  
Only way how change styling of theme (f.e. colors) is to change this file (or use inline styling).  But if you update from theme manager it's override with original style.css and you need to modify it again.

Couldn't be there some next file - f.e. custom.css - loaded after style.css if existed with these rules:
- all css customizations need to be done here
- theme pack can't use this file name. 

Just idea.

**Comment by tgtje** [comment]
@Jimmi08 

Think a split in question is needed : 
a)  has it to belong to core themes?
b) such option is present using stylesheets inside theme xml ( own created themes).?

**Comment by Jimmi08** [comment]
@tgtje 
it's generally problem. 
theme.xml is overriden by update too

**Comment by LaocheXe** [comment]
For a theme I've been working on over the past few years, I have a regular stile that uses style.css - then additional styles (dark.css, green.css, etc...) In the admin area - theme manager - select css file. Select dark, or green, over writes the styles.css.

Now to make the dark.css, etc... I copy the styles.css and rename it, and go change colors in it, etc... In the theme,xml file I would keep the styles.css as the default since I made all my additional changes in the style.css to begin with.

**Comment by Jimmi08** [comment]
We don't understand each other.

There is no problem for theme where you are author. ButT if you install f.e. core theme and then without creating your own copy you just change collors (and you can do it only in style.css or adding new css style), then next update of this theme (it is possible now from github or theme manager) will override your changes.

**Comment by rica-carv** [comment]
@Jimmi08 I suppose that's intedende, since core themes are "core" themes, therefore, if you need to change it, just make a copy of it and leave the core theme alone....
If you need a lot of changes in the core forum plugin, you also change the plugin? What will happen to it when e107 is upgraded?
Core plugins = core themes..... keep them original...
Please correct me if i'm wrong...

**Comment by Jimmi08** [comment]
I disagree. Ok, you do copy. And then?  Why there is update functionality? Your copy will not be updated. It's not for me, I really know what to do.

**Comment by Jimmi08** [comment]
So again. I would like to have one css file with name we agree on it that is loaded AFTER style.css.  Nothing more. One rule - if it will name f.e. theme.css or custom.css, it will be loaded AFTER style.css.  
So if you make copy, than you can just copy files from original theme without need to rewrite something, because your customization will be in separate file.

**Comment by rica-carv** [comment]
@Jimmi08 I think you're mixing things.... Core is to be kept as is, if you change antything core related, you will overwrite it on next update.
If you copy it, of course it won't be updated...
It's how it works, currently...

Anyway, how can you manage a update to know if you got a theme named theme1 or theme2007?? It can't, so they won't be updated, of course...
If you want to update the copied theme with the new updates made on the core parent theme, you'll have to do it yourself, because you'll have to manage all the replacements and merges "by hand"......

**Comment by LaocheXe** [comment]
I think I understand, kinda like how e_header.php for plugins loads anything, even css code. have you tried adding a e_header.php to the theme?

You want the theme to load style.css, and then you would like to also load another css, kinda like how bootstrap theme has the bootstrap css files, but style.css overwrites them.

I've talked about how Wordpress allows the admin to modify the theme in the admin area, custom html, css, etc... SFM has the same, the difference is that SFM saves teh data into the database, while Wordpress edits the file... or I got them mixed up. Im working on Defiantzstrap 3 - allows more customization than others.

**Comment by Jimmi08** [comment]
Yes, this is.  I agree,  it's confusing but others always look at it from view of theme developer. Look it from user view, when they are able to do some css customization themself without creating copy of theme.  

My simplier question or ask for enhancement is:  How to load some css file after loading style.css from theme without changing header template?

By the way, you shouldn't change original theme in WP either. Never, because you lost possibility to update. You should create child theme to be able update original theme. Or possibility to add inline css or js in theme options (this I already use in my themes, because sometimes you haven't access to ftp and you need to change it very quickly via admin area)

With e_header I am back to using special plugin for theme...   I can load css in footer but it would look crazy at least.
