### ISSUE TITLE
Issue: Forward Button Display

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2586]
`<i class="fa fa-forward icon-forward"></i>`

In admin area forward button display error
![capture1](https://cloud.githubusercontent.com/assets/5818022/25192043/58863ec4-24f7-11e7-8734-72f6382195e8.JPG)

However, reverse button shows
![capture2](https://cloud.githubusercontent.com/assets/5818022/25192078/8013afc6-24f7-11e7-8dc1-f882060455a3.JPG)

**Comment by Moc** [comment]
Just making sure, did you clear the e107 caches and browser cache?

**Comment by LaocheXe** [comment]
Yes

**Comment by Moc** [comment]
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download' button at the top of this page: https://github.com/e107inc/e107

**Comment by LaocheXe** [comment]
![previous-button](https://user-images.githubusercontent.com/5818022/33673580-c794d696-da72-11e7-9e3d-f3bc353a34f4.JPG)

**Comment by Moc** [comment]
Did you clear the cache?

**Comment by LaocheXe** [comment]
Yes

**Comment by CaMer0n** [comment]
@LaocheXe 
Please inspect and compare with mine: 
![image](https://user-images.githubusercontent.com/2825679/33681002-2a4766dc-da78-11e7-88bc-d6bb1a468c67.png)

A css conflict perhaps?

**Comment by LaocheXe** [comment]
![capture2](https://user-images.githubusercontent.com/5818022/33683158-9bd818fc-da8f-11e7-9130-a07b7058161a.JPG)

**Comment by LaocheXe** [comment]
Still displaying incorrectly for me, even with clear cache, refresh - happens on mobile devices, and on different web browsers. Also checked out if it's just the web host, tried on other sites hosted off of nfoservers, and ifastnet - same issue

**Comment by CaMer0n** [comment]
@LaocheXe Please paste the HTML of the button causing trouble.

**Comment by CaMer0n** [comment]
@LaocheXe How does it look after the last commit?

**Comment by LaocheXe** [comment]
Works, can now see the arrow button (next/forward)

**Comment by CaMer0n** [comment]
Thanks :+1:
