### ISSUE TITLE
forum_template to add "Attach file / image" and "Poll" sections* to the edit-screen of a forum post

### ISSUE THREAD

**Issue by JohanKlos** [e107inc/e107#260]
Add a forum_template to add "Attach file / image" and "Poll" sections* to the edit-screen of a forum post. 
It does show up when making a new reply or new thread, but not when editing a post/reply.

What forum_template file will allow me to modify the edit screen for my theme to allow the "Attach file / image" and "Poll" section*?

*An example of the "Attach file / image" section as in attached image below:
![image](https://f.cloud.github.com/assets/639844/469979/9483d652-b6e7-11e2-90ec-892749a5edfa.png)

**Comment by CaMer0n** [comment]
@Moc Is this one still an issue?

**Comment by Moc** [comment]
Hmm not sure, I would need to test. IIRC, there was an issue that certain options e.g. poll or file upload would or wouldn't show up on editing a post. 

Actually, I don't remember that well. We may just close it and let users report it again if it is still an issue, because in the foreseeable future I won't have time to test it.

**Comment by CaMer0n** [comment]
Okay Thanks. I believe it may be fixed. I'll close it, and another can be opened if necessary.
