### ISSUE TITLE
remove default <p> tag in tinymce and replace it with <br>

### ISSUE THREAD

**Issue by drasehat** [e107inc/e107#2620]
default `<p>` tag can really disturbing while we input contents with a lot of css styles.
this might help you to remove default `<p>` and `<span>` tags from tinymce

1. create folder your_theme/templates/tinymce/
2. copy mainadmin.xml from e107_plugins/tinymce4/templates/mainadmin.xml to your new folder
3. add this lines to mainadmin.xml 
`<forced_root_block>false</forced_root_block>`
    `<force_br_newlines>true</force_br_newlines>`
    `<force_p_newlines>false</force_p_newlines>`

before `</tinymce>`

with this, you can still write `<p>` or `<span>` tags manually anywhere in your contents
hope this help..

regards,
Indra

**Comment by Jimmi08** [comment]
Nice, but if you don't want to mess with core files and sometimes is p tag very handy, you could just remove it only for field you don't need it. 

In my case only needed field was CMENUBODY, so I do it this way:
`$text =  str_replace(array("<!-- bbcode-html-start --><p>","</p><!-- bbcode-html-end -->"), "", $text);`

https://www.e107.sk/forum/tip-and-tricks/8/how-to-remove-p-tags-from-cmenubody/

**Comment by drasehat** [comment]
nice idea @Jimmi08 ..
but how about every time we push enter button, tinymce create p tag automatically ?
i don't know about other user, but for me it is disturbing.

**Comment by Jimmi08** [comment]
You can change it to div tag manually.  Over time and many real examples I found it is only disturbing on menubody mainly because theming reasons - inserting p tag can need different css (changing child hierarchy in html dom), but otherwise no problem. It should be used for block of text, so using p or div tags is correct.  It was weird from beginning, but I am already used to it, so no complaints.  You can use solution with replace in table_style() function in theme.php for $text and then you have removed this tags completely or just for some style (f.e. menu).
