### ISSUE TITLE
Tools/database - can I change this to have possibility of better translation?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2640]
import and export options - the description string is the same as label.  In my language they are different. Other options are correct, only these two.

```
			'pref_editor'			=> array('diz'=>DBLAN_19, 'label'=> DBLAN_20),
		//	'backup_core'			=> array('diz'=>DBLAN_8, 'label'=> DBLAN_9),
		//	'verify_sql_record'		=> array('diz'=>DBLAN_35, 'label'=> DBLAN_36),
			'importForm'			=> array('diz'=>DBLAN_59, 'label'=> DBLAN_59),
			'exportForm'			=> array('diz'=>DBLAN_58, 'label'=> DBLAN_58),
			'sc_override_scan'		=> array('diz'=>DBLAN_55, 'label'=> DBLAN_56),
```

for backup options is LAN_CREATE used. But this terms is used in other parts (mainly to add new record to database) . Create record (add new record) and create backup have different translations

`$message .= "<br /><a class='e-ajax btn btn-success' data-loading-text='".DBLAN_71."' href='#backupstatus' data-src='".e_SELF."?mode=backup' >".LAN_CREATE."</a>";`

**Comment by tgtje** [comment]
My 2 cents on this : i would suggest **yes**. Since a backup is something different than a record (in meaning).
Although he goal is to simplify the LAN's in use and number;  diversity (which makes things more understandable; in this case 'splits' the actual true piece below for function use) would be a good thing. 👍

**Comment by Moc** [comment]
Feel free to submit a pull-request with the changes needed
