### ISSUE TITLE
CVE-2016-10378 SQL-injection vulnerability

### ISSUE THREAD

**Issue by fgeek** [e107inc/e107#2665]
What commit(s) and release(s) fixes this SQL injection vulnerability?

https://nvd.nist.gov/vuln/detail/CVE-2016-10378
```
e107 2.1.1 allows SQL injection by remote authenticated administrators via the pagelist parameter to e107_admin/menus.php, related to the menuSaveVisibility function.
```
Original blog post about this issue is in here: http://code610.blogspot.fi/2016/09/sql-injection-in-latest-e107-cms.html

Post also says:
```
Vendor was notified but to this day (16.09) - I did not received any response.
```
I don't know how author tried to contact you.

**Comment by Moc** [comment]
Security issues are not discussed in public here on Github. Please contact security@e107.org for more information. I have removed the details in your issue report for security reasons. 

I don't know the exact status of this security report, but I'd assume it has been solved since 2.1.5 as been released for some time which includes numerous changes to the affected area.

**Comment by Moc** [comment]
I've also sent you a private message with more details.

**Comment by fgeek** [comment]
Well it doesn't hurt anybody anymore to discuss about it publicly since it is public in the original blog post and in the CVE database. The information is "out there" so to say =)

**Comment by Moc** [comment]
I agree, but apparently the CVE details are not updated because the security issue is resolved. Until that time I am not disclosing more information than necessary in public, even though this is a minor security issue. 

I have bumped this so the CVE can be updated.
