### ISSUE TITLE
Install Issue with dash in database name

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2709]
If i setup the database name with a dash, ie: e107-master, my install gives me an error at final step 8, and it doesn't setup completelly the database.
I got to restart the install process, give that database name again (and this time, untick the create database), and this time it finishes setup...
My install definitions, as validated by install time in step 4:
![untitled 1](https://user-images.githubusercontent.com/17130530/27517403-e4e77954-59c3-11e7-9790-c849c1b6ce5c.jpg)

**Comment by tgtje** [comment]
Just my 2 cents. using the dash (hyphen) seems to have issues a lot of times, if you search for it. Manual added databasenames will normally be accepted, however (guessing here) some code you send (eg dbase creation) will likely be parsed and of the operator does see it as a minor character.  like 2 - 1 =1 instead of dname-here.  (sequence > e107- ...  ;-)

**Comment by Moc** [comment]
Cannot reproduce anymore, I guess it's fixed:

Installed successfully without any errors using `e107-master` as database name. 

PHP 5.6 and PHP 7 
MariaDB 10.3.12. 

If this is still an issue for anyone, please provide PHP and MySQL/MariaDB versions.
