### ISSUE TITLE
Issue: PageTitle

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2713]
I've been working on a new site and notice something strange on the index page.

![what-no-pagetitle](https://user-images.githubusercontent.com/5818022/27604922-83c94d22-5b40-11e7-878f-55d3071fd551.JPG)

In the image, you see the browser web page tab, it says "- 501st Legion"  while on another e107 website, the tab is called "Task Force 13" there is no " - ". Now I created a custom page (mods.php) which also showed the page title as " - 501st Legion" - until I added if(!defined("e_PAGETITLE")) {define("e_PAGETITLE", "501st Mods");} in the mods.php...

I looked at the Index.php and added if(!defined("e_PAGETITLE")) {define("e_PAGETITLE", "Landing Pad");} - to see what it would do, and "Landing Pad - 501st Legion" was displayed on the index page, and every other page as well, it even replaced the Forum - 501st Legion with Landing Pad - 501st Legion.

![what-yes-pagetitle](https://user-images.githubusercontent.com/5818022/27605073-121d63e2-5b41-11e7-8cfb-ecb6f551e3b7.JPG)

so I removed the if(!defined("e_PAGETITLE")) {define("e_PAGETITLE", "501st Mods");} in index.php since that really didnt work. Am I missing something? Shouldent Front Page have an option to add a page title?

**Comment by LaocheXe** [comment]
Update on this, since recent github updates - the Forum front end no longer shows a page title, as the last image I posted, says Forum - Site Name - now just shows Site Name, but when I click on a thread I get Thread Name / Forum - Site Name   <---  and working on plugins, I was told to add define('PAGE_NAME', 'This Page'); at the top of the php - which used to work, but I don't know when it stop working. Most, to all pages on the site only have the Site Name (On the browser tab).

**Comment by Moc** [comment]
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download' button at the top of this page: https://github.com/e107inc/e107
