### ISSUE TITLE
Issue: Forum Post Format

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2718]
![capture](https://user-images.githubusercontent.com/5818022/27719082-cd7c1d10-5d15-11e7-9dd1-fb4d854b1d54.JPG)

![capture2](https://user-images.githubusercontent.com/5818022/27719089-d0620efe-5d15-11e7-96db-c9cd165c7803.JPG)

As you notice on the first image, there are spacing, however, in the second image of the post, there is no spacing.

**Comment by tgtje** [comment]
Yep , it happens. Why ? not sure It is definitly how tiny works.. since years there is always something happening with linebreaks vs paragraphs etc... (and likely the browsers also have a hand in that).

Although i have no clue i confirm that this happens , but as a workaround ( i use tiny as less as possible), i always use **Shift+Enter** to add breaks.  That works _**nearly always and everywhere**_. Know it is a substitute and asks you to do things different, it is at least helpfull untill looked into.

**Comment by Jimmi08** [comment]
Just adding to @tgtje it's years old thing (issue?) with tiny and it was in version 3 related with used browser too (I can't say now)  . Standard - enter = only <p> tags were insterted (not in IE for example), enter+shift - <br> tags were insterted.  There was setting for tinymce (something like linebreak true/false) but it wasn't helping in all browsers. So shift-enter was only stable solution I knew. The same thing is in MS Word too - it depends on your settings - translation is "hard enter" but I don't know if this term is used in English too.   

If you are not sure, check your html output not how it looks.

**Comment by rica-carv** [comment]
@Jimmi08 Maybe "[forced line-break](https://en.wikipedia.org/wiki/Wikipedia:Line-break_handling)", instead of "hard enter", no?

**Comment by Jimmi08** [comment]
@rica-carv you can't change this in core files, so....  but yes, something like that

**Comment by Moc** [comment]
@LaocheXe Does this still happen with the latest version?

**Comment by LaocheXe** [comment]
Seems to be working correctly
