### ISSUE TITLE
Admin UI forms multiple selector

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2755]
How is possible to have a multiple choice selector (created from a plugin db table) for a field?
I've searched the [docs ](https://e107.org/developer-manual/plugin-basics#admin-ui)and can't figure out how to create it...

**Comment by tgtje** [comment]
Could the poll plugin not help you with some methods?

**Comment by rica-carv** [comment]
@tgtje I think you missed my point, I want to make multiple choices in a dropdown (or if not possible, in any other way), and not a single option selection, as is in poll plugin and admin_gallery.php.....
Something like this:
![bootstrap-multiselect 1](https://user-images.githubusercontent.com/17130530/28830601-233dc9ba-76cf-11e7-9783-8fd3c23e4fcb.png)

**Comment by tgtje** [comment]
Was meant as idea for coding, not the works..Multiple choice is a broad 'understanding'. Normally mcp is 1 question with 1 answer out of a list of answers..Multiselect is the ability to have more than 1 (and still be selected). Ok, just the idea.

How about incorporating the options (dropdown) presented in admin that switches the bars/titles (hide/display) for columns?  Just the idea because you got an idea (one has to sneak in) but when i see the image posted, it triggers more has to be added (eg the ultimate outcome)> in basic form function the admin dropdown comes close (maybe too 'broad' in function).? (just thinking along)

**Comment by Jimmi08** [comment]
what is differents againt checkbox field?
![image](https://user-images.githubusercontent.com/5429548/28844528-364eb8e4-7705-11e7-9d92-703566c5f9cf.png)

**Comment by rica-carv** [comment]
@Jimmi08 Nothing against, the weird is that my 'checkbox' field type only renders a single checkbox, without text, and the 'checkboxes' field type renders a list of check boxes with text.
How did you get that checkboxes style?

**Comment by Jimmi08** [comment]
@rica-carv is in news,  if I remember correctly you need to set parameter multi - or something like that.   I will try to check that user issue and this on newest version this evening (not sure, too hot here)

**Comment by rica-carv** [comment]
@Jimmi08 The admin config code in news is [this](https://github.com/e107inc/e107/blob/master/e107_admin/newspost.php#L452), and it's values for the dropdown is defined [here](https://github.com/e107inc/e107/blob/master/e107_admin/newspost.php#L854).
And you're right, it has [multiple parameter defined](https://github.com/e107inc/e107/blob/master/e107_admin/newspost.php#L855)....

**Comment by rica-carv** [comment]
I found out that currently i'll need two selects, one (standard format) for default parameter, and a second (using multiple parameter on form ui) for additional parameters...

Anyway, to simplify things, i'm thinking on using [this](http://loudev.com/#demos). Can it be possible? Any guidelines, please?

**Comment by rica-carv** [comment]
Ended up doing it another way. Thanks for all the help...
