### ISSUE TITLE
Extra '&' on params values

### ISSUE THREAD

**Issue by drasehat** [e107inc/e107#2764]
Hi Guys,
i'm working on how to make e107's shortcodes work in tinymce as page builder ..
so here is the picture:
![parms1](https://user-images.githubusercontent.com/25628686/29203662-9d3045fc-7e9c-11e7-8a5c-ed8af9187f26.jpg)

i make SHORTCODES menu in tinymce toolbar, so user can easy to access it without editing the original scripts.
here is the result :
![parms2](https://user-images.githubusercontent.com/25628686/29203700-e0ad50c2-7e9c-11e7-8684-b502f20fa482.jpg)

the case is, tinymce send the values with the '&' for second params and so on.. this is my sample function for click to action:
```
function sc_cta($parms){    
    $cont=$parms['text'];
    $color=$parms[$this->amp().'color'];
    $btext=$parms[$this->amp().'buttonText'];
    $blink=$parms[$this->amp().'buttonLink'];
    $style=$parms[$this->amp().'style'];
    $anim=$this->anim($parms);
    $text='
            <div class="click-to '.$color.'">
                <div class="container">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1 '.$anim['class'].'" '.$anim['atts'].' style=" '.$style.' ">
                            <div class="ct">
                                <div class="h3 col-md-9 text-center">'.$cont.'</div>
                                <div class="col-md-3 text-center"><a href="'.$blink.'" class="ct-btn">'.$btext.'</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>';
    return $text;
    }
```
`$this->amp()` returned '&' .. i tricked this to make all my functions working with the tinymce.
it would be great, if all params values use their own key without '&' in functions, is that possible ?
not urgent, i still can live with it 😄

**Comment by CaMer0n** [comment]
@drasehat I've been considering adding something similar to the core of e107 - drop-down menu of shortcodes in TinyMce.

**Comment by Jimmi08** [comment]
If I can. 

@drasehat  only problem with your solution **for me** is that you are calling it "shortcodes".  It could be confusing for  user or to hard explain it . In fact is template with many shortcodes inside.
 
@CaMer0n 
Dropdown of shortcodes could be helping but its not enough. But idea is good and theme author should be able to set what shortcodes should be in this dropdown.  Why?  Because with too many not used shortcodes it could be more difficult to use that to have external list and just copy them. Or add it to tinymce preferencies and only checked ON shortcodes would be in that dropdown.

I considered something like content blocks (with shortcode and templating for it)   So in tinymce area I would have only code {CONTECT_BLOCK=cta1} and in plugin I would have full setting and inserted more that one shortcode (like at that picture above).  This way I can insert menus too and manage them from one place.
