### ISSUE TITLE
e107.org FAQs (help wanted)

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#2824]
I would like to build a database of frequently asked questions concerning Installation, Usage and Developing with e107.  So, I'm looking for help from anyone in the community who can provide some questions. 

If you have some ideas, please login with your github account at e107.org and then go here: 

https://e107.org/faqs

.. and then use the "Ask a Question" button to submit questions. 

Thank you in advance

**Comment by rica-carv** [comment]
Humm, will this replace https://e107help.org/ ?

**Comment by tgtje** [comment]
Ahum @CaMer0n   at org : ?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch (no go )

**Comment by lonalore** [comment]
Hmm. I'm also haveing that problem during logging in with my Github account.

**Comment by Jimmi08** [comment]
I needed to go via incognito and log in aggain

**Comment by CaMer0n** [comment]
hmm.. must have been the last upgrade of hybridAuth. Looking into it.

**Comment by CaMer0n** [comment]
@rica-carv No it won't.

**Comment by CaMer0n** [comment]
@e107inc/honorary-contributors Please try again.

**Comment by tgtje** [comment]
Do not know if i miss something; using login php on org > no go (idem above); // using route > plugin/theme git login success; rerouting to faqs > still logged in and Question posted and accepted.

**Comment by CaMer0n** [comment]
Thank you @tgtje !

**Comment by Moc** [comment]
The plan for e107help is to turn it more into a community platform, which still includes the Q&A but in a different form. More news once we're further along the development process.

**Comment by CaMer0n** [comment]
Thanks @Moc ! What I'm aiming for on e107.org is a kind of "Quick Start" guide in the form of FAQs.

**Comment by Moc** [comment]
Exactly, quick start on e107, and community discussion/sharing/collaboration platform on e107help (which will be renamed to e107community.org)

**Comment by LaocheXe** [comment]
@CaMer0n can't login, get redirected to e107.org, went to add a theme/plugin, hit GitHub login, and a blank screen - url: http://e107.org/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch

**Comment by CaMer0n** [comment]
@LaocheXe Would you mind please trying again, but this time from https://e107.org (https)

**Comment by LaocheXe** [comment]
@CaMer0n same issue, Used the link you provide - click on GitHub login, url: http://e107.org/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch

The Login Github button url points to: https://e107.org/?route=system%2Fxup%2Fsignup&provider=github&back=aHR0cHM6Ly9lMTA3Lm9yZy9kZXZlbG9wZXJz

**Comment by CaMer0n** [comment]
hmmm. I just tried it twice and logged in each time. Very strange. 
@LaocheXe @tgtje 
Could you please go to https://github.com/settings/applications and "Revoke" access for "e107.org Developers" and then try logging in again?

**Comment by LaocheXe** [comment]
Same issue

**Comment by CaMer0n** [comment]
@LaocheXe At one point in the process the URL should look like this: 

`https://github.com/login/oauth/authorize?client_id=...... `

Would you mind trying again and posting that URL here? (sorry about all this)

**Comment by LaocheXe** [comment]
http://e107.org/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch

Same URL

Even tried in Google Chrome, (I wasnt logged into GitHub so I had to login), Then I get the same url as well, blank page.

**Comment by Jimmi08** [comment]
@LaocheXe clear your cookies and browser cache
No problems here.

**Comment by CaMer0n** [comment]
@LaocheXe Normally it will redirect to Github. https://github.com/login/oauth/authorize?client_id... etc. 
That URL is something else.

**Comment by martyshep** [comment]
I don't get logged in either? I see Please register and/or login to post a question.

**Comment by CaMer0n** [comment]
@martyshep Please go here first to login: https://e107.org/developers

**Comment by martyshep** [comment]
@cameron I get this error http://e107.org/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch

**Comment by CaMer0n** [comment]
@martyshep Did you end up at a Github URL before that one?

**Comment by martyshep** [comment]
No, straight to the error URL and blank screen

**Comment by Jimmi08** [comment]
@CaMer0n your link is with https  ( https://e107.org/developers)  he needs to use  http://e107.org/developers   (no https) -  that error is about wrong url

@martyshep  this happened to me some days ago, delete cookies in your browser and be carefull about url (without https)

**Comment by martyshep** [comment]
Used Firefox instead of Chrome worked fine. Think I'm logged into e107 using chrome on another PC too, was using chrome on android. Clearing cache might of fixed it too.

**Comment by CaMer0n** [comment]
@Jimmi08 Thanks. I have set e107.org to SSL only, and changed the Github callback URL to https://e107.org - I believe this should fix the issue.

**Comment by LaocheXe** [comment]
@CaMer0n works now.

**Comment by tgtje** [comment]
@CaMer0n  revoked and tested .. working 👍  (using login php to get git )

**Comment by weedshop2** [comment]
BUY THC PRODUCTS ONLINE  AND WEED text/Call +16615328526
Contact info
WHATSAPP: +16615328526
text/Call +16615328526
originalweedshop@gmail.com
site: originalweedshop.com
Welcome to the Original Weed online shop! We strive to offer you the best and widest selection of countercultural products. From 13 different cannabis strains, vaporizers, glass bongs and smoking accessories to grow kits, extraction kits and cleaning equipment. We have everything at the best price! We only deal with authentic objects … no imitations or imitations! Browse our product categories and keep an eye out for new items as we become America’s best online store!
Since 1997, The original weed shop located in Stanford Ave, Los Angeles has been steadily earning the reputation of being UNITED STATES Premier online weed dispensary!
We were the first, and remain the best head shop in the area. We helped pave the way for this industry to be where it is today and are here to take it into the future. Our brand new online original weed shop is the next step in our evolution.
 https://originalweedshop.com/product/buy-pink-lady-online/
https://originalweedshop.com/product/buy-super-lemon-haze-online/
https://originalweedshop.com/product/buy-ice-cream-cake-strain-online/
https://originalweedshop.com/product/face-mints/
https://originalweedshop.com/product/buy-og-kush-online/
https://originalweedshop.com/ https://originalweedshop.com/product/buy-zkittles-strain-online-min-order-1-https:/originalweedshop.com/product/buy-deadhead-og-kush-online/
https://originalweedshop.com/product/buy-royal-king-kush-online/
https://originalweedshop.com/product/buy-pink-budder-wax-online-min-order1-ounce/
https://originalweedshop.com/product/honeycomb-clearmin-order-15/
https://originalweedshop.com/product/ginger-dank-nugs/
https://originalweedshop.com/product/buy-viper-kush-online/
https://originalweedshop.com/product/moby-dick/
https://originalweedshop.com/product/buy-cantaloupe-haze-online/
https://originalweedshop.com/product/buy-skywalker-og https://originalweedshop.com/product/candyland/-0nline/
https://originalweedshop.com/product/buy-skywalker-og-0nline/
https://originalweedshop.com/product/buy-ak-47-online/
https://originalweedshop.com/product/buy-royal-king-kush-online/
https://originalweedshop.com/product/buy-ice-cream-cake-online/
https://originalweedshop.com/product/buy-guava-cake-online/
https://originalweedshop.com/product/buy-zombie-cookies-online/
https://originalweedshop.com/product/sour-tangie/
https://originalweedshop.com/product/buy-sweet-tooth-online/
https://originalweedshop.com/product/buy-black-widow-online/
https://originalweedshop.com/product/buy-comatose-online/
https://originalweedshop.com/product/buy-rockstar-og-online/

 Why Shop at ORIGINAL WEED SHOP?
Awesome selection, fast shipping, 24/7 customer service, all available in your pajamas. Or whatever you’re wearing; we don’t even want to know, TBH.
There are definitely differences between shopping at a local brick and mortar smoke shop versus shopping at an online headshop like ours.
Contact info
WHATSAPP: +16615328526
text/Call +16615328526
originalweedshop@gmail.com
site: originalweedshop.com

**Comment by tgtje** [comment]
User reported

**Comment by kirsch32** [comment]
https://linktr.ee/easysales
<a href="https://listafarmacia.com/">Pentobarbital Precio</a>
<a href="https://bohatstvi.com/">Koupit padělané peníze online</a>
<a href="https://farmacify.com/">Pentobarbital Sodico Comprar</a>
<a href="https://c24kredit.com/">Kredit Ohne Schufa</a>
<a href="https://unofarmaci.com/">Kaufen Nembutal online</a>
<a href="https://chempremium.com/">Buy JWH 018</a>
<a href="https://bioenergydirect.com/">Kaufen Holzpellets</a>
<a href="https://allfalschgeld.com/">Kaufen falschgeld</a>
<a href="https://ricoremedies.com/">Natrium Pentobarbital Kopen</a>
<a href="https://echtedoku.com/">Kaufen Dokumente</a>
<a href="https://echtfalschgeld.com/">falschgeld kaufen</a>
Pentobarbital Kaufen Ohne Rezept - Natrium Pentobarbital
<a href="https://makedonbud.com/">buy wood lumbers </a>
<a href="https://eurofalschgeld.com/">kaufen falschgeld</a>
[Natrium Pentobarbital Kaufen - Comprar Nembutal - Preis (prontofarmaci.com)](https://prontofarmaci.com/product/natrium-pentobarbital-kaufen/)
Natrium Pentobarbital Kaufen - Nembutal online Pries Ohne Rezept
<a href="https://globafarmaci.com/">COMPRARE PENTOBARBITAL ONLINE</a>
 Kaufen Sie Natrium pentobarbital ohne Rezept. Wir sind die vertrauenswürdigsten, zuverlässigsten, die Lieferung erfolgt bei uns
Nembutal Kaufen in Holland - Natrium Pentobarbital Kaufen
<a href="https://prontofarmaci.com/"> PENTOBARBITAL KAUFEN</a>
[Nembutal For Sale](https://prontofarmaci.com/product/nembutal-in-vendita/)
<a href="https://buonefarmaci.com/"> Nembutal-Penbarbital online</a>
https://prontofarmaci.com/prezzi/ 
<a href="https://prontapharma.com/">Comprar pentobarbital online</a>
<a href="https://farmaluxe.com">Kaufen Cyanide online</a>
<a href="https://dbesseiche.com/">Buy Pentobarbital Natrium</a>
https://t.me/falschgeldkaufe
https://t.me/suicidedrugs 
https://t.me/bigbambupaper
https://t.me/cyanidepoison
https://t.me/pentobarbitalnatrium
https://t.me/buytramadol50mgcapsules
https://t.me/Pentobarbital_Natrium

**Comment by kirsch32** [comment]
https://linktr.ee/easysales
<a href="https://listafarmacia.com/">Pentobarbital Precio</a>
<a href="https://bohatstvi.com/">Koupit padělané peníze online</a>
<a href="https://farmacify.com/">Pentobarbital Sodico Comprar</a>
<a href="https://c24kredit.com/">Kredit Ohne Schufa</a>
<a href="https://unofarmaci.com/">Kaufen Nembutal online</a>
<a href="https://chempremium.com/">Buy JWH 018</a>
<a href="https://bioenergydirect.com/">Kaufen Holzpellets</a>
<a href="https://allfalschgeld.com/">Kaufen falschgeld</a>
<a href="https://ricoremedies.com/">Natrium Pentobarbital Kopen</a>
<a href="https://echtedoku.com/">Kaufen Dokumente</a>
<a href="https://echtfalschgeld.com/">falschgeld kaufen</a>
Pentobarbital Kaufen Ohne Rezept - Natrium Pentobarbital
<a href="https://makedonbud.com/">buy wood lumbers </a>
<a href="https://eurofalschgeld.com/">kaufen falschgeld</a>
[Natrium Pentobarbital Kaufen - Comprar Nembutal - Preis (prontofarmaci.com)](https://prontofarmaci.com/product/natrium-pentobarbital-kaufen/)
Natrium Pentobarbital Kaufen - Nembutal online Pries Ohne Rezept
<a href="https://globafarmaci.com/">COMPRARE PENTOBARBITAL ONLINE</a>
 Kaufen Sie Natrium pentobarbital ohne Rezept. Wir sind die vertrauenswürdigsten, zuverlässigsten, die Lieferung erfolgt bei uns
Nembutal Kaufen in Holland - Natrium Pentobarbital Kaufen
<a href="https://prontofarmaci.com/"> PENTOBARBITAL KAUFEN</a>
[Nembutal For Sale](https://prontofarmaci.com/product/nembutal-in-vendita/)
<a href="https://buonefarmaci.com/"> Nembutal-Penbarbital online</a>
https://prontofarmaci.com/prezzi/ 
<a href="https://prontapharma.com/">Comprar pentobarbital online</a>
<a href="https://farmaluxe.com">Kaufen Cyanide online</a>
<a href="https://dbesseiche.com/">Buy Pentobarbital Natrium</a>
https://t.me/falschgeldkaufe
https://t.me/suicidedrugs 
https://t.me/bigbambupaper
https://t.me/cyanidepoison
https://t.me/pentobarbitalnatrium
https://t.me/buytramadol50mgcapsules
https://t.me/Pentobarbital_Natrium
