### ISSUE TITLE
Survey: What are the top 5 features of e107 for you, and why?

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#2826]
Examples: Inline-editing because..., simple admin area because..., batch changes because..., easy to use so.. etc etc. 
Please provide details if you can. 

@e107inc/honorary-contributors 

--- Copy/Paste Below --- 

1)

2)

3)

4)

5)

**Comment by martyshep** [comment]
1.  Built in forum
2. Can restrict content to registered members while still having a public/guest facing pages and images with userclasses
3. Single database for user access to site and email out 
4. Inline editing of news items
5. Built in Download plugin

**Comment by Jimmi08** [comment]
1. template and shortcode system
2. Admin UI (functionality)
3. Plugin Builder
4. Custom Fields
5. freedom in coding

**Comment by ulision** [comment]
1    for me that simplicity for full with things.
- facility of installation, that left nonvisible with dimensions administrator and that left visible with dimensions visitor.
- facility to be thus understood easy to improve by plugins or topics grafic which for me and a principal asset for a site the visual one.

2    a team of pro who helps smallest or the worthless ones like me and which follows the cms and which develops it while listening such or such idea of all people who serf of the cms. because the assistance that one can receive make also a great force of the cms, that very very important. a cms without a team which develops or which helps. it is a cms which will die .pour my share it was that a long ago which had enabled me to choose this cms. because at the beginning it was one of the cms more succeeds and a large number of forum of spoken but with final the indeed just only one forum will aurrai for to have spoken about it there.

3    thing for me which make that this cms and strong. it is that the administrator can measures that touches personal simply. but version 2 and much much less simple of this there with dimensions. (example me large beginner, I could modify such or such grafic thing plugin, topic, or codes php so that my site is as I want. with the version two much more difficult bus of the xml in more and full with thing one changed)

 4   that reliability, can of beug or not visible that top.

5    it is more one request of the user basic beginner like me. the basic user as me asks e107v2 it is a long life, many plugins, security, versatility because everyone do not write a blog or everyone does not present only images without contents. the contents of a site can be various either simple or very complex and e107 will have to be able to present any type of contents as the administrator wishes it and in the form which wishes, which misses with e107 it is the possibility of presenting graph or Camembert cheese 3D
interactivity and power to install files flash

**Comment by Norwayman** [comment]
1. Easy to use and intuitive for beginners.
2. No need for programing skills, but it helps.
3. Language pack in over 20 languages
4. Very customizable
5. Userclasses for restricting content to certain groups of users

**Comment by NZCyrus** [comment]
1. Posting future news items on selected dates and time.
2. Easy to Sync with GitHub as my preference, to stay on the latest development version.
3. Ability to change site theme easily, if required.
4. An active development team that gives me the confidence to stay on the latest development version in a live environment.
5. Easy SEO - SEF URL's, meta tags.

**Comment by veskoto** [comment]
Proper survey should be: What we need to improve and what new features to add?

**Comment by Jimmi08** [comment]
@veskoto I suppose that this survey is about something else.   Answer for your question could be this:  https://github.com/e107inc/e107/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement+sort%3Areactions-%2B1-desc
  (sorted by thumbs up)

**Comment by veskoto** [comment]
I can not understand what the point is to ask about the top 5 features!

**Comment by arunshekher** [comment]
1. Forum - its free, reliable, time-tested, unique, community and doesn't require additional setup or customization
    2. News - simplicity, manageability
    3. Chatbox - simplicity, the community aspect
    4. Internationalization - allows easy internationalization, built in tools for it
    5. Plugin and Theme API - easy to understand, opens multitude of possibilities
    6. Download - comes free, reliable, have a community aspect to it

**Comment by rica-carv** [comment]
1 - Forum (althought lacks a lot of bells & whistles like some other dedicated scripts have...)
2 - Liberty to code anything, or almost anything.... (other CMS are very rigid in coding...)
3 - User management
4 - Template & shortcode system, easy to customize (while others CMS are a real headache...)
5 - Support

**Comment by CaMer0n** [comment]
Thank you everyone, this is all very helpful! 
@veskoto The point to all this is that I am working on new content for e107.org. ;-)

**Comment by tgtje** [comment]
1. Proven stability ( 15 years and still going, in use rock solid)
2. For novice and experienced (everyone can use it at entry level, and alter when needed)
3. Suited for most wishes (bundled; build in packages)
4. Suited for worldwide use (languages +28 and growing)
5. Open Source (some might say : free)

**Comment by lonalore** [comment]
From a developer's point of view, or at least from a developer-first perspective:
1, Admin UI - easy to build admin pages and easy to build admin forms using a single Array
2, "e_" addon files for altering/expanding core functions
3, Templating and shortcode system, the ability to override other templates and shortcodes
4, APIs make life easier for delevolpers, so I love the Form API, Ajax API, JS Framework, JS/CSS Manager, Libraries API, the various parser functions and utilities, etc...
5, Easy to sync with GitHub, keep the system up-to-date

**Comment by hanklu** [comment]
Content, relationship , management is my key features request
1.image and video could save in difference hosting include system images,we could choose difference hosting by image folders for admin.(mirror and non mirror mode)
2.User relationship management, we could download or upload or import or export  member list include email and social...etc information like excel or SQL. We could easy use same user list in difference Web. Maybe we could put it in difference database hosting.
Bank or point or floewer systems to increase member post activity and relationship.
3.Lang files code change for PDF plugin in , we use UTF 8 in Web and download by big 5.
4.Powerful News system could choose new and blog in difference page in same admin area. In some company web, they will show product news, developer blog, Fanacil new... Etc in difference Page.
5.Forum system in difference page(in groups and admin page) for private group or admin  discussion.

**Comment by AdocArg** [comment]
1. Admin Area - It is truly very easy to use and understand, I think it's very well organized
2. Template & Shortcode system - very customizable and as lonalore said, the ability to override other templates and shortcodes
3. User management - ability of restricting content for certain users classes (like menus, news, etc)
4. Good organization of files and directories. - It's really an open source CMS, possibility to freely modify what you want (It's usually easy to find a file where you want to modify something)
5. Active support

**Comment by LaocheXe** [comment]
1. Easy to customize themes and plugins
2. Admin GUI, easy to understand (80+ year old compared it to Windows XP)
3. Stats (In Admin Area, how many users/forum post/news items, etc...)
4. Plugin Updates (Sync Plugin from e107)

**Comment by Jimmi08** [comment]
Just reminder:  alt_auth (if it would be part of core) would be nice feature.  No idea if it works  now.
