### ISSUE TITLE
Testimonials for e107.org

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#2836]
I'm looking for some positive and short testimonials to add to e107.org about why **you** use e107. 

I'll be choosing the best 8-10 of them. 

**IMPORTANT:  If you have used other CMSes, please mention which ones in your testimonial.** 

So, if you would like to contribute one, you can do so here: 

https://e107.org/testimonials (max. 250 chars)

Thank you in advance everyone!!

@e107inc/honorary-contributors

**Comment by oui3kings** [comment]
I really don't know where to begin with chronicling my positive experiences with e107! For starters, I have been using this amazing CMS since the early 2000's. Yep, it's been around that long. One thing that always stood out to me was the community of e107 users. There are a vast amount of plugins for really just about any utility or enhancement you can think of. The founders and those working/re-working the code are exceptional. You can almost have and in many cases have a direct line of communication with them. Any time I have need assistance or have had questions, someone has been there to help or explain. A lot of the plugins are relatively easy to tweak as well which has simplified things for someone like me who doesn't really code but can find my way around Dreamweaver or other editing apps. I'd say all in all, I have built easily over 100 sites using e107. To this day I still prefer e107 over other bigger name CMS'. Even tweaking themes is pretty easy even if you are just starting out. I'm sure most people will find everything from installing to getting your layout the way you want it really intuitive. Extremely happy to see this CMS take on new life with current v2 releases. Keep up the great work e107 dev & community!!

**Comment by Norwayman** [comment]
I was introduced to e107 in the early years of 2000 by my boss at my former workplace. I really liked it for it simplicity and ease of use for people with little or no coding skills. With e107 one can do powerful stuff without coding, but as I always have said.....it helps to know coding for extra tweaking and customizing. The comunity is amazing with many people who are willing to help out if one is stuck on a technical issue. Also, the volunteers in the translating team help e107 stand out with soon to be 30 languages translated of the latest official release. As more people see this powerful CMS and its simplicity and easyness the comunity will grow. A few years back I must admit I was a bit nervous when more and more people left because of the changes to v2, but I am glad I stayed on because now there is only up and forward. Thanks to everyone involved in making it happen. Thanks to e107 developers and the comunity. You are all great people!

**Comment by AdocArg** [comment]
Around 2014 i needed a CMS to do a work, because i didn't have much time. I tested many cms, including: Wordpress, Concrete5, Grav and Drupal, and let me tell you that none of them seemed so powerful and simple as e107: the admin UI, file system organization, the amount of plugins, languages packs, the active support and much more, made e107 my favorite CMS. Congratulations CaMer0n and of course, the people who contribute and make it possible that the CMS continue improving. 

Thanks to all, regards!

**Comment by rica-carv** [comment]
I stumble with e107 in mid's 2000's, when i wanted to create a comunity portal for my personal hobby site. At the time (and presently) i participate in a forum about my hobby, but that's it, just a forum, nothing more. Because i saw a lot of people was using the same "database" for the same purpose, i decided to "upgrade" my old static html personal site, and therefore, my aims were:

- To have a multiuser site
- Have a forum (like SMF - the one i'm participating - or better)
- Allow me some free coding and some customization "space" to work with

So, i begin a exaustive search for a CMS that allowed me the above.
I've tested several, among Drupal, Joomla, Concrete, Wordpress, SimpleCMS, and almost everything Google could throw at me.
In the end i ended up with e107 v1.x because it really fits me and allowed me to do what i want, a little bit slower, but it really suited me like a glove.
At the time i've had to learn almost everything by myself, inclunding PHP, JS, Prototype, etc.

So, i can thank e107 for teaching me (or forcing me to learn! 😄 ) everything i know today about web languages and more.

Today my site is a full functional v2.x one, despite the strugle and headache i had to make a upgrade from v1.x to v2.x. I've thought many times from dropping e107 and convert to another CMS, but even the latest versions of other CMS weren't so good as is e107 v2.x, so i decided to fight back, learn more, and make it work. And i suceeded!
With the help of the available comunity, and new online friends i made, it worked!
Thank you all!

At this time, i'll stick to e107 if it keeps the same philosophy, and as long it allow us to customize almost everything at our needs, i'll keep using it...
I've had some other side projects (dead now) in wich i used it, and i'll try always to use it before anything else, in last resort...

Just my two cents...

**Comment by CaMer0n** [comment]
These are all great, Thank you! 

But can you please submit them on the site? - there are a few more details in the form. 

First, Login here: 
https://e107.org/developers

...then go here: 
https://e107.org/testimonials

Thanks!

**Comment by rica-carv** [comment]
@CaMer0n Done... 👍

**Comment by Norwayman** [comment]
@CaMer0n  Done :)

**Comment by CaMer0n** [comment]
I have limited space, so most testimonials will need to be shortened for the site. I'll do my best to keep sentences unchanged and leave the full versions here.

**Comment by Jimmi08** [comment]
When I stumbled on e107 in 2013, I couldn’t believe my eyes. I had tried almost all available CMS to find a replace of my UN Nuke sites (the fork of PHP Nuke from 2002). I had spent 5 years trying to find replacement of it. Without success, I really don’t know why I had missed e107 at that time. I had tried almost all available CMS.  

They just released first Bootstrap version, but version 1.0.4 was enough for me at that time. It was so familiar, like to get back after long time to family. Not mention great people who have been helping me. I think that the old forum was a key factor for my decision to start with e107.  

Starting to use 1.0.4 was easy for me, but the beginning of version 2 was really hard; I often asked myself why I spend my time with it. But I saw that great potential and I couldn’t resist. And there was always somebody who got me over my struggling, who was so excited about my work that I couldn’t stop.  e107 is addictive. if you start to customize it, to make plugins or themes, if you find some of its hidden gems, you feel like you're a professional programmer even if it's just a hobby.; you have that feel of real coding. It‘s rare now with all that just install, uninstall, drag and drop well know CMS that you need to use for live being.  

So thank to all people who are improving this great software.

**Comment by CaMer0n** [comment]
@e107inc/honorary-contributors The new website design is online. Thank you to everyone who contributed a testimonial. More are certainly welcome! Just post the full version here and then post again on the site, as I'll need to edit it down to size.

**Comment by LaocheXe** [comment]
As a gamer, joining a gaming community is one thing, but helping creating a website is another. Back in 2007 I came across e107 while also checking out other content management software (CMS). Out of all the other CMS available at that time, e107 was one of the best, the community had develop many plugins for gaming communities, and had free themes, and support on e107 forums was the best support I've had ever seen. As a novice to web development, I could understand most of how to code themes, and plugins for e107, the admin area was easy to understand, and manipulate plugins, and themes was easy to do. As for today, I've worked with other CMS's and now e107 version 2 and up is still the best CMS to date that is easy to use, and easy to develop new plugins with the new plugin feature. I've worked on other 20 plus websites that use e107, and I can't wait to work on many more.

**Comment by CaMer0n** [comment]
Thank you Travis!! @LaocheXe  Once I receive a couple more testimonials, I'll have enough for a third slide (of 3) which will include your post.

**Comment by NZCyrus** [comment]
I highly recommend e107 as a CMS (Content Management System) purely for its ease of use and features. As an administrator, it has everything that you need to set up and run a website. The adminstrator's interface is simple to navigate and easy to understand with a number of management options and tools at your fingertips.

I have personally been running a community news site for a number of years that consists of over 2,500 news items. I find this site easy to maintain and cannot think of any extra features that I require from what is already offered. 

If you're looking for a CMS to get your content up and running I'd suggest that you try e107. A simple enough decision for me :)
Cyrus
Admin
https://www.promotiondata.com

**Comment by CaMer0n** [comment]
Thanks @NZCyrus ! Could you login on e107.org and post it here? https://e107.org/testimonials 
I need to associate it with your account so it grabs your avatar. ;-)

**Comment by fizi** [comment]
I've been using the e107 system since version 5.x. simple and flexible. It performs well in all areas, be it a business, gaming or blog site. You can create beautiful templates where the other portal systems are just stunning. Runs in several places without problems (company, sports club, etc.). This system is for me excellent.

**Comment by CaMer0n** [comment]
Thank you everyone! These last 3 have been added to the site. @NZCyrus @LaocheXe @fizi  (sorry some had to be shortened to fit, please let me know if you want something modified)
