### ISSUE TITLE
No gliph icons

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2863]
After latest upgrade from GitHub the Glyph icons disappears (example COMMENT_RATE).
(If I right glyph icons default is font awesome, span rewrited to i. And GLYPH sportcode use fontawesome? And got fa fa- prefix? -only name of icon need?)

**Comment by CaMer0n** [comment]
@fizi Please retest.

**Comment by fizi** [comment]
Not quite good:
Example: COMMENT_RATE shortcode good (hands appears)
I used {GLYPH=folder-close} and {GLYPH=eye-open} in templates... now the icons not appears.
If I use {GLYPH=folder} and {GLYPH=eye}...as named in the font awesome... the icons appears.
Need rewrite the templates and all icons shortcode that use the Glyph for display.

**Comment by CaMer0n** [comment]
@fizi Is folder-close and eye-open from Glyphicons or elsewhere?

**Comment by fizi** [comment]
From Glyphicons.

**Comment by CaMer0n** [comment]
Please re-open if necessary.

**Comment by fizi** [comment]
Now Works. Thanks!

**Comment by rica-carv** [comment]
I don't know if its related or not, but i got FONTAWESOME defined in my theme (`define("FONTAWESOME", 	4);`), and all my icons are rendered as glyphicons.....
Why?

**Comment by CaMer0n** [comment]
`fa-bell` for FontAwesome, `bell` for glyphicons.

**Comment by rica-carv** [comment]
@CaMer0n Previously the `{GLYPH:type=bell}` rendered a Fontawesome bell, not a Glyphicon.
Now it renders a Glyphicon....
It has something to do with latest pulls, because i got a earlier V2.1.7 live site working and rendering the Fontawesome icon, with exactly this same shortcode....

**Comment by rica-carv** [comment]
Even prevoiusly we could prevfix a icon called via GLYPH shortcode or function with icon-* and it would render a regular icon with the name specified. Now it ALWAYS renders a Glyphicon....

**Comment by CaMer0n** [comment]
@rica-carv You're correct, previous builds did do that, but it came with a performance hit.

**Comment by rica-carv** [comment]
@CaMer0n I understand that, but if i'm allowed, just my two cents:
Before we could change icons sitewide with a simple setting, the FONTAWESOME constant, now we got to got change every and single GLYPH shortcode to change them accordingly...
Furthermore, if we don't want any FONTAWESOME on a core template that uses GLYPH shortcode with fa-, we need to make that changes in the theme itself, on a copy of the core template.
Now we spend more time finding the "erroneous" icons, and if in the future the icons change again, we'll have to do it all over again...

Isn't more user friendly, and time saving to have only the FONTAWESOME constant (or any other else) defined, and make the GLYPH shortcode behave accordingly?
With a simple change in the cosntant, we could change the icons sitewide with a single change.... even the core ones...
I know it's hard to make it since it will need to scavenge a full array of a matching crosstable icons between fonts (the only thing nearest to it that i found is this: https://www.w3schools.com/icons/icons_reference.asp ), and perfomance it's not good, but it would be simpler and easier from the theme designer perspective, if you know what i mean....

Just my thoughts, sorry...

**Comment by Jimmi08** [comment]
My 2 cents. 
There should be never hardcoded fontawesome icons in core template.  I am sure that at many places they are inserted via shortcode because FONTAWESOME is set as true. Otherwise there is used old image or something like that.  

To complicate things - I often use bootstrap and fontawesome but I want images as icons.  
Similar way like coment icon is solution.  - constant - if not set in theme, then use core solution, if not, use theme settings. 
This should be applied for all icons used in core templates.

I think that now toGlyph works correct way -  the need to add "fa" to icons is because at the beginning there were only FA used.   What is problem - if you don't use FA on frontend, user still can use it in admin and then your frontend is broken.  From this view I understand rica's need for crosstable icons.

**Comment by rica-carv** [comment]
@Jimmi08 I agree with you, it should no be any hardcoded or forced icons on the core, they all should rely on the icons family choosen by the theme author.
And the GLYPH shortcode (or the toGlyph) had the functionality to do exactly that. Had....
Because now it doesn't!
Previously i could call the GLYPH shortcode without any specific font icon name, and it rendered a i element with specific icon class name, that i could afterwards aplly the icon i want via css, more or less the way you do, since i also use a lot of image icons...
