### ISSUE TITLE
problem with login with Chrome on localhost, hashLoginPassword is not defined

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2889]
I can't login in e107 on localhost, xampp, in Chrome. 
Browser cookies cleared. No error message. I tried it in Incognito window too. Nothing.

In console there is errror:
 
![image](https://user-images.githubusercontent.com/5429548/33255119-61c35536-d34c-11e7-9328-8c4ccb8589ec.png)

No problem in Firefox. Only some warning:
 
![image](https://user-images.githubusercontent.com/5429548/33255204-be52159e-d34c-11e7-9a28-2acf18b73e5b.png)

PHP7.0.15, xampp, bootstrap 3 default theme.  

Thanks

**Comment by tgtje** [comment]
Thanks, thought i was the only one having issues with xampp and Chrome. Been looking for a solution, and last (most mentioned...ongoing struggle with Chrome) seems to point out that Chrome likes a v3 certificate. (xampp is normally v1 open ssl). thread : https://community.apachefriends.org/viewtopic.php?f=16&t=75613&sid=a9f8cf10923aa1c788f4ecfea004955f&start=15#)  
Indeed the same: using FF no troubles.. (php 5.6.32 and php 7.1.11 FRESH/new installations due to Chrome issues exactly the same. No results yet...

**Comment by Jimmi08** [comment]
@tgtje just info:  
way how to add v3 to xampp
https://community.apachefriends.org/viewtopic.php?p=256428&sid=57f424751a8e46e0cb39a7ef1f4d52cf#p256489
then I run makecert.bat  
then installed it according last post in that forum
- I have problem with location, so itsnot trusted, but v3 version is there
![image](https://user-images.githubusercontent.com/5429548/33272926-054f4fc2-d38c-11e7-84f1-b0ed0b7f56bc.png)
No change.

**Comment by tgtje** [comment]
Found something (well Opera refuses) np other settings applied (not v3 too) just plain.Asuming you do use same as me : localhost >  use 127.0.0.1   It works at least... (except Opera still refuses on numbers and localh)

**Comment by tgtje** [comment]
Well did not see the error reported by Jimmy08, did a new fresh install (php 7.1.11 xamp) Tested after syncing Github now (incl. commits), Chrome (latest)FF (Latest quantum... nice speed that new one); Opera latest> some tweeks ; ; Edge; IE (11)  Localhost (as name) accepted.. for me  👍

**Comment by Jimmi08** [comment]
Works. Thanks.
