### ISSUE TITLE
Cannot pass step 6 of installation on PHP 7.2

### ISSUE THREAD

**Issue by fwhcat** [e107inc/e107#2933]
11 days ago, with the commit https://github.com/e107inc/e107/commit/ff2b79145ec6030406070e9cd8b0ef09fc366260
you introduced a bug.

Calling $output .= $this->thumbnailSelector('sitetheme', $opts, DEFAULT_INSTALL_THEME); is a great idea, but in $opts array, preview are the templates folder and not their preview image,
the thumbnailSelector checks if the preview field is a file and in that case, it fails.

OS: ArchLinux
PHP: 7.2
MariaDB: 10.1.29

**Comment by fwhcat** [comment]
Here is an attached screenshot:

![image](https://user-images.githubusercontent.com/20411249/34355465-c49ed270-ea35-11e7-9573-d6bef73359ba.png)

**Comment by Jimmi08** [comment]
Installation on php 5.6 without problems.

**Comment by tgtje** [comment]
Although local (php 7.1.1) no issues (1,5 days ago)

**Comment by CaMer0n** [comment]
@fwhcat Please test again with install.php?debug as your URL so that you can see the errors. 

    'preview'   =>  e_THEME.$val."/".$themeInfo['thumbnail'],

My guess is that the XML is not being parsed correctly.

**Comment by fwhcat** [comment]
No errors displays. The following is the array displayed via ?debug
```
Array
(
    [language] => English
    [mysql] => Array
        (
            [createdb] => 1
            [server] => localhost
            [user] => root
            [password] => test
            [db] => e107
            [prefix] => e107_
            [overwritedb] => 1
        )

    [paths] => Array
        (
            [hash] => 416f4602e3
        )

    [admin] => Array
        (
            [user] => root
            [display] => root
            [email] => root@localhost
            [password] => test
        )

    [prefs] => Array
        (
            [admincss] => css/bootstrap-dark.min.css
            [sitename] => test
            [sitetheme] => 
        )

    [generate_content] => 1
    [install_plugins] => 1
)
```

My web server outputs a notice, might be related:
```
[Tue Dec 26 19:12:53 2017] PHP Notice:  Undefined index: @value in /home/fabien/Dev/e107/e107_handlers/theme_handler.php on line 626
[Tue Dec 26 19:12:53 2017] PHP Stack trace:
[Tue Dec 26 19:12:53 2017] PHP   1. {main}() /home/fabien/Dev/e107/install.php:0
[Tue Dec 26 19:12:53 2017] PHP   2. e_install->renderPage() /home/fabien/Dev/e107/install.php:206
[Tue Dec 26 19:12:53 2017] PHP   3. e_install->stage_6() /home/fabien/Dev/e107/install.php:375
[Tue Dec 26 19:12:53 2017] PHP   4. e_install->get_theme_xml() /home/fabien/Dev/e107/install.php:1192
[Tue Dec 26 19:12:53 2017] PHP   5. e107::getTheme() /home/fabien/Dev/e107/install.php:1896
[Tue Dec 26 19:12:53 2017] PHP   6. e107::getSingleton() /home/fabien/Dev/e107/e107_handlers/e107_class.php:1517
[Tue Dec 26 19:12:53 2017] PHP   7. e_theme->__construct() /home/fabien/Dev/e107/e107_handlers/e107_class.php:930
[Tue Dec 26 19:12:53 2017] PHP   8. e_theme->load() /home/fabien/Dev/e107/e107_handlers/theme_handler.php:75
[Tue Dec 26 19:12:53 2017] PHP   9. e_theme::getThemeInfo() /home/fabien/Dev/e107/e107_handlers/theme_handler.php:239
[Tue Dec 26 19:12:53 2017] PHP  10. e_theme::parse_theme_xml() /home/fabien/Dev/e107/e107_handlers/theme_handler.php:429
```

**Comment by CaMer0n** [comment]
@fwhcat Please list all theme folders in your e107_theme folder. 
Tested here with PHP 7.1.1 without any problem.

**Comment by fwhcat** [comment]
@CaMer0n it's a pure and fresh copy of master, nothing more.

**Comment by Moc** [comment]
Maybe there's a change in PHP 7.1.x vs. 7.2 which causes this issue.

**Comment by tgtje** [comment]
Just did an install on php **7.2** 
( PHP Version	7.2.0	 
MySQL	10.1.29-MariaDB (PDO) XML extension	Installed	EXIF extension	Installed	Curl Library	Installed	 GD Library	Installed	MB String Library	Installed

Confirmed; same output as @fwhcat (by image ) 
further testing : 

Only to be seen in php **_7.2_** (_2.1.6. git (aug) + today (2.1.8_):
 Notice: Undefined index: @value in local\htdocs\test\e107_handlers\theme_handler.php on line 626
Notice: Undefined index: @attributes in local\htdocs\test\e107_handlers\xml_class.php on line 568
Warning: explode() expects parameter 2 to be string, array given in local\htdocs\test\e107_handlers\theme_handler.php on line 778
Warning: Invalid argument supplied for foreach() in local\htdocs\test\e107_handlers\theme_handler.php on line 780
Notice: Array to string conversion in local\htdocs\test\e107_handlers\theme_handler.php on line 617
Notice: Undefined index: @value in local\htdocs\test\e107_handlers\theme_handler.php on line 626
hope an idea arises..

**Comment by tgtje** [comment]
Had a new test with **php 7.2**.. The above commit  3019 (still as request works for displaying thumb previews..
Install went fine there after, but helas : NO top bar links and debugging gave some results (?)
admin shortcodes >invalid argument _admin_shortcodes php_ line 2124  `foreach($slinks->eLinkList['head_menu'] as $k=>$lk)` 
This results that NO sitelinks are in dbase/system eg does not know what index php is as 'frontpage".
When adding them manually : yes the top nav gets populated (blank page (no wm stored?).
Next (but i do believe that is mariadb issue : ( Incorrect definition of table mysql.column_stats: expected column 'max_value' at position 4 to have type varbinary(255), found type varchar(255)).
So install ok (if also installed commit https://github.com/e107inc/e107/pull/3022)  eg #3021 
When installed and commit 3022 NOT used) the database (core as example) Has overall no numbers ( 0,1 etc...) but everywhere NULL as value.. (after commit all is where was NULL > 0 )
Sitelinks issue thus remains

next is invalid argument (2) in _theme_handler line_ 777 and 779 _(i did change it to this  `	foreach ((array)$tmp as $cat)`  (notice double ( (   ) and warning dispappears_ but 777 one stays.
Since i do not know what to change here, i went through. (got working site, but some issues, described above)
Hope it helps pinpointing...

**Comment by Deltik** [comment]
@tgtje: Can you create a new issue for what you're experiencing?  It would be best to have steps to reproduce the issue, what you're expecting to see, and what you're actually seeing.

**Comment by tgtje** [comment]
@Deltik Sure, will do (php 7.2) unaltered xamppp (yes only local since live not having 7.2)
might take some time though... but than again 7.2 is in early stage.. 
) ...maybe live video capture during installment.. I will submit when results.
