### ISSUE TITLE
Feature Box: Can't chose custom category/item templates

### ISSUE THREAD

**Issue by veskoto** [e107inc/e107#2952]
After updating to 2.1.7 when create/edit feature box category/item I can chose only core templates, even I have custom on **/my_theme/templates/featurebox/**
Check it with landingzero theme - same

**Comment by Jimmi08** [comment]
I confirm this issue.  This list ignores theme template array. Field type "layouts" and it uses getLayouts();

![image](https://user-images.githubusercontent.com/5429548/34603435-3943c7cc-f204-11e7-8165-c742cdb6e74c.png)

**Comment by Jimmi08** [comment]
This change fixed this:

![image](https://user-images.githubusercontent.com/5429548/34604821-7de3b3a6-f209-11e7-8a43-ad030f3204b1.png)

This commit:  https://github.com/e107inc/e107/commit/229f0486aa13fc1f6d6f5350c45ad9fb5930cd1b#diff-b881850f371cf4bdd14ebacd7cfa564c

**Comment by veskoto** [comment]
**e107_plugins/featurebox/admin_config.php** 
`'fb_category_template' 	=> array('title'=> FBLAN_30,	        'type' => 'layouts',	'inline'=>true, 	'data' => 'str', 	'width' => 'auto', 'thclass' => 'left', 'writeParms' => 'plugin=featurebox&id=featurebox_category&merge=1', 'filter' => true),`
to:
`'fb_category_template' 	=> array('title'=> FBLAN_30,	        'type' => 'layouts',	'inline'=>true, 	'data' => 'str', 	'width' => 'auto', 'thclass' => 'left', 'writeParms' => 'plugin=featurebox&id=featurebox_category&merge=0', 'filter' => true),`
**merge=0**

**Comment by Jimmi08** [comment]
This is perferct. This way it includes only theme templates. 
![image](https://user-images.githubusercontent.com/5429548/34605708-e2a8a5dc-f20c-11e7-8242-64e89f95b7ab.png)

@CaMer0n  With solving this issue could you consider set it as merge = 0?
If theme doesn't have featurebox templates, plugin templates are displayed.
If theme has FB templates, you normally copy plugin file in theme folder and then you let there what you want in theme.    
Or set this in FB plugin preferencies (better maybe because existing themes)

**Comment by CaMer0n** [comment]
@Jimmi08 Please try with my changes. merge is currently set to true by default. But we can change it if you guys think it's better to be false by default.

**Comment by Jimmi08** [comment]
this works for feature box category
