### ISSUE TITLE
Issue: Menu Manager/Old Theme

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3068]
Having an issue where Menu Manager no longer works on https://clancoyote.com website.

Admin Area > Menu Manager
![capture](https://user-images.githubusercontent.com/5818022/37131816-f59b3880-224f-11e8-9dd4-6cb257f97c0b.JPG)

I check a menu I want to add, click the Go button but that doesn't work - This is a v1 theme that did get a little update to work with e107 v2 (used bootstrap 3 files and tweaks) - this used to work, but recent github update, now it wont function.

On another site, with another theme, it works.

**Comment by tgtje** [comment]
Just informational (seems identical to a thing i ran into) try uninstalling plugins 1 at a time (the older ones), can be that some menu php file interferes (on layout).. ps e_shortcode anteup throws warning there.. ( line 148 or 184

**Comment by LaocheXe** [comment]
Tried that, no go

**Comment by tgtje** [comment]
For what it is worth.. can not really see what is going on.. take alook (it are notices, but might give some clue: (spec. menu class)
Notice Undefined variable: expand_autohide, Line 341 of /home/clancoy1/public_html/main/e107_themes/cytn/theme.php
Notice Undefined index: menu_title, Line 646 of /home/xxx/public_html/main/e107_handlers/menu_class.php
Notice Undefined index: menu_text, Line 668 of /home/xxx/public_html/main/e107_handlers/menu_class.php
Notice Undefined index: menu_name, Line 669 of /home/xxx/public_html/main/e107_handlers/menu_class.php
Notice Undefined variable: expand_autohide, Line 341 of /home/xxx/public_html/main/e107_themes/cytn/theme.php
if you got FF and debugger use  notices....

**Comment by Moc** [comment]
Did you check the browser debug console for any javascript related errors?

**Comment by CaMer0n** [comment]
@LaocheXe  I would need your theme files in order to test. You can send thru gitter if you wish.

**Comment by LaocheXe** [comment]
https://github.com/LaocheXe/CYT-Theme

**Comment by tgtje** [comment]
Info: did test it, same outcome as issue..Cause ???  So definitely in theme but ....?

**Comment by CaMer0n** [comment]
The buttons are there, just hidden. Not sure why yet.

**Comment by CaMer0n** [comment]
@LaocheXe Is this still an issue?

**Comment by LaocheXe** [comment]
Yes, still an issue - that website (clancoyote.com) uses PHP Version 5.6.40.

**Comment by Jimmi08** [comment]
The reason for this 

class for displaying available layouts has value LegacyDefault

but layout name is Default

![image](https://user-images.githubusercontent.com/5429548/108588340-f0406380-7358-11eb-9209-53f48dd8d43b.png)

If you manually change this to default, it will work 

![image](https://user-images.githubusercontent.com/5429548/108588366-136b1300-7359-11eb-9a30-163def036cdc.png)

@Moc it is a bug

**Comment by CaMer0n** [comment]
@LaocheXe @Jimmi08  

The 'bug' is in the theme itself. The layout specified in theme.xml does not correspond correctly with theme.php. 
It looks like a quick theme  'upgrade' to add a **theme.xml** file that wasn't done correctly, however, if this was not created manually, but automatically by the theme manager tool, please create a separate issue, because this would indeed be a core bug. 

#### The problem: theme.xml specifies a layout named 'default' which doesn't actually exist in theme.php. 

To match **theme.php** with the the **'default'** layout specified in theme.xml:

 `$HEADER` should have been renamed to `$HEADER['default']` 
`$FOOTER` should have been renamed to `$FOOTER['default']` 

(or, `$HEADER` and `$FOOTER` combined into one, separated by `{---}` and renamed to `$LAYOUT['default']` ) 

After these changes the theme manager behaves correctly: 

![Screen Shot 2021-02-20 at 07 51 24](https://user-images.githubusercontent.com/2825679/108601237-83c16680-7350-11eb-9d16-5463a24bbd67.png)

btw. In its current state this theme will fail under PHP8.

**Comment by CaMer0n** [comment]
I added an alert for when this occurs.
