### ISSUE TITLE
Members can not reply to their private messages

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3102]
Hi guys!

So, on my site, the members can not reply to their private messages, they can only send a new message. When they click on the reply button, they receive an error message (LAN_PM_114): "You do not have access to send to this user"

Is this a plugin setting error or a bug?

**Comment by KiraTheUltimate** [comment]
On the advanced tab:

1: Allow sending to all members: Admin

**Comment by tgtje** [comment]
is a limit set on pm ? I can not replicate this issue.
And informational : do you see a listing of send and received in pm settings?

**Comment by KiraTheUltimate** [comment]
There is no limit. And I can see this list...

**Comment by tgtje** [comment]
Ok, but are there replies to be seen? (those what would be have made, but not delivered?

**Comment by tgtje** [comment]
Still strange, but please read this issue post (all to the way down) iff you find similarities.. #2635

**Comment by net1313** [comment]
I comfirm. You can send a massage from Admin area, but not from frontent.
Got "You do not have access to send to this user" - but i'm a MAIN ADMIN

**Comment by SimSync** [comment]
The problem here is, that the sender must be in the same userclass as the receiver, if the receiver is in a userclass that is set as VIP class in the PM prefs. This restriction seems also to be valid for main admins.
The questions is: Is a bug or a feature ...?

see:
![grafik](https://user-images.githubusercontent.com/7572616/42033243-88e931d4-7adc-11e8-9481-b353831d4069.png)

**Comment by KiraTheUltimate** [comment]
If I set up the VIP class to "no one", then the problem is terminated. Thx!

**Comment by SimSync** [comment]
@KiraTheUltimate Please close this issue.
