### ISSUE TITLE
Download / Upload  categories problem

### ISSUE THREAD

**Issue by chimcen** [e107inc/e107#3152]
Hi,

on my website (latest e107git, php5.6) i've a problem with importing uploaded files from users.
Uploading the file works without any problems.
After then i switch to the admin area -> public uploads, edit the new file and turn the switch from "pending" to "accept"

![image](https://user-images.githubusercontent.com/22658487/40714928-39b1f478-6404-11e8-8e91-31cda7c54c55.png)

After hitting "update" i got the following error:

![image](https://user-images.githubusercontent.com/22658487/40714972-64f329ea-6404-11e8-81de-016757945304.png)

Because of that, i setup a new fresh install of latest e107git (php5.6) on another server, created a ne categorie

![image](https://user-images.githubusercontent.com/22658487/40715043-9f999da4-6404-11e8-8ddf-0ba91af3e013.png)

and tried to upload a file - but in upload.php i don't see my new created categorie:

![image](https://user-images.githubusercontent.com/22658487/40715100-cdd61904-6404-11e8-8862-3eeb9fdb5fa2.png)

Anyone got the same problems?

**Comment by SimSync** [comment]
@chimcen The empty category dropdown is because you need to check your categories.
Only categories, that have at least 1 subcategory assigned will be displayed here.

1. create a main category e.g. "General"
2. create a subcategory (e.g. "Stuff") and assign the main category "General" as parent.
3. The category "Stuff" fill now be display properly in the dropdown.

I've also submitted a fix for another issue that belongs to your issue. But Cameron still has to merge it in the master branch.

**Comment by chimcen** [comment]
Now the upload (and the activation of it) works - but i get this error:
![image](https://user-images.githubusercontent.com/22658487/40906323-c6267818-67e0-11e8-991d-0643e0e968ba.png)


Another question is - why i'm only able to see/choos from one subcategorie of my parent categories when uploading files instead of all?
