### ISSUE TITLE
Error in upload.php page

### ISSUE THREAD

**Issue by iscf2019** [e107inc/e107#3182]
I have an error in upload.php load. after I set category and subcategory in the admin page this occur in load page! 
Warning: require_once(../class2.php): failed to open stream: No such file or directory in /home/iscfcom/public_html/upload.php on line 13

Fatal error: require_once(): Failed opening required '../class2.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/iscfcom/public_html/upload.php on line 13
so I replace new upload.php file in e107_admin in my host and this error was occur after load upload page
Oops! 
Error 404 - Document Not Found

**Comment by CaMer0n** [comment]
@iscf2019 Thank you. Are you using the latest version from Github?

Here's what the page looks like to me: 

![image](https://user-images.githubusercontent.com/2825679/41301176-568aca12-6e1c-11e8-8e21-29650192856b.png)

Could you send a screenshot and share the URL are using to access the page?

Thank you

**Comment by iscf2019** [comment]
Hi
Yes, I used the last version of e107, but after I active upload in preference page and set category and subcategory in the download page, I upload a file for test system and the file was uploaded successfully but have an error for the active file for downloading, after this, the errors have been shown in my website
https//iscf2019.com/upload.php
and I haven't  access to the page that you requested of me 
![image](https://user-images.githubusercontent.com/39799521/41333442-126a7d38-6ef7-11e8-88da-8355c2ba7965.png)
![image](https://user-images.githubusercontent.com/39799521/41333577-91c7444e-6ef7-11e8-8375-ea1c4deb0953.png)
![image](https://user-images.githubusercontent.com/39799521/41333615-b101ade0-6ef7-11e8-99a4-7767d20c459e.png)
![image](https://user-images.githubusercontent.com/39799521/41333667-e0390126-6ef7-11e8-9387-474c2ee03041.png)
![image](https://user-images.githubusercontent.com/39799521/41333687-f1a76b28-6ef7-11e8-9ff3-35653fee778c.png)

**Comment by iscf2019** [comment]
so what can I do to correct this issue?

**Comment by Moc** [comment]
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download' button at the top of this page: https://github.com/e107inc/e107
