### ISSUE TITLE
Image Not found

### ISSUE THREAD

**Issue by tyupika93** [e107inc/e107#3275]
When you click an image by typing the file not found for each download, this is a problem

![notfound](https://user-images.githubusercontent.com/35248010/42660349-28c58cda-862b-11e8-86a5-696cead7bd2f.png)

**Comment by Jimmi08** [comment]
Just additional info:  It works with download plugin using SEF-URLs (latest github), tested on my site.  So maybe this is related to legacy urls.

**Comment by SimSync** [comment]
@Jimmi08 So you did understand what he wrote about? Great! Could you explain it to me?

**Comment by tyupika93** [comment]
No SEF URL set up nowhere

**Comment by tyupika93** [comment]
I deleted a safe url and wrote this when updating 

Hiba 42S22: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'can_url' in 'field list'

**Comment by tyupika93** [comment]
This is picture php code download.php

$image = ($table == "upload" ? $upload_ss : $download_image);

if (strpos($image, "http") !== FALSE) 
{
	e107::redirect($image);
	exit();
} 
else 
{
	if ($table == "download") 
	{
		require_once(HEADERF);
         $imagecaption = ''; // TODO ?name or text Screenshot

		if (file_exists(e_FILE."download/{$image}")) 
		{
			$disp = "<div style='text-align:center'><img class='img-responsive img-fluid' src='".e_FILE_ABS."download/{$image}' alt='' /></div>";
		}
		else if(file_exists(e_FILE."downloadimages/{$image}")) 
		{
			$disp = "<div style='text-align:center'><img class='img-responsive img-fluid' src='".e_FILE_ABS."downloadimages/{$image}' alt='' /></div>";
		} 
		else 
		{
             $image = $tp->replaceConstants($image,'abs');
			$disp = "<div style='text-align:center'><img class='img-responsive img-fluid' src='".$image."' alt='' /></div>";
		}

		$disp .= "<br /><div style='text-align:center'><a href='javascript:history.back(1)'>".LAN_BACK."</a></div>";

		$ns->tablerender($imagecaption, $disp);

		require_once(FOOTERF);
	} else 
	{
		if (is_file(e_UPLOAD.$image)) 
		{
			echo "<img src='".e_FILE_ABS."downloadimages/{$image}' alt='' />";
		} 
		elseif(is_file(e_FILE."downloadimages/{$image}")) 
		{
			echo "<img src='".e_FILE_ABS."downloadimages/{$image}' alt='' />";
		} 
		else 
		{
			require_once(HEADERF);
			$ns->tablerender(LAN_ERROR, "<div style='text-align:center'>".LAN_FILE_NOT_FOUND."<br /><br /><a href='javascript:history.back(1)'>".LAN_BACK."</a></div>");
			require_once(FOOTERF);
			exit;
		}
		exit();
	}
}

**Comment by Jimmi08** [comment]
@SimSync yes, and because I am active user of this plugin, I tried to check this.

@tyupika93 SEF-URL is core system of rewritting urls adresses,  there was nothing wrong from your side, you are using just non SEF-URL system, called for simplicity Legacy urls 
I just tried to narrow problem for solvers.

BUT - when I see in your message field "can_url"  - what plugin do you use?  How you could delete SEF-URL? 

@SimSync  For you
He is talking about preview image in download plugin view.  There are 2 fields thumb and images, just image is now used with some exception.  
When you click on link, big image detail should be appear.

![image](https://user-images.githubusercontent.com/5429548/42686247-93c41816-8695-11e8-851f-4988448a9e27.png)

My url is:
`<td><a href="/download/image/21/jm-canonical-plugin-1-3-0">Click here for screenshot</a></td>`

and it opens image in separate page:
![image](https://user-images.githubusercontent.com/5429548/42686321-cd0dac54-8695-11e8-8306-2c6b53d18cb7.png)

his url is:
![image](https://user-images.githubusercontent.com/5429548/42686425-2de059d2-8696-11e8-888f-4a06d57af543.png)

`<a href="/Kiegeszitok/download/request.php?download_=">Képernyőkép megtekintése</a>`

@tyupika93 could you post you download detail in admin? What is your SEF-URL for ID = 7?

**Comment by Jimmi08** [comment]
@SimSync when you check this, you could close this one too:  https://github.com/e107inc/e107/issues/1027

**Comment by Jimmi08** [comment]
@tyupika93 check if your theme doesn't have special template for download plugin and if it has, check if there is used this shortcode:  `<td class='forumheader3'>{DOWNLOAD_VIEW_IMAGE}</td> `  
Just to be sure that this is not theme related.
