### ISSUE TITLE
Rank images problem

### ISSUE THREAD

**Issue by tyupika93** [e107inc/e107#3285]
Something does not appear in the user's profile for rank images
![adminrtank](https://user-images.githubusercontent.com/35248010/42733287-17787838-882f-11e8-9273-be51c746bfe9.png)
![rank_user](https://user-images.githubusercontent.com/35248010/42733270-bfd3a828-882e-11e8-82df-0efc3b968757.png)

**Comment by KiraTheUltimate** [comment]
I confirm this... the rank images doesn't appears on my site too.

**Comment by SimSync** [comment]
The first image shows the admin area and it shows no image, because this field is inline edit enabled.
This can be changed to show the image, but to modify, you will than have to edit the whole item. @CaMer0n What do you think, show image or inline edit?

The user profile is empty because of an issue. This can be fixed once the first question is decided.

**Comment by tyupika93** [comment]
The admin panel now displays a rank, but no profile yet. :(

**Comment by SimSync** [comment]
Custom template for the profile page? Or custom theme shortcode, that overwrites the build in shortcode?
On my standard bootstrap3 it looks like this:
![grafik](https://user-images.githubusercontent.com/7572616/43033859-193c6e0c-8cd2-11e8-847a-b63a5a5d12e8.png)

**Comment by tyupika93** [comment]
![screenshot_20180721-112721](https://user-images.githubusercontent.com/35248010/43034276-f1a93afc-8cd9-11e8-8680-aa1768081dc6.png)
Not custom user template. :(

**Comment by tyupika93** [comment]
Thank you very much. Now it's good
