### ISSUE TITLE
SEF URL automatically turn on

### ISSUE THREAD

**Issue by tyupika93** [e107inc/e107#3324]
After installing the plug-in or after plug-in removal, a SEF url automatically turn on

**Comment by CaMer0n** [comment]
@tyupika93 Thank you. Could you please explain in a little more detail what the result is, and what is the expected result?

**Comment by tyupika93** [comment]
When I install an add-in or remove one, the database is updated. And then all the sefurl will automatically turn on

**Comment by tyupika93** [comment]
Can I ask you to fix this problem? You must turn off the sef url function 10 times a day

**Comment by Moc** [comment]
You're the only one reporting this specific issue so far. What's your PHP version? Also, are you installing fore plugins or third party plugins? Does it happen for both?

**Comment by tyupika93** [comment]
no plug-ins other than factory accessories are installed and PHP Version 7.1.3

**Comment by tyupika93** [comment]
This my problem. Video issue :) 
[](https://vimeo.com/303869350)

**Comment by Jimmi08** [comment]
I found the reason. 
After any install/uninstallation of any plugin, all core prefs are set as new (refreshed)

```
		foreach ($this->plugin_addons as $var) // clear all existing prefs.
		{
			$core->update($var.'_list', "");
		}
```
		
Prefs responsible for this settings is e_url_list, so it's refreshed too. 

It's correct for other "_prefs"  because there are just list of plugins using that addon, so it should be refreshed.
```
  'e_sql_list' => 
  array (
    'banner' => 'banner_sql',
    'chatbox_menu' => 'chatbox_sql',
    'featurebox' => 'featurebox_sql',
    'forum' => 'forum_sql',
    'gsitemap' => 'gsitemap_sql',
    'rss_menu' => 'rss_sql',
  ),
```
but with e_url_list there is user input (site settings)  = value can be changed by user

```
  'e_url_list' => 
  array (
    'contact' => 0,
    'forum' => 0,
    'gallery' => 0,
    'gsitemap' => 'gsitemap',
    'news' => 'news',
    'rss_menu' => 'rss_menu',
  ),
```

and it's refreshed again and again (in fact it's list of plugins using e_url addon)
```
  'e_url_list' => 
  array (
    'contact' => 'contact',
    'forum' => 'forum',
    'gsitemap' => 'gsitemap',
    'news' => 'news',
    'rss_menu' => 'rss_menu',
  ),
```
It should be refreshed, because you can install or unistall plugin with e_url.php used, but user settings shouldn't be ignored.

**Comment by CaMer0n** [comment]
@Jimmi08 Thanks. This was helpful.

**Comment by Moc** [comment]
@tyupika93 Please update with the latest files from Github and let us know if the issue is fixed for you.
