### ISSUE TITLE
Doesn't show images of the download categories

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3362]
Hi!

Since I've upgraded to v.2.1.8 the system doesn't show images of the download categories.

-> https://starwarsmedia.hu/download/

**Comment by tgtje** [comment]
No solution, only comment : take a look at the image size created/used 
taken out of source of page : `<img class='e-banner img-responsive img-fluid' src='/thumb.php?src=e_MEDIA_IMAGE%2F2018-01%2F728x79_szukitshu_banner_001.jpg&amp;aw=730&amp;ah=80' alt="728x79_szukitshu_banner_001.jpg" srcset="/thumb.php?src=e_MEDIA_IMAGE%2F2018-01%2F728x79_szukitshu_banner_001.jpg&amp;aw=1460&amp;ah=160 1460w" width="730" height="80"  /></a>`

**Comment by CaMer0n** [comment]
@KiraTheUltimate Did you try clearing the thumbnail cache?

**Comment by KiraTheUltimate** [comment]
@CaMer0n Yes, I tried and didn't solve the problem.

**Comment by tgtje** [comment]
Then it is size vs table width : here are 2 screens from FF see img 2 where i changed column width to 70% and what happens to the images..
![scr1](https://user-images.githubusercontent.com/1811857/43971936-1ace3870-9cd3-11e8-8017-fd367999b89a.jpg)
img 2 : 
![scr2](https://user-images.githubusercontent.com/1811857/43971950-256e7286-9cd3-11e8-9bd6-393ed6284c7b.jpg)

**Comment by KiraTheUltimate** [comment]
@tgtje but I don't use a download template, so it's in the original.

**Comment by CaMer0n** [comment]
@KiraTheUltimate I see the images on your download page. Did you change something?

**Comment by tgtje** [comment]
As @CaMer0n mentioned, the images are a little bit larger now..
Since i can do no more investigation, i just mention it (not a css/code user in this)so as question to readers :  
Does the 'img class > icon represent a certain image size by h, and w ? 

The bottom of the images is likely 'cut off just because of the thumb (see above first comment) the width was 730 px... that will never fit in that column (or cripples the next columns as it would kind of react responsive)..., the height is/was 80 px so cut ?
if you would reassign an image about 150px150px  (just for testing.... See how that works..

**Comment by KiraTheUltimate** [comment]
@tgtje  the images are covers (posters, like this: https://vignette.wikia.nocookie.net/starwars/images/a/a6/RebelsPoster.png/revision/latest?cb=20140805200015 ). When I upload earlier (in 2.1.7), the system automatically resized them (scale), and don't cut it.

@CaMer0n what do you see now?

I see this and this is wrong:

![01](https://user-images.githubusercontent.com/12445784/43983879-4966b606-9cfd-11e8-8c87-2b6f4b912889.JPG)

**Comment by KiraTheUltimate** [comment]
I put back the 2.1.7 version, and everything works well again.

https://starwarsmedia.hu/download/

**Comment by CaMer0n** [comment]
Download template was missing the appropriate `{SETIMAGE} `
