### ISSUE TITLE
Login page data is missing

### ISSUE THREAD

**Issue by BlastFM** [e107inc/e107#3419]
I'm having problems with the login page. I have seen several issues that arose in the past that seem to resemble my issue closely.

I would appreciate some help as I've been chasing this for hours now. https://blastfm.limited login page does not show any form data, it seems to appear and disapear very quickly on page load, as if it's disabled somewhere/somehow but I've checked the settings over and over and can't find the cause.

Login.php is also causing a Google page fault, the exact error is: Clickable elements too close together, (for mobile devices).

I have temporarily hidden the Members menu and am using a home page menu item login system instead.

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/issues/1870#issuecomment-418927839

**Comment by Moc** [comment]
@BlastFM Do you still require help with this?

**Comment by BlastFM** [comment]
I do still have the same problem on another site: https://blastfmmusicart.com/login.php

**Comment by BlastFM** [comment]
Ok, so after some more investigation.
			if (file_exists(THEME.'templates/login_template.php')) //v2.x path
			{
				require_once(THEME.'templates/login_template.php');
			}
			elseif (file_exists(THEME.'login_template.php'))
			{
				require_once(THEME.'login_template.php');
			}
			else
			{
				$LOGIN_TEMPLATE = e107::getCoreTemplate('login');
			}
in login.php redirects to the core login template because the other templates don't exist.
The core login template contains: {LOGO: login} which, if removed, solves the issue.
The problem therefore appears to be in the core login template file.

**Comment by Moc** [comment]
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download' button at the top of this page: https://github.com/e107inc/e107
