### ISSUE TITLE
language of admin area

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3485]
I noticed that help is in different language that rest of admin. 
 
![image](https://user-images.githubusercontent.com/5429548/46347118-b157c900-c64a-11e8-97b7-7e8d367c1241.png)

This is detail, but I am trying why something doesn't work  (banlist is blank page) and bad translation could be reason. And I am not able to switch fully to English.

Thanks.

**Comment by CaMer0n** [comment]
@Jimmi08 Please enable debug. What is the value of e_LANGUAGE ?

**Comment by Jimmi08** [comment]
![image](https://user-images.githubusercontent.com/5429548/46365270-6b195e80-c678-11e8-9c77-be6bf2412c0d.png)

**Comment by tgtje** [comment]
Just posting while reading... did you rename the languagedir ?  ( i do have >  ../e107_languages/) (did a quick check on 2 installs)

**Comment by Jimmi08** [comment]
> Just posting while reading... did you rename the languagedir ? ( i do have > ../e107_languages/) (did a quick check on 2 installs)

Yes, but it shouldn't be problem.  You can do it in config file.

**Comment by Jimmi08** [comment]
Great. Awesome job. Thank you. 
You confirmed that there is bug.  That switch is for User Frontend area.  
If it's not, then full admin area should change too.

**Comment by tgtje** [comment]
Did just thought about something, so i am not very sure it is a 'real' bug. (how strange it might seem).

Now suppose there are multiple admins/mods that can gain access to admin (and they are NOT (from example) Czech, but let's say Dutch. On MAIN entrance i do have the _user_language menu activated_, and this is IN use by the visitors. 
Now when that 'admin' uses fe Dutch as main, he/she will enter admin having that same circumstance, however the help section ('bug'?) displays the help in his/her native tongue..

So that makes it more complex.. As non-native it 'could/would' help me, but it is/looks strange.

**Comment by Moc** [comment]
Fixed with https://github.com/e107inc/e107/commit/254f56a449841016fabb0e60a35e2db295c04e6d
