### ISSUE TITLE
The relocation of the site and pictures.

### ISSUE THREAD

**Issue by Evgura** [e107inc/e107#3513]
Moved the site to another hosting and lost all the images in the news. On the main page, the pictures remained. What could be?

![default](https://user-images.githubusercontent.com/25720089/47333079-0bbcd600-d69b-11e8-8c09-c4113a08ac6d.png)

![default](https://user-images.githubusercontent.com/25720089/47335501-e3d27000-d6a4-11e8-858d-4543a210df19.png)

**Comment by Moc** [comment]
This is probably because the 'site hash' changed. This is the random string of letters/numbers combination, in which all files are stored. I need to check the code to see in which variables the hash is based, but I think it's related to the database name and/or table prefix. If these change, the hash will change. 

Check your e107_media folder for the correct hash (there will be two folders, one which actually still contains all the existing media files, and one new folder which is pratically empty). 

Copy the old hash and paste this in your e107_config.php file, and replace *** with the correct hash:

`$E107_CONFIG['site_path'] = '***';`

You may need to clear your caches afterwards. 

If that doesn't help, let us know. You might be experiencing the same issue as @Jimmi08 as described in https://github.com/e107inc/e107/issues/3412

**Comment by Evgura** [comment]
Yes, the hash has been changed. I copied the content from the old folder to the new one and it worked.

@Moc Thanks

**Comment by Moc** [comment]
That's another option as well haha 👍

**Comment by CaMer0n** [comment]
thumb.php wasn't checking the `$E107_CONFIG['site_path']` .  Commit https://github.com/e107inc/e107/commit/5073dcd3bb1884d6ea325886c499031a2fb41a4e should fix it.
