### ISSUE TITLE
avatar uploads

### ISSUE THREAD

**Issue by oui3kings** [e107inc/e107#3518]
This issue seems similar to previous avatar upload issues however this is occurring on a v2 site. Site is now 2.1.9, was 2.1.8(git) when issue was brought to my attention by a member. Updated, did not resolve. PHP 5.6.27, voux theme,  site has been up since Dec. 2016. Avatar uploads were functional before on this site. User prefs set to allow avatar upload. Avatar will say "click to change" when hovering but clicking will not allow upload dialogue box

**Comment by oui3kings** [comment]
![image](https://user-images.githubusercontent.com/2325228/47522474-acf68880-d863-11e8-9396-1db267bc37c9.png)

**Comment by oui3kings** [comment]
![image](https://user-images.githubusercontent.com/2325228/47582195-b8a88480-d921-11e8-8e51-e86ffc84dc0e.png)

**Comment by oui3kings** [comment]
I won't close this because I can't explain why there was a conflict. I was however to fix my issue/conflict by uninstalling the gallery plugin.

**Comment by Moc** [comment]
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download' button at the top of this page: https://github.com/e107inc/e107
