### ISSUE TITLE
Steam Login

### ISSUE THREAD

**Issue by SalomanKane** [e107inc/e107#3576]
Greetings,
ive got a small Problem with the steam Login. But from the beginning:

The Steam-Login seems to work fine BUT in the new created profile with the Steamlogin is no E-Mail Adress saved and the E-Mail Field canot be edited. So i cant use the Steam Profile.
The new Profile is only usable with deactivate the option  "Force user to update settings " but this is no solution. The Profile owner cannot edit his Profile because there is no E-Mail Adress. Everytime i enter a E-Mail Adress i must enter my Password but the Steampasswort is not correct for this. I dont see a way to complete the profile without a Adminaccount.

I hope someone can help. My Page is Using 2.1.9 and sorry for my bad english^^

**Comment by CaMer0n** [comment]
@LaocheXe Are you able to help @SalomanKane  ?

**Comment by LaocheXe** [comment]
Yes, Hello @SalomanKane and sorry for the late reply. I can share with you the settings I have been using on 501stlegion-a3.com website. I only  use Steam Login  - disallowed for creating accounts (Steam Login  does it  already).  In the admin area of the website go to Preferences  > User Registration/Login I have User  registration system set to Login Only,  New user verification method set to No Verification, User loigin method set to Username and Password. Next in Preferences > Signup Page Options: Field Options Email display, Password Hide (because steam login, no password required), Email Confirmation is set to display. The rest are set to hide.

I customized the login template and uploaded it to the theme templates folder - basically it shows the Steam Login button. For the admin account, I just go to website.com/e107_admin it comes up with it's own login that uses email/password.

Note: Username should not be changed with Steam Login. If you  try to  change it,  well it will say you need to enter a password, which blocks you from changing the username.

You can add an email address if you want, or edit you're display name, signature, etc... However, @CaMer0n once you enter you're email address,  save, edit   profile to change it (or  miss typed it, the  email section is locked (can't edit it no more unless admin deletes the email from admin area)).

**Comment by SalomanKane** [comment]
@LaocheXe 
Thanks for your reply. 
I have Changed the Settings and it worked :) but one problem still left. If i try to add a E-Mail Adress the Website ask for a Passwort. Is it normal?
