### ISSUE TITLE
Statistics has issues

### ISSUE THREAD

**Issue by aducom** [e107inc/e107#3583]
Under php 7.1 and 7.2 the statistics module has issues. I.e. referral stats generates an error under php 7.2 and a blank page under 7.1. See also: https://www.e107help.org/4455/requesting-statistics-about-referral-stats-generates-error

Not sure but search string stats does give a rendered form with no results where I would expect at least some.

Others seem to work well.

**Comment by Jimmi08** [comment]
@Deltik Thank you very much.
Is Fatal error related to php version?  Because I hadn't that problem.
Wouldn't be better to add default value null here:
`function simpleParse($template, $vars, $replaceUnset='')`
`$vars = null `
to avoid this error in future? I am just curious, nothing more.
Thanks again
