### ISSUE TITLE
Last sync github

### ISSUE THREAD

**Issue by yesszus** [e107inc/e107#3645]
Today update latest version with github sync after not loaded correct main admin area and database tools.

**Comment by mostym** [comment]
Have the same problem

![image](https://user-images.githubusercontent.com/25377269/51762210-f6818a00-2083-11e9-9458-69cfbdccd3a4.png)

**Comment by net1313** [comment]
it's a big disaster with a last update. Do developers make some tests on linux machine with updated branch? half of admin area shows nothing.

**Comment by Moc** [comment]
PHP versions please

**Comment by net1313** [comment]
PHP 7.1

**Comment by KiraTheUltimate** [comment]
PHP 5.6... and I tried all version...

**Comment by Moc** [comment]
Can you please enable debug mode and see if there is a PHP warning error?

**Comment by Moc** [comment]
@net1313 Several comments, because I am done with your snarky remarks here and on your own forums: 

- There is no professional development team. 'e107 Inc' is only setup so it is legal to accept donations (blame the American law system).  There are only voluntary contributors who spend their time developing aside from full-time or parttime jobs, families and so on. It's not a dedicated team working on this 24/7, and no one is getting paid. The development relies on the contributions of people who voluntary support e107 in any way (coding, support, documenting, writing plugins and themes, etc.). 

-  Tests are done more and more, including automated tests (https://github.com/e107inc/e107-test), ensuring higher quality of code development in order to improve. Is it all finished and perfect? No. But at least it is a step in the right direction. 

- There is no need for snarky remarks. If you feel like you want to improve e107, there are plenty of ways to contribute. If you feel like you can do everything better yourself, then please do so. You know how the github pull-request system works.

- No one said e107 is perfect. It can constantly be improved. If you feel like you have ways to improve it, we're open to all contributions and feedback (be it in a constructive manner). 

I appreciate all the feedback, but make it constructive. I don't appreciate the tone of your comments at all, even though it is valuable feedback. You are harassing valuable contributors of e107 publicly on your forum. People who are trying to help you. For FREE. At least you could show some respect and appreciation. 

So I am asking you to please change your attitude towards the volunteers and to start providing more *constructive* feedback. Thank you.

**Comment by CaMer0n** [comment]
Appears to be caused by a recent pull-request. 
@net1313 If you're not prepared to ride the errors, you should wait for the official releases which is when all the tests are made.

**Comment by net1313** [comment]
Ok guys, I'm taking back everything I said earlier. Who knew that you are so sensitive to criticism (even if I think it pushes for progress).
@Moc I really apologize for my snarky statements. My attitude changes. From today - only positive and constructive feedback!
