### ISSUE TITLE
Contactform sends with from field Admins e-mailadress

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#3667]
Hi All,
when someone uses the e107 contactform the entered mailadress is in the answer-to field, result is when you forward a message to another e-mailadress the answer-to field is gone and you cannot answer the sender anymore. The from mail adress is from the main admin.. Is that how it's supposed to be?

Please confirm.

Alex

**Comment by Moc** [comment]
You are right. How do you think this should be done instead?

**Comment by Alex-e107nl** [comment]
Yess you are right, use the from field, and use the subject for a message that its comming from the contactform of the website... something like that, is that possible?

Thx
Alex

**Comment by CaMer0n** [comment]
It's already using the 'reply-to' header.. normally that fixes this issue with replying.  

```
	$eml = array(
    	    'subject'       => $subject,
    	    'sender_name'   => $sender_name,
    	    'body'          => $body,
	    'replyto'       => $sender,
	    'replytonames'  => $sender_name,
	    'template'      => 'default'
	);
```
However, with forwarding, the only solution is to enable the viewing of full headers in your mail client before forwarding. This will also forward that 'reply-to' line.  
We can't change the "FROM" value to the person filling in the form, because the email would be detected as SPAM. (and possibly get your server blacklisted)

**Comment by Alex-e107nl** [comment]
Oke thx Cameron, did not know that was the reason, thx for your time!

Alex
