### ISSUE TITLE
Admin Area -> Edit News= Update button missing

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#3717]
So when editing a news post, the Update button is not visible, unless you hover your mouse over it, then it appears.

![annotation 2019-03-07 001925](https://user-images.githubusercontent.com/5818022/53936276-f2775d80-406e-11e9-89d0-46d38b52404e.jpg)

Weird behavior for sure. Notice after I updated the news, the button stays there until I clear my browse cache. Also notice, if I change browser tabs and switch back over, the button appears.

**Comment by Moc** [comment]
Which browser are you using?

**Comment by LaocheXe** [comment]
Mozilla  Firefox

**Comment by LaocheXe** [comment]
Notice this in all of admin area - all update buttons don't display unless you move your mouse over them - must be something new within Firefox screwing with CSS.

**Comment by Moc** [comment]
@CaMer0n Are you able to reproduce this?

**Comment by CaMer0n** [comment]
@Moc No, looks normal here. Using the latest firefox. @LaocheXe Try using a "New Private Window" in Firefox. Does it help?

**Comment by Moc** [comment]
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download' button at the top of this page: https://github.com/e107inc/e107
