### ISSUE TITLE
Missing menus, areas

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#3741]
hi!

After the latest update, the some menus are missing, the tinymce editor didn't load and the installed plugins are dissapeared (really didn't disappear, just invisible O.o). Sample:

![Képkivágás](https://user-images.githubusercontent.com/12445784/54783122-d81db200-4c20-11e9-98de-b9f8d4dbfcf0.JPG)

![2](https://user-images.githubusercontent.com/12445784/54783124-dbb13900-4c20-11e9-900d-9f51dee9116c.JPG)

![3](https://user-images.githubusercontent.com/12445784/54783132-df44c000-4c20-11e9-97af-cf2b0f97582f.JPG)

Before you ask, yes I clear the cache, and the browser cookies... :(

**Comment by Jimmi08** [comment]
Console log?  PHP version? The same if you switch admin to English?

**Comment by KiraTheUltimate** [comment]
Php-version: 5.6.36
Same problem when I using english language. :\

**Comment by KiraTheUltimate** [comment]
@Jimmi08 
The problem was that the system removed the installed plugins after the update, so I had to reinstall everything... now it's OK.

**Comment by Jimmi08** [comment]
@KiraTheUltimate thank you for letting me know. I use only PHP 7, nothing like this happened to me. On online sites, I haven't updated yet.

**Comment by Moc** [comment]
@KiraTheUltimate You said 

> The problem was that the system removed the installed plugins after the update,

Do you mean update to the latest Github files? Did you do this manually (downloading ZIP from github), via Git (ie.  you have a `.git` folder in your e107 install), or via the Admin Area > Tools > Database > Sync with Github option?

**Comment by KiraTheUltimate** [comment]
@Moc 
Yes, after the update with the latest Github files. I do this manually always (downloading zip and overwrite the files)

**Comment by LaocheXe** [comment]
I  can confirm it happen in PHP7 as well.

**Comment by Moc** [comment]
Please update to the latest files and let us know if the issue occurs again

**Comment by Jimmi08** [comment]
I can confirm it too now.  Something between 19.4.2019-20.5.2019 caused this. 
PHP 5.6 
some the old updated plugins used
core pref installed plugins list was correct 
all plugins with needed installation had set installed flag value as 0

**Comment by Moc** [comment]
@CaMer0n Perhaps related https://github.com/e107inc/e107/commit/cb02f705b69fcd566201aa12f83102803218a89e https://github.com/e107inc/e107/issues/3592

**Comment by Moc** [comment]
Copied from Gitter:

> @Moc plugin_installflag was set to 0 for all plugins with installation required. The mistake was to run Database/Rescan Plugins. I had to change this in database and run rescan again, because after install via admin it hit me that it could override plugin preferences if plugin use setup file. Db tables were safe, but I really don't know what will happen with plugin prefs. And because I had to set smartsuup prefs again, I am afraid with that new plugins way, they will be overridden. I am still not sure if everything is back correct way.

**Comment by CaMer0n** [comment]
@Jimmi08 Could you please list every plugin that you have installed, prior to the upgrade?

I just did a test upgrade from 2.1.9 to 2.2.0 without any such issue. 
So I'm thinking it could be related to a third-party plugin. 

Thanks.

**Comment by Jimmi08** [comment]
@CaMer0n I had 2.2.0 git, I am sure about it.
I just sync localhost copy and without a problem, but it's 7.2.  On live site, it's PHP 5.6 .

Now I have installed OLD ones:
Content Plugin
Links Page
New Forum Posts
Signup Secure
spoiler

Not available old plugins (I mean others shouldn't have them)
User Class Badges Plugin
Class Membership

Custom plugins (again others shouldn't have them)
JM Elements
JM Theme Options
JM Canonical
JM Content
JM Downloads
JM Google Ads
JM Shortcode
Theme Options
Yandex Turbo Pages
Yandex Metrica

New ones:
Smartsupp Live Chat
NoCaptcha ReCaptcha
Mentions
Nofollow
EU GDPR cookies

You can't export plugin table from Database/Tools/export, otherwise, I would export this.  
My last backup is from 20.4. when I am aware that I update the site. I was surprised today that my live site is running on 2.2.1 git.   

Ok, I could do this by mistake, but datestamp on files is 20.5, I would notice something like this yesterday or day before.  I am checking logs now.

**Comment by CaMer0n** [comment]
@KiraTheUltimate Could you please list all the plugins you use? Thanks.

**Comment by KiraTheUltimate** [comment]
Hi!
I using this plugins:

Banners
Cookie Consent (by Lóna Lore)
Downloads
Forum
Gallery
Google Analytics (by lonalore)
Google Site Map
Hits (by CaMer0n)
Linkwords
Statistics
Mentions (by Arun S. Sekher)
On This Day (by Father Barry)
Private Message
Social
Tags
TinyMce4
User
Youtube (by CaMer0n)

**Comment by CaMer0n** [comment]
Thank you @KiraTheUltimate . I'm not seeing any correlation between your plugins and those of @Jimmi08 . 

When issues like this arise, it's better to contact me via PM on Gitter before you attempt to fix it, as there is no guarantee that I will be able to reproduce the issue later in order to correct any issue in e107. 

I don't think we can do anything for this issue at the moment, until it can be reproduced.
