### ISSUE TITLE
displaying of metatags on areas that have their own metatags

### ISSUE THREAD

**Issue by net1313** [e107inc/e107#3765]
Definitely not good for SEO.
If you enter meta tags in admin prefs, it will display in header (pages, forum, ... etc)

That's the artifact of V1.
While the pages, news, forums have their own meta tags, why we should add these tags which will be invalidated by search engines?
I suggest to modify e107_admim/meta.php in order to place meta tags only in home page.

**Comment by Moc** [comment]
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download' button at the top of this page: https://github.com/e107inc/e107
