### ISSUE TITLE
SEF URL to custom page in comment_menu

### ISSUE THREAD

**Issue by Evgura** [e107inc/e107#3778]
In the comments menu links to pages have this form (for example) - site.ru/page.php?***
How to make SEF URL (for example) - site.ru/page/****/ ?

**Comment by Moc** [comment]
Mostly added, except for when using the URL configuration `/book-title/chapter-title/page-title' because I am still missing SEF values. 

@CaMer0n What is an easy way to retrieve those?

See[ e_search](https://github.com/e107inc/e107/blob/305f0816f804d9f41b258c8092403c2a8feec38f/e107_plugins/page/e_search.php#L105) in `e107_plugins/page` for example:
```php
		$book 			= $this->getParent($row['page_chapter']);
		$row['chapter_sef']   = $this->getSef($row['page_chapter']);
		$row['book_sef']	= $this->getSef($book); 
```

**Comment by CaMer0n** [comment]
@Moc That's correct. However, there was a lot of duplication. This has now been corrected with the introduction of the pageHelper class.
