### ISSUE TITLE
How to insert video to tinymce ?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3793]
I have self-hosted video.

I want to insert it to the news body/extended.  It's not displayed.  TinyMCE messed the code.

Neither using bbcodes f.e. in my forum without TinyMCE [video]

Only way is using html5 tag manually via editing forum post, but then the problem with new lines will start.

**Comment by tgtje** [comment]
Hey @Jimmi08 
The only way i can succeed is using the base url for movie from media manager 
ex :  {e_MEDIA_VIDEO}2019-05/destination_moon_1950_movie_trailer.mp4

Now what normally happens (normal?) it strips (plain post inside tinymce editor) the src tag.
So no path...
Now i go into CODE mode inside tinymce and paste the following:
`<video width="420" height="400" src="{e_MEDIA_VIDEO}2019-05/destination_moon_1950_movie_trailer.mp4" controlslist="nodownload" controls="controls">
  Your browser does not support the <code>video</code> element.
</video>
`
this will be known by you (w+h) but i use the extra 'control'function here to (sneaky) diable the download button.... (the 'play'bar is created by browser, but this way it will be hidden).
So inside code and use plain url.. the below ADD movie ; image etc.. has no effect.
example (voux papilion minter extended field). Yup it is not as how it is intended i guess..

![rocket](https://user-images.githubusercontent.com/1811857/57227222-1fb19f00-7011-11e9-840a-de7a619d21bd.jpg)

**Comment by Jimmi08** [comment]
I use this way in the forum with bb codes.  There has to be another way, this is basic functionality...   But thanks

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/issues/3781

**Comment by Jimmi08** [comment]
https://github.com/e107inc/e107/issues/3675

**Comment by Jimmi08** [comment]
Confirmed, that this is still the only way how to insert video to the TinyMCE area.

**Comment by Moc** [comment]
https://www.e107sk.com/forum/general-theme-questions/237/video-player-solved/?p=1#post-787

**Comment by tgtje** [comment]
The post on sk reflects the issue here..

In my opinion, it is something that is missing for tiny. In tiny 3 we had a media plugin, which does not appear anymore after 2013 first alpha for 2 as tinymce was pulled out of core, and became core plugin.
Not sure if at that timeframe  tinymce4 media was a paid part... 
Hven't tested it using and adapting tiny to use a newer media plugin, and changing wysiwig/mediamanager etc...
That is out of my league. I just experimented with different scenarios untill i found one, that did the job. It's a basic solution, but would even need more (alike auto browser switch if mp4 is not played> go to webm > or ogg/theora …..

**Comment by tgtje** [comment]
Tested 👍 
result using insert media with media manager file path : 
![movies](https://user-images.githubusercontent.com/1811857/81187484-6afbe600-8fb4-11ea-9760-0badf4b011df.jpg)

**Comment by CaMer0n** [comment]
Thank you @tgtje !
