### ISSUE TITLE
Social Plugin > HTTPS blocked content 

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/e107#3817]
Hi Team, 
I am getting blocked/unsafe warnings due to Social plugin.

Blocked loading mixed active content 
"http://xxx.yyy/e107_plugins/social/font/fontello.eot?25587411#iefix" 

Any idea how to use HTTPS instead? 

Thanks
Mikey

**Comment by tgtje** [comment]
Peaked into some cause... could be a) related to some caching by browsers OR (do not know jow exactly the identify of ssl/https runs... maybe a small change IN the font also could work.
That is a test method anyway, but it is a core plugin, so not sure if it will work and how to implement this iff any... Testing for you best since you have that issue..)
Get yourself an font editor (example is based on  birdfont = opensource) find  the setting that gives name and description(menu)...  ( you need to have a font loaded inside the program; the ones you need are eot AND ttf)  GO down > vendor.... it says http.... change this and to //  or https ....save..
Hope it helps  ( in case it does....fontello is commonly used...)

**Comment by Jimmi08** [comment]
Hm, I haven't this problem, it's loaded as a relative link:
`<link  rel="stylesheet" media="all" property="stylesheet" type="text/css" href="/e107_plugins/social/css/fontello.css?1559393465" />`
What is your site url?  Thanks

**Comment by MikeyGMT** [comment]
Hi @tgtje , @Jimmi08 ,
Looks like it is ok today. I agree caching issue. I think we can close.  
https://gangesfield.wales/ 
Mikey
