### ISSUE TITLE
TinyMce4 Unsuccessful YouTube code embedding 403 error

### ISSUE THREAD

**Issue by JoniPeti** [e107inc/e107#3872]
Hi!

I would have a problem (in the case of a website I run) that when I want to embed YouTube code, I get 403 error messages. I attach a picture to understand what it would be like.

I use the latest e107 version.

<img src="https://jonasportalstudio.hu/github/1.jpg">

<img src="https://jonasportalstudio.hu/github/2.jpg">

<img src="https://jonasportalstudio.hu/github/3.jpg">

**Comment by yesszus** [comment]
Did you enter the youtube api key?

**Comment by Moc** [comment]
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download' button at the top of this page: https://github.com/e107inc/e107
