### ISSUE TITLE
Chatbox does not display the user's nickname correctly

### ISSUE THREAD

**Issue by chory** [e107inc/e107#4162]
## Bug Description
Chatbox does not display the user's nickname correctly

## How to Reproduce
In chatbox menu, if the user contains "." in your nick, only the first string is displayed up to the "."

## Expected Behavior
Show the full nick

The content of line 64 needs to be changed, in the file e107_plugins/charbox_menu/chatbox_menu_shortcodes.php of
`$temp = explode ('.', $this->var['cb_nick']);`
to
`$temp = explode ('.', $this->var['cb_nick'], 2);`

**Comment by CaMer0n** [comment]
Thank you @chory for the fix.

**Comment by Moc** [comment]
I'm not sure how this was exactly but I remember there was an issue with usernames having a ".". Need to lookup the exact issue. 

I also remember that this fix was put there to split the userid from the username because for some reason, messages were stored in "id.username"  format. Not sure if that's still the case. 

Can't test now but will test asap

**Comment by Moc** [comment]
#2376 hmm, this was in forum only. Doesn't seem to be related to chatbox.

**Comment by chory** [comment]
> I also remember that this fix was put there to split the userid from the username because for some reason, messages were stored in "id.username" format. Not sure if that's still the case.

Correct, user names are stored in id.usename format, so as it was previously, if the user name contains any ".", Only the content was returned between the first and second point.

Now it works correctly.
Thank you very much for the work you do and the dedication...
