### ISSUE TITLE
TinyMCE formatting don't work in the admin area

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#4223]
## Bug Description
When I creating a news post or a page the TinyMCE editor don't work correctly. Some formatting options not display (like: bootstrap inline, blockquote, etc) in the editor area. After saving, the formatting what I set will be fine.

## Screenshots
![01](https://user-images.githubusercontent.com/12445784/88569444-baddcc80-d03a-11ea-815a-d6feef2aa5d6.jpg)

### e107 Version
Git.

### PHP Version
PHP 7.1.33

**Comment by tgtje** [comment]
Using provided language pack for hu, updated to very last version (git) just now.
No issues here, Mind : use/tested on php 7.3.5

**Comment by KiraTheUltimate** [comment]
@tgtje 
Trying Bootsrap Inline or Block, Bootstrap Blocks, etc... not just the regular formatting. It doesn't work for me. (yes, I updated the language files)
On php 7.3.5 the website showing "white page" and nothing to load. :S

**Comment by tgtje** [comment]
Wanted to take  a look at sw... 500 Internal Server Error page (by source) does not fully load.. Some points (diff browsers) to ssl, while other says ssl cert. ok Went back to 7.1.33 i saw.

So something internal is destroying your outcome..  I can gain some info, but very limited keeps giving 500 (source goes to line 65  
`

<div class="modal-footer">
--
  | <a href="#" data-dismiss="modal" class="btn btn-primary">Close</a>
divs..
`last entry.. theme corrupted?

**Comment by Jimmi08** [comment]
@KiraTheUltimate 
if you see this in F12 Console:
![image](https://user-images.githubusercontent.com/5429548/99152807-653e3600-26a4-11eb-9ed0-817d8442b1c7.png)


This is one of possible fix:
![image](https://user-images.githubusercontent.com/5429548/99152717-c1548a80-26a3-11eb-90be-6c953d3e0c37.png)

@tgtje 
bootstrap 3 is not loaded because there was probably a change in the e107_web folder 

I don't know what is correct fix, because I can see I had there folder 3.3.7/dist/ and now there is just  folder /3/

**Comment by CaMer0n** [comment]
@tgtje @KiraTheUltimate @Jimmi08  

Change made. Thank you.
