### ISSUE TITLE
Set default forum rights to admin only.

### ISSUE THREAD

**Issue by aducom** [e107inc/e107#4256]
## Motivation
If you or your moderator is creating a new forum then the standard rights are public. If you oversee this, then anyone can post on your website without logging on. In my case, it took about 2 hours to get porn links on my website.

## Proposed Solution
By setting the rights default to admin, this cannot happen. Security should be number one prio imho.

## Alternatives
n.a.

## Additional Context
n.a.

**Comment by CaMer0n** [comment]
@aducom Good suggestion. Thank you!

**Comment by Moc** [comment]
@CaMer0n I tried adjusting this. For example:

```
			'forum_postclass'           =>   array ( 'title' => FORLAN_205, 'type' => 'userclass', 'inline'=>true,'filter'=>true, 'batch'=>true, 'data' => 'int', 'width' => 'auto', 'help' => '', 'readParms' => array('classlist'=>'public,guest,nobody,member,admin,main,new,mods,classes'), 'writeParms' => array('classlist'=>'public,guest,nobody,member,admin,main,new,mods,classes', 'default'=>'253'), 'class' => 'center', 'thclass' => 'center',  ),
```
(I added ` 'default'=>'253'` to the writeParms) 

The following code in form_handler however makes it so that this default userclass is always selected, even though it is not the current value set in the database. This is because the current setting is "0" (e_UC_PUBLIC). 
```
		if(empty($value) && !empty($parms['default']) && $attributes['type'] !== 'dropdown') // Allow writeParms to set default value.
		{
			$value = $parms['default'];
		}
```

Would changing this check to include `&& $value !== "0"` be ok? Or would that break other things?

**Comment by Moc** [comment]
@CaMer0n What's your take on my suggested form_handler change? See above. Thanks!

**Comment by CaMer0n** [comment]
@Moc I added e_UC_MEMBER (integer 253) and it appears to be functioning normally. Perhaps the form handler had since been improved.
