### ISSUE TITLE
New forum posts plugin version

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/e107#4322]
Is this plugin still under development because its compatibility version is still stuck on 1.0

**Comment by realmontazeri** [comment]
![Screenshot](https://user-images.githubusercontent.com/10089685/103335652-da19d380-4a8a-11eb-85c3-6d7084b1615c.png)

**Comment by Moc** [comment]
This plugin is outdated and should be removed. For some reason you are not getting the message in the admin area where it lists those outdated files. 

The plugin is now integrated as a menu within the forum plugin: https://github.com/e107inc/e107/blob/master/e107_plugins/forum/newforumposts_menu.php

**Comment by realmontazeri** [comment]
Its directory need to get remove from repository (e107_plugins/newforumposts_main) because it is still exist online.

**Comment by Moc** [comment]
It's left there for backwards compatibility reasons. If you go into the admin area of the plugin, you'll get a warning message with an explanation.

**Comment by PH5HP** [comment]
Hi,

Maybe an idea to list plugins which will work under version 2 in a separate list instead of listing all in one list. I encountered more than once website problems while installing plugins which seems after installing not compatible with version 2. Only way to unlock my website was removing the plugin from the plugin table in the database and removing the plugin files from the plugin directory.

The problem is that some version 1 plugins seems to work fine and most of the version 1 plugins does not work and mess up the website. E107 is a great CMS but maybe the lack of popularity comes from a part of things like this.

Kind regards,
Henk - https://ph5hp.nl

**Comment by rica-carv** [comment]
This plugin initially it was a full page plugin, but when it was integrated in the forum plugin, it became a menu, and right now there's no chance to make it work as a page again...
