### ISSUE TITLE
problem with extended news afer update

### ISSUE THREAD

**Issue by MurglakB** [e107inc/e107#4345]
I have updated the e107 system for my site to the latest Git version and since then the extension part of the news can not be seen.

The "Extend" button is there:

![image](https://user-images.githubusercontent.com/77437136/104577295-9b267900-5659-11eb-803e-cc8bde9f7dbe.png)

But when you click on it, there is no extension:

![image](https://user-images.githubusercontent.com/77437136/104577335-a9749500-5659-11eb-88ec-51f2f76fc6ee.png)

**Comment by Jimmi08** [comment]
Source code of that button, please.   Theme name. too

**Comment by MurglakB** [comment]
the theme is a modified BS Magazine 02. the source code I don't know (to be honest I'm not really competent in this). here's the site: https://starwarsmedia.hu/hirek - there you can see the news and the problem.

**Comment by Jimmi08** [comment]
Thanks for the link, it helped. Your URL is correct, your button is correct. The problem is in your news detail. 

1. either in missing news_view_template.php and the code for the view is in new_template.php, and this is not supported anymore (just guess)
2. or {NEWS_BODY=extended} stopped to return content for wrong used template file  (just guess)
 
Quick fix:
- copy core news_view_template.php to your theme templates/news/news_view_template.php

Full fix:
- move $NEWS_TEMPLATE['view']['item']  (theme, not core) from news_template.php to  $NEWS_VIEW_TEMPLATE['view']['item']  in news_view_template.php
 
By the way, it is templated this way for years.

**Comment by CaMer0n** [comment]
@MurglakB Sounds like a bug. Don't change anything just yet.

**Comment by CaMer0n** [comment]
@MurglakB If you update, it should be fixed now.

**Comment by MurglakB** [comment]
great, thank you!
