### ISSUE TITLE
Separate pref in admin for Phone, Email, and Address

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#4372]
I think would be great a separate pref in admin for Phone, Email, and Address, and google map (Contact page). Now they are in the one textbox and only one shortcode for it. I can not style the details and I think this option is poor.

**Comment by CaMer0n** [comment]
@fizi This has been completed.  But pls let me know of any template changes you think would be useful. 

fyi @Jimmi08 @Moc

**Comment by CaMer0n** [comment]
![image](https://user-images.githubusercontent.com/2825679/107987454-e0a0d380-6f82-11eb-9624-4305c5a31106.png)

**Comment by Jimmi08** [comment]
Please, add this as a preference to admin display options to be able to hide those fields.  There are themes that used theme preferences for something like this.
 
At least get back the description field for the contact page, not replace it. There is no way after emptying this field to get it back.

This is just not the correct approach.  I want on contact page Working hours, I want different zoom or google maps by coordinates, not by address,  What now?  Will I have contact information on 2 places now? So give me an option to hide this. 
 
So now each theme should support those fields?  Because users can fill them now and they will ask why they are not displayed.

And if you added an email field, why it is not type email?

**Comment by CaMer0n** [comment]
@Jimmi08 It is up to themes to conform to e107's architecture, not the other way around. You would have done better to suggest this enhancement to the core ( like @fizi did) but sooner, rather than added non-theme-related data fields to your theme preferences. Theme preferences should be about layout/styling, not about storing user data/content for core pages like 'contact.php'. 

>  I want on contact page Working hours, I want different zoom or google maps by coordinates, not by address, 

Exactly, these are feature requests that should be directed to the e107 core here on github, not to theme developers to put into theme preferences.

**Comment by Jimmi08** [comment]
I asked for this with an Industrial theme. It was discussed on gitter. I had to create a Contact Page Extended plugin to have those fields and then I found that there was already a legacy plugin for this.  @rica-carv will maybe remember this discussion.

I don't mind your changes. I want the back description field for the contact page.  It is missing now.

**Comment by CaMer0n** [comment]
Yes, but a discussion != Feature-request created. 

Now, the field that was removed was create to hold company name, address, phone etc. together. 
This has now been replaced by separate fields. 

So, my question is: why do you need this generic contact field back when it is replaced by the new fields?

**Comment by Jimmi08** [comment]
Because you limited functionality of that field to just some listed fields!.   There can be a text field too f.e. adding some text information...  
What happens if somebody uses an old theme with this field and empties it?

And I don't talk only about theme prefs.  How I can now explain to the user that that information is in 2 places now? So this is the reason why I am asking for the option to hide them by admin display settings.

![image](https://user-images.githubusercontent.com/5429548/108084637-ba5b6080-7074-11eb-8470-698c19dc5763.png)

By the way, I don't agree that those fields should be in the core because they are intended for the corporate website.  No community site will need those fields.  

Where do you write f.e. some message now for users on contact page?

**Comment by CaMer0n** [comment]
> How I can now explain to the user that that information is in 2 places now?

You update your theme/plugin to disable those fields and you display a message to the user that they should insert their data into the core prefs pages. You also provide a link to take them to that area directly and you display their previously entered data.

**Comment by Jimmi08** [comment]
You can forget this. Nope.  There is an access issue too.  You should extend the contact plugin not to add this to core prefs for this.

If other users ask, I will point them to this issue.  I will wait until the other themes will be fixed.

**Comment by CaMer0n** [comment]
@Jimmi08 Please do. The "fixing" needs to occur in your themes. You used theme prefs for the wrong purpose. End of story.

**Comment by CaMer0n** [comment]
@fizi Here's a screenshot of the completed feature-request. 

![image](https://user-images.githubusercontent.com/2825679/108099306-46e82d80-7039-11eb-92c8-f3df795f0c9c.png)

**Comment by Jimmi08** [comment]
@CaMer0n  Where to put company ID and Company VAT number now?

**Comment by fizi** [comment]
Good work! Thanks!

**Comment by 2548ir** [comment]
Nothing were changed after upgrading to the latest version and it only appears on fresh install.

**Comment by CaMer0n** [comment]
@2548ir You need to delete your existing contact info and save, then the new prefs will appear.
