### ISSUE TITLE
How to select (selected) dropdown default value?

### ISSUE THREAD

**Issue by djbeater** [e107inc/e107#446]
my code looks like

```php
'noliktava' => array('title' => 'is in?', 'type' => 'dropdown', 'data' => 'boolean', 'readParms' => array(1 => 'Jā', 0 =>'Nē'), 'writeParms' => array(1 => 'Jā', 0 =>'Nē'),
```

## How to select default value 1 => 'Jā' ?

and also how to select boolean default value?

```php
'publiceta' => array('title' => 'sure?', 'type' => 'boolean', 'data' => 'boolean'),

**Comment by Moc** [comment]
I think this is determined by whatever default value is set in the SQL structure. For instance, if your SQL structure's default value for the 'noliktava' field is '1', this would be the option that is selected when viewing the settings for the first time. 

Let me know if this answers your question. I'm closing this since it's a very old one and no feedback has been given in the mean time.
