### ISSUE TITLE
Choosing between featurebox and hero plugin

### ISSUE THREAD

**Issue by 2548ir** [e107inc/e107#4463]
An option for business home layout to choose between featurebox and hero plugin as slider because featurebox is currently set as default.

**Comment by Jimmi08** [comment]
The correct fix is to replace {FEATUREBOX} hardcoded in this layout and then select featurebox or hero menu.

If you plan to solve this other way, I would like you to tell me ahead, because there are at least 2 other plugins using this area.

**Comment by realmontazeri** [comment]
@Jimmi08 sounds good!

**Comment by 2548ir** [comment]
@Jimmi08 are you finally done with this?

**Comment by Jimmi08** [comment]
@2548ir I have a problem with English, sorry. This is not waiting for me... if it is implemented, just let me know. I have no plans to use Hero plugin.

**Comment by 2548ir** [comment]
Go ahead! @Jimmi08 your English language is good, tell me what exactly are you talking about?

**Comment by 2548ir** [comment]
Go ahead! @Jimmi08 your English language is good, tell me what are you exactly talking about?

**Comment by 2548ir** [comment]
> The correct fix is to replace {FEATUREBOX} hardcoded in this layout and then select featurebox or hero menu.
> 
> If you plan to solve this other way, I would like you to tell me ahead, because there are at least 2 other plugins using this area.

Replace {FEATUREBOX} in home layout was the solution you have mentioned? if this is it, then it looks confusing about your second part: I would like you to tell me ahead!

**Comment by 2548ir** [comment]
> The correct fix is to replace {FEATUREBOX} hardcoded in this layout and then select featurebox or hero menu.
> 
> If you plan to solve this other way, I would like you to tell me ahead, because there are at least 2 other plugins using this area.

@Jimmi08 replacing {FEATUREBOX} in home layout was the solution you have mentioned? if this is it, then it looks confusing about your second part: I would like you to tell me ahead!

**Comment by 2548ir** [comment]
> The correct fix is to replace {FEATUREBOX} hardcoded in this layout and then select featurebox or hero menu.
> 
> If you plan to solve this other way, I would like you to tell me ahead, because there are at least 2 other plugins using this area.

@Jimmi08 replacing {FEATUREBOX} in home layout was the solution you have mentioned? if this is it, then it seems confusing about your second part: I would like you to tell me ahead!

**Comment by Jimmi08** [comment]
**Actual state (at least at that time):**
- hardcoded {FEATUREBOX} shortcode in home layout. To replace it with hero, you can either delete it and add menuarea and add the needed menu with the menu manager or use the hero shortcode instead of it.

**Your feature request** -  to select what to show in this area. (I don't mind) . In fact, the correct solution is to use some {MENU=xxx} and add featurebox_menu there, not hardcoded shortcode. 

If they would accept your FR, I needed to know this,  because there **were** at that time two next plugins for solving this type of content - masterhead plugin and JMelements plugins.   And my themes sometimes override {FEATUREBOX} shortcode in layout with theme shortcodes and insert needed shortcode according to the installed plugin.

Please, notice the past time. I ended with business-type themes, so this is not my problem anymore. And those plugins will not be developed anymore.
