### ISSUE TITLE
Allowfullscreen don't work correctly

### ISSUE THREAD

**Issue by KiraTheUltimate** [e107inc/e107#4486]
## Bug Description
On my website I share online videos from mega.nz. But when I create a page, add the embed code and save the page, with the video that I added if I click to put it out full screen, it doesn’t work.

Here is the original embed code generated by mega.nz:

`<iframe width="640" height="360" frameborder="0" src="https://mega.nz/embed/JWgRSLxS#AVFhrctsPgyTbI2A8J4JY1juNWb2hoDMF-vg5N6veKE" allowfullscreen ></iframe>`

If I editing the code, like this, then work the fullscreen:

`<iframe width="640" height="360" frameborder="0" src="https://mega.nz/embed/JWgRSLxS#AVFhrctsPgyTbI2A8J4JY1juNWb2hoDMF-vg5N6veKE" allowfullscreen allow="fullscreen"></iframe>`

So when I using allowfullscreen allow="fullscreen" then works.

But that's not what I want. I want it to work with the original code as well. What could be the problem? What should I change the theme?

## How to Reproduce
I created a test page... so, the first video is the original embed code, and the second is the modified. On the first video doesn't work the fullscreen, but second it working. ->

https://starwarsmedia.hu/oldalak/teszt

### PHP Version
Php Ver. 7.4

### e107 Version
e107 2.3.0.

Thank you for your helping!

**Comment by Deltik** [comment]
@CaMer0n: I'm not familiar with `e_parse`, but I think there are two issues here:

1. Attributes not in the allow list at `e_parse::$allowedAttributes` are allowed to be used anyway if the last attribute is not an allowed attribute.  The last attribute will be removed, and all the other attributes are preserved.  To reproduce, edit a page and add this HTML:
   ```html
   <iframe width="640" height="360" frameborder="0" src="http://allowed-attribute-test.local" this-attribute-should-have-been-removed="oh no" this-attribute-will-be-removed="bye"></iframe>
   ```
   If you save the page again, the attribute `this-attribute-should-have-been-removed="oh no"` will be removed.  The behavior appears to be that the last invalid attribute is removed every time, rather than all invalid attributes being removed at once.
2. `allowfullscreen` and `allow` should be considered allowed attributes for `<iframe>` tags.

**Comment by CaMer0n** [comment]
@KiraTheUltimate Those iframe attributes will now be accepted in e107 v2.3.1. 

@Deltik Thanks for spotting that.
