### ISSUE TITLE
`/e107_admin/menus.php` preview broken when different user theme is active

### ISSUE THREAD

**Issue by Deltik** [e107inc/e107#4527]
## Bug Description
Side effects from `e_parse_shortcode::__construct()` are preventing the layout preview at `/e107_admin/menus.php` from loading if the current admin user has a user theme set.

The cause is that `e107::getScParser()` has a side effect of loading the user theme shortcodes, but later, the layout loaded tries to load the default theme shortcodes, which may attempt redefining `theme_shortcodes`:
```
#0  e_parse_shortcode->loadThemeShortcodes() called at [C:\xampp74\htdocs\e107-2_3_1_git\e107_handlers\shortcode_handler.php:120]
#1  e_parse_shortcode->__construct() called at [C:\xampp74\htdocs\e107-2_3_1_git\e107_handlers\e107_class.php:1138]
#2  e107::getSingleton(e_parse_shortcode) called at [C:\xampp74\htdocs\e107-2_3_1_git\e107_handlers\e107_class.php:1491]
#3  e107::getScParser() called at [C:\xampp74\htdocs\e107-2_3_1_git\e107_handlers\theme_handler.php:121]
#4  e_theme::loadLayout(sidebar_right, bootstrap5) called at [C:\xampp74\htdocs\e107-2_3_1_git\e107_admin\header.php:475]
#5  require_once(C:\xampp74\htdocs\e107-2_3_1_git\e107_admin\header.php) called at [C:\xampp74\htdocs\e107-2_3_1_git\e107_admin\footer.php:34]
#6  require_once(C:\xampp74\htdocs\e107-2_3_1_git\e107_admin\footer.php) called at [C:\xampp74\htdocs\e107-2_3_1_git\e107_admin\menus.php:793]

#0  e_parse_shortcode->loadThemeShortcodes(bootstrap5) called at [C:\xampp74\htdocs\e107-2_3_1_git\e107_handlers\theme_handler.php:121]
#1  e_theme::loadLayout(sidebar_right, bootstrap5) called at [C:\xampp74\htdocs\e107-2_3_1_git\e107_admin\header.php:475]
#2  require_once(C:\xampp74\htdocs\e107-2_3_1_git\e107_admin\header.php) called at [C:\xampp74\htdocs\e107-2_3_1_git\e107_admin\footer.php:34]
#3  require_once(C:\xampp74\htdocs\e107-2_3_1_git\e107_admin\footer.php) called at [C:\xampp74\htdocs\e107-2_3_1_git\e107_admin\menus.php:793]
```

## How to Reproduce
1. Go to Menu Manager (`/e107_admin/menus.php`).
2. Activate `usertheme_menu`
3. Allow admin users to choose a different theme from the site theme
4. Using the menu now published, choose a different theme as an admin user
5. Go back to `/e107_admin/menus.php` and observe that the layout preview is now inoperative.

## Expected Behavior
Layout preview shows the site theme layout

## Screenshots
Bad:
![bad](https://user-images.githubusercontent.com/1364268/125439848-afc2f4e3-250b-43fa-8265-d1f0e5073375.png)

Good:
![good](https://user-images.githubusercontent.com/1364268/125439888-cf40559e-79f5-4d4c-962f-341b4967d74d.png)

## Additional Information
Report came from @Jimmi08 

Related issues:
* #4386
* #4506

**Comment by Jimmi08** [comment]
@Deltik I think I found it.

in the` batch/admin_shortcodes.php` there is 	public function` sc_admin_menumanager($parm=null)`
and it displays left menu this way:
`foreach($pref['sitetheme_layouts'] as $key=>$val)`

so the keys are layout keys from the site theme used (they are parameters for "configure" in preview).
But preview used USERTHEME and its layouts and it needs different keys/parameters. 

This was my test n attempt to fix this (yeah, testing defined is missing, but I was just playing)

```
        if(e107::getPref('sitetheme') !== USERTHEME) {
                            require_once(e_HANDLER."theme_handler.php");
        					$utheme = new themeHandler;
                            $ut = $utheme->themeArray[USERTHEME];
                            $layouts = $ut['layouts'];
        }
        foreach($layouts as $key=>$val) 
```

**But the correct solution is to use in Preview mode only site theme, ignore the user theme.**  With the actual way how menu areas work, it is useless, because themes can have not only different layouts but different menu areas for those layouts. 

What would be really helpful to use this functionality (theme change) is to have a list of themes with the same layout keys as the site theme, not all themes listed.

**Comment by Deltik** [comment]
I've got a fix for you, @Jimmi08: https://github.com/e107inc/e107/pull/4559
