### ISSUE TITLE
Why this db verification fails?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4532]
The table definition is a copy of some old version, so maybe there is the problem, but DB verification failed to detect missing one field in the database  

![image](https://user-images.githubusercontent.com/5429548/125918374-5e4729e8-96b9-483f-9a1c-b3105444b44d.png)

```
CREATE TABLE `fanfiction_pagelinks` (
  `link_id` int(11) NOT NULL auto_increment,
  `link_name` varchar(50) NOT NULL default '',
  `link_text` varchar(100) NOT NULL default '',
  `link_key` char(1) NULL, 
  `link_url` varchar(250) NOT NULL default '',
  `link_target` char(1) NOT NULL default '0',
  `link_access` tinyint(4) NOT NULL default '0',
  PRIMARY KEY  (`link_id`),
  KEY `link_name` (`link_name`)
) ENGINE=InnoDB;
```

**Comment by Deltik** [comment]
It looks like `CHAR` type fields are not detected because of a puzzling workaround that @CaMer0n introduced [on 02 November 2012](https://github.com/e107inc/e107/commit/95ae8d911d229378336526f37cb8338655e8e614#diff-940e04ed023a2601964002f97da3727414c057256735fc831fbd1fa1aab7703bR36).

I can find no reason why a space should be required after specifying the `CHAR` type.  This is why I have removed the limitation in [my pull request to rework class `db_verify`](https://github.com/e107inc/e107/pull/4508) ([see change](https://github.com/e107inc/e107/commit/78d9e4b4042075fcddc47da7ae95dce973c2bcda#diff-940e04ed023a2601964002f97da3727414c057256735fc831fbd1fa1aab7703bL39)).

Until then, you can apply this patch to your plugin database schema to make `CHAR` field types detected:

```diff
--- <unnamed>
+++ <unnamed>
@@ -2,9 +2,9 @@
   `link_id` int(11) NOT NULL auto_increment,
   `link_name` varchar(50) NOT NULL default '',
   `link_text` varchar(100) NOT NULL default '',
-  `link_key` char(1) NULL, 
+  `link_key` char (1) NULL, 
   `link_url` varchar(250) NOT NULL default '',
-  `link_target` char(1) NOT NULL default '0',
+  `link_target` char (1) NOT NULL default '0',
   `link_access` tinyint(4) NOT NULL default '0',
   PRIMARY KEY  (`link_id`),
   KEY `link_name` (`link_name`)
```

**Comment by Jimmi08** [comment]
Thank you, clear and fixed.
