### ISSUE TITLE
Download Page not showing downloads...

### ISSUE THREAD

**Issue by dimante** [e107inc/e107#463]
Getting : "No downloads yet, please check back soon" when there are indeed downloads.  Clicking on the link in the download itself renders a page with a breadcrum:

Downloads eSchoolPlus ProgramsAP / ACT Test Score Import Program *NEW (Version 3.0)

But when you path it back to the Downloads crum you get :  "No downloads yet, please check back soon"  Just no rhyme or reason to this...

**Comment by gary231178** [comment]
This bug is still present today. Have created my categories, added the downloads, but the downloads.php page displays no downloads yet please check back soon.
However if i navigate to the path of the download, it is active and downloadable.
e.g:-
http://www.ltnclan.com/e107_plugins/download/download.php (No downloads visible)
http://www.ltnclan.com/e107_plugins/download/download.php?view.1 (visible download)

Gary
