### ISSUE TITLE
Add export option to Admin/Navigation 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4639]
## Motivation
Easier export demo data for theme install demo 

## Proposed Solution
File:  `admin/links.php`

Change:
` protected $batchExport 	= true;`
is not working

**Comment by Moc** [comment]
@CaMer0n Do you know why adding `protected $batchExport = true;` does not work here? 

I suspect because of `handleListLinkParentBatch()` but I cannot figure out a fix.

**Comment by CaMer0n** [comment]
@Moc `$batchExport` wasn't working because `links_admin_form_ui::getList()` is overriding the base method `e_admin_form_ui::getList()` that is  in **admin-ui.php**

Once I updated `links_admin_form_ui::getList()` to match the list of options in `e_admin_form_ui::getList()` the 'export' option was visible again when `batchExport = true`.
