### ISSUE TITLE
Bug with my design

### ISSUE THREAD

**Issue by Shoke49** [e107inc/e107#4901]
Hello, I had a website that I closed in 2016. But now I want to resume it with the same design I had at the time.

But now I get an error message:

Bug :

**Fatal error: Uncaught Error: Undefined constant "e_PAGE" in /homepages/0/d938985505/htdocs/e107_themes/UnlimitedV2/theme.php:29 Stack trace: #0 /homepages/0/d938985505/htdocs/class2.php(1078): require_once() #1 /homepages/0/d938985505/htdocs/index.php(58): require_once('/homepages/0/d9...') #2 {main} thrown in /homepages/0/d938985505/htdocs/e107_themes/UnlimitedV2/theme.php on line 29**

Line 29 :

 **define("e_PAGECLASS", str_replace(substr(strrchr(e_PAGE, "."), 0), "", e_PAGE));**

Thank's !

**Comment by Jimmi08** [comment]
Don't use PHP 8 with outdated PHP theme code.

**Comment by Shoke49** [comment]
How I know the version of php used? please

**Comment by Jimmi08** [comment]
You should get this information from your hosting provider. But you can find in admin area too. Go to Admin, find About (last menu item in navigation) and there is PHP info. 
Your problem is that e_PAGE is not defined (and it causes fatal error in PHP8). From that code it is not clear what it is was used for. Quick fix is to test if it is defined and only then use that code.

**Comment by Moc** [comment]
Closing this. Your theme probably needs updating. Please contact the theme author or consider choosing a different theme.
