### ISSUE TITLE
Extended user fields with fixed list display wrong

### ISSUE THREAD

**Issue by nlstart** [e107inc/e107#498]
If a custom extended user field is defined with field type 'Predefined list' (e107_user_extended_struct.user_extended_struct_type = 9) with values M and F then Extended User Fields overview (e107_admin/users_extended.php) displays:
No file: ../e107_core/sql/extended_M,F.php

Expected behavior: just display "M,F"

**Comment by Moc** [comment]
Both on frontend and backend the user extended field 'gender' seem to work just fine. I cannot reproduce the error. Also the path to the files in the e107_core/sql folder seems to be set correctly in the code. 

Please reopen in case the issue is still there, with concrete steps to reproduce using the latest Github code.
