### ISSUE TITLE
Upgrade password handling

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#595]
Replace all md5 and new salt password functions with the php5.5 function (and compatibility code for older versions) 

More info: 
http://www.sitepoint.com/hashing-passwords-php-5-5-password-hashing-api/

**Comment by CaMer0n** [comment]
When PHP 5.5+ is detected, the stronger password encryption will now be used.

**Comment by cameron** [comment]
Just another reminder that I'm not the Cameron you're looking for 






On Tue, Jun 7, 2016 at 11:08 AM -0700, "Cameron" <notifications@github.com> wrote:












When PHP 5.5+ is detected, the stronger password encryption will now be used.

**Comment by CaMer0n** [comment]
@cameron I'm sorry about that. It must have notified you because of the mention in an earlier post by someone else. I have edited the old post, but you may need to 'unsubscribe' from this issue as you are listed as a 'participant'.

**Comment by cameron** [comment]
No sweat! Thanks for keeping it in mind :)






On Tue, Jun 7, 2016 at 5:25 PM -0700, "Cameron" <notifications@github.com> wrote:












@cameron I'm sorry about that. It must have notified you because of the mention in an earlier post by someone else. I have edited the old post, but you may need to 'unsubscribe' from this issue as you are listed as a 'participant'.
