### ISSUE TITLE
All icons in the media manager are showing as zip file icons...

### ISSUE THREAD

**Issue by dimante** [e107inc/e107#619]
![image](https://cloud.githubusercontent.com/assets/4084331/3200299/7a84df38-ed7a-11e3-9d1d-0c09b0ac94e2.png)
Again, this is a 1x to 2x upgrade.  Does that have something to do with this?

Thanks!
-D-

**Comment by CaMer0n** [comment]
@Jimmi08 could you please test your fix with a file that has an underscore "_"or dash "-" in the name?

**Comment by Jimmi08** [comment]
I will do, after this: https://github.com/e107inc/e107/issues/853

**Comment by Jimmi08** [comment]
Hi, tested. Localhost, windows, xampp, php 5.5.
Before change (today fresh install)
![image](https://cloud.githubusercontent.com/assets/5429548/6015833/f2de5262-ab79-11e4-9e30-864571654cec.png)
- the change made
Import file with underscore (twice the same)
![image](https://cloud.githubusercontent.com/assets/5429548/6015839/0d232486-ab7a-11e4-90a1-6db375d57ddd.png)
Media manager:
![image](https://cloud.githubusercontent.com/assets/5429548/6015859/306c7852-ab7a-11e4-8f7f-a5a9f6016b3b.png)

Test with dash, space, national character:
![image](https://cloud.githubusercontent.com/assets/5429548/6015959/4001cca8-ab7b-11e4-8f7a-298db53143b0.png)
import:
![image](https://cloud.githubusercontent.com/assets/5429548/6015970/5ccdd37c-ab7b-11e4-9d23-cc9f2d96bd7b.png)

Manager:
![image](https://cloud.githubusercontent.com/assets/5429548/6015973/65bddd88-ab7b-11e4-97d4-d5f30b5adf05.png)

**Comment by Jimmi08** [comment]
Fresh install:
![image](https://cloud.githubusercontent.com/assets/5429548/6067016/b8328bb6-ad71-11e4-933e-bf50edf518f8.png)

after changing this, picture are back
![image](https://cloud.githubusercontent.com/assets/5429548/6067007/a3d3ddd2-ad71-11e4-86a6-ab96098a53f3.png)

**Comment by Jimmi08** [comment]
Ok, tested again, fresh install, different comp (the same xampp with php 5.5)
- installation 
![image](https://cloud.githubusercontent.com/assets/5429548/6075948/ae389e82-addc-11e4-8edc-16fb780cda07.png)

- changin preg_match in form_handlers.php line 3152  
![image](https://cloud.githubusercontent.com/assets/5429548/6075956/d7727336-addc-11e4-8dc5-cfcf23d794e9.png)

Rekap, because this is really long issue.
1. preg_match (original code) works with php 5.4, it's written right way (tested on online regex tester). But in php 5.5 doesn't work and I wasn't find anything about it on google.  So in php 5.5 underscore causes problem.

**Comment by CaMer0n** [comment]
Perhaps a php 5.5 bug? I have moved this issue to beta2 to review again later.

**Comment by dimante** [comment]
As of my latest update the icons are showing up in the media manager now as expected!
