### ISSUE TITLE
media manager/importing bug

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#867]
I notice in the media manager when some one uploads an image and when you go in the admin area to so some image uploading you get this import feature of the uploaded images. I select which folder (or category) to file the image under and get a "cannot move, image already exist" or something like that. If the image already exsist than why do I need to import it again, and I have tried other folders such as news, avatars, downloads etc, get same error.

**Comment by Jimmi08** [comment]
This is error when there is already record in core_media table (image url is unique). When you do this via media manager (not import feature) it creates duplicate (rename it with underscore_) and you have 2 records in database. I am not sure if not only first time... 

I think that it's good feature, you don't accidentally rewrite image with the same name.  It could be better to have possibility to do something with it.  (Imagine: I had 20 images in import, rewrite all names, captions… and then stopped because they already existed – I forgot to rename the image url in database -  and I needed to rewrite everything again).

**Comment by LaocheXe** [comment]
So you can edit the URL name? I tried changing the name with no success

**Comment by Jimmi08** [comment]
If you mean image url for images f.e {e_MEDIA}/2015-02/imagename.png , I meant ad hoc... after importing to media folder.  I do it either manually in admin area or in database replacing string ' 2015-02' in media table. 
To be exact: I upload images to e107_media/images/myfolder,  then I use import feature (to create records in media table), then I delete  images in actual image folder (2015-02) and replace string in db. Or move content of actual folder to my folder.  
There is function for move files from one folder to second...  but I need to check each one, so I do it manually.

**Comment by CaMer0n** [comment]
Are these different images with the same name or attempting to upload the same file again? If you need the same file in a different area, it is better to add that category to the image with the media-manager.

**Comment by LaocheXe** [comment]
I uploadednlike 5 screen shots and after the first screenshot that was imported the others had issue importing, names where like this: screenshot 1.PNg screenshot 2.PNG etc

**Comment by CaMer0n** [comment]
@LaocheXe Please enable debug and then try again and check the System logs.

**Comment by Moc** [comment]
@LaocheXe Is this issue still happening?

**Comment by Moc** [comment]
Closing this as no feedback is given. Please re-open in case the issue persists.
