### ISSUE TITLE
URL Configuration

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#869]
It might be good to add the e107_plugins folder to this so it hides and/or makes the link shorter instead of going in and renaming the folders manually and changing the config and robots.txt file

Do it for all the e107_ folder's is my suggestion.

**Comment by CaMer0n** [comment]
If I understand well, you mean to have an alias for e107_plugins? 
eg. e107_plugins/faqs/faqs.php would be come -my-sef/faqs/faqs.php 
It has crossed my mind before.

**Comment by LaocheXe** [comment]
not just for plugins, for admin, images, and media

eg. e107_images/news/screen.jpg to -my-sef/news/screen.jpg (or other) - e107_media/(whateverfolder)/(images or avatars or any other folder in this direct/file.whatever to media (-my-sef)/whateverfolder/whateverfolder/file.whatisit

Stuff like that - would be a lot better using it than changing the files - but up to you guys if you want to add it or not.

**Comment by Jimmi08** [comment]
Are not Aliases in URL configuration just for this?

**Comment by CaMer0n** [comment]
I believe that SEF (Search Engine Friendly) URLS  should apply to the aspects of e107 which we want search-engines to index. How I see it: 

* e107_admin (internal use) although a shortcut could be useful (if it doesn't conflict with server)
* e107_core (internal use). 
* e107_docs (should probably be 'online' rather than in the folder). 
* e107_files (deprecated)
* e107_handlers (internal use)
* e107_images (internal use) 
* e107_languages (internal use)
* e107_media (not be linked directly, but via thumb.php etc. )
* e107_plugins (often linked to directly via sitelinks etc.) 
* e107_system (internal use)
* e107_themes (internal use. ie. loading theme)
* e107_web (internal use. ie. JS and CSS)
